### ISSUE TITLE
Create an archetype application demo using Spring

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#10]
- Same as the Vaadin 7 version, minimal code changes. 
- Spring Data / JPA
  - Use a multi select option group instead of a Custom field implementation
  - Lazy loading
  - Create a custom Vaadin data source for this example – don't implement a generic reusable SpringDataSource for this demo
- Validation using JSR-303, as in the Vaadin 7 version

**Comment by denis-anisimov** [comment]
Blocked by OptionGroup migrated to DataSource (#70).

**Comment by Artur-** [comment]
Everything except the option group can be done before that

**Comment by denis-anisimov** [comment]
Should it use BeanBinder ? Or direct JSR303 bean validator ?
So may be it's also blocked by BeanBinder

**Comment by Artur-** [comment]
Whatever is more suitable

**Comment by denis-anisimov** [comment]
Do you mean this https://github.com/vaadin/spring-tutorial by the way ?

**Comment by denis-anisimov** [comment]
Almost nothing is done (because can't be) except Spring migration.
Issues #155-#158 are created.
https://github.com/vaadin/framework8-demo/pull/10

**Comment by Artur-** [comment]
Initial version done
