### ISSUE TITLE
Add onChange shortcut to AbstractField

### ISSUE THREAD

**Issue by jdahlstrom** [vaadin/framework8-issues#106]
```
public interface OnChange<T> extends Consumer<T>, Serializable {} 

public Registration onChange(OnChange<T> listener) {
    Objects.requireNonNull(listener, ...);
    addValueChangeListener(e -> listener.accept(e.getValue()));
}
```

**Comment by Legioth** [comment]
Could also consider whether this would make more sense as a default method in `HasValue` instead

**Comment by Artur-** [comment]
First should consider if it makes sense to have. Dev UX tests showed it is hard to understand the difference between `addValueChangeListener` and `onChange`. Also whether `onChange` adds a listener or overwrites an existing one

**Comment by pleku** [comment]
COULD HAVE, but not necessary for FW8.
