### ISSUE TITLE
Review AbstractFieldConnector in order to use correct state

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/framework8-issues#109]
The ticket #108 is about renaming an old AbstactFieldState.
But AbstarctFieldConnector has a logic which relies on old AbstactFieldState impl.
The connector class is still used by the new implementation (TextField e.g.) but it's not in sync anymore with the server side since state class is different.
AbstarctFieldConnector and its descendants should be reviewed to check that they uses correct state on the client side (and their logic should be updated correspondingly).

**Comment by Artur-** [comment]
Thias was fixed at some point
