### ISSUE TITLE
Dynamically enable/disable form save button in archetype demo

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#11]
"Save" is enabled when
- At least one change has been made
- All fields validate

"Discard" is enabled when
- At least one change has been made

The state is updated when typing a new value, does not require blurring any field

**Comment by denis-anisimov** [comment]
This is blocked by #155, #157.
There is no sense to do it for old functionality implemented using FieldGroup.

**Comment by pleku** [comment]
blocked by #208
