### ISSUE TITLE
Review package names for new classes

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#110]
HasValue is in com.vaadin.data, which seems a bit strange as it is related to fields. Should review the package of all new classes.

**Comment by pleku** [comment]
@Legioth please clarify is this a part of the "new DoDo" and add or close.

**Comment by Legioth** [comment]
One might also wonder about the difference between `com.vaadin.server.data.Sort` and `com.vaadin.data.sort.Sort`. Each also has a corresponding `SortOrder` class.

**Comment by tsuoanttila** [comment]
old Sort and SortOrder should be tossed into the v7 package, Grid needs the sorting API with the new Sort and SortOrder with Column<T, ?>

**Comment by tsuoanttila** [comment]
Opened a ticket for the metioned Grid part #557

**Comment by Legioth** [comment]
The destiny of the other `Sort` and `SortOrder` pair is now in #563.
