### ISSUE TITLE
Renaming DataSource -> DataProvider to avoid collisions with javax.sql.DataSource

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#111]
Fix all variable names, documentation, javadocs and comment mentions for *source related to this case.

**Comment by jdahlstrom** [comment]
"Data" is a supergeneric term - why can't I use a "data source" with my TextField? The name should somehow denote that it's a source for beans/items/rows.

**Comment by pleku** [comment]
COULD HAVE, but not necessary for FW8.

**Comment by mstahv** [comment]
WTF, so this is now closed? This is kind of thing that we probably cannot change for the next n years once released. And as I have stated before on other channels, this is a bad name.

cc: @macjuan

**Comment by Legioth** [comment]
@mstahv Any suggestions for a better name?

**Comment by macjuan** [comment]
Need some suggestions for a better name here. If there are no suggestions what this could be then we'll ship 8 with this.

**Comment by Artur-** [comment]
`DataProvider`? This is used for the same thing internally already: `DataProviderRpc`

**Comment by mstahv** [comment]
IIRC I already googled DataProvider when we discussed about this with @Artur- in the summer and it would work much better. Not big fan of the data word either though. I'd use domain specific words, RowProvider or OptionProvider, depending on component.

**Comment by macjuan** [comment]
DataProvider it is. @pleku please make it sow!

**Comment by elmot** [comment]
https://dev.vaadin.com/review/#/c/14775/
