### ISSUE TITLE
Binder.forField should handle properly invocation for the same field

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/framework8-issues#112]
The Binder.forField method should either be idempotent or disallow to call it twice for the same field.

I would prefer idempotent behavior since implementation is almost the same.
But right now it's a bug in A Binder since it will create a new Binding instance.

**Comment by Artur-** [comment]
Doing Binder.forField for an already bound field should throw an IllegalArgumentException

**Comment by pleku** [comment]
SHOULD HAVE, but not necessary for FW8.
