### ISSUE TITLE
Slider should not be a field

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#113]
Slider is pretty close to an AbstractField but is not really a field. For instance clear() and isEmpty() make sense for fields but not for a Slider. 

If needed there could be an AbstractComponentWithValue which Slider can extend and AbstractField would extend ACWV. This might make sense if also Label, ProgressBar and others can extends ACWV.

**Comment by jdahlstrom** [comment]
Slider should definitely be a Field (a component with a value that can be edited/adjusted by the user), but isEmpty/clear do not make sense for all fields.

**Comment by Artur-** [comment]
Let it be a Field
