### ISSUE TITLE
Fix tests broken on new Chrome 52

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#116]

**Comment by hesara** [comment]
Fixing first those relevant also for 7.7, then rest if applicable

**Comment by hesara** [comment]
- expected Chrome version updated for 7.7 branch and master
- screenshots updated for 7.7 branch and master (tests that failed for 7.7)

To check other failures

**Comment by hesara** [comment]
JavaScriptPreloadingTest (socket timeout) and  SplitPanelWithMinimumAndMaximumTest (minimum size not correctly enforced but 1.9px off) still broken on Chrome 52 (master and 7.7 branches) - not currently working on them

**Comment by Artur-** [comment]
Muted remaining tests with descriptions of why they are broken (Chrome issues)
