### ISSUE TITLE
Add bean level validation to spring archetype demo

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#12]
If stock > 0, then price must be > 0, otherwise price=0 is ok

**Comment by denis-anisimov** [comment]
Blocked by #10.

**Comment by denis-anisimov** [comment]
Blocked by #155 and #157.
The issue cannot be done until the demo is migrated to the Binder.
At the moment it still uses BeanFieldGroup.

**Comment by pleku** [comment]
SHOULD HAVE, but not necessary for FW8.
