### ISSUE TITLE
Research and decide on migration/backwards compatibility package

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#121]
Ideally, we could have old components in a separate package in a separate jar so that they would have the same API as in V7. They should be implemented using the V8 components to avoid duplicate effort.

This would mean e.g. com.vaadin.legacy.ui.CheckBox extends com.vaadin.ui.CheckBox where com.vaadin.legacy.ui.CheckBox contains all the public API which is in com.vaadin.ui.CheckBox in V7

**Comment by Artur-** [comment]
https://dev.vaadin.com/review/14085

**Comment by samie** [comment]
We can also use major version numbers in package name to distinct APIs. Like com.vaadin.v7.ui.ComboBox. Whis can also help in future major versions.

**Comment by Artur-** [comment]
Done in

https://github.com/vaadin/vaadin/commit/402a103 Duplicate AbstractField state and connector into compatibility-client
https://github.com/vaadin/vaadin/commit/0732591 Organize imports
https://github.com/vaadin/vaadin/commit/a93eae1 Use new Label instead of old
https://github.com/vaadin/vaadin/commit/18be149 Remove Legacy prefix
https://github.com/vaadin/vaadin/commit/a23bf94 Move and duplicate client side and state to compatibility package
https://github.com/vaadin/vaadin/commit/b31a71a Move and duplicate client side and state to compatibility package
https://github.com/vaadin/vaadin/commit/b965c25 Move and duplicate client side and state to compatibility package
https://github.com/vaadin/vaadin/commit/ce35755 Fix OSGi support in compatibility packages
https://github.com/vaadin/vaadin/commit/9fce56f Move V7 Converter and ConverterFactory to compatibility package
https://github.com/vaadin/vaadin/commit/653a24f Mark java validation packages as optional for OSGi
https://github.com/vaadin/vaadin/commit/13b99cf Move remaining Vaadin 7 classes to the compatibility package
https://github.com/vaadin/vaadin/commit/44cb252 Remove dependency from ErrorMessage to old exception types
https://github.com/vaadin/vaadin/commit/73e3062 Move old converters and DefaultConverterFactory to compatibility package
https://github.com/vaadin/vaadin/commit/818f7d1 Remove Property dependency from TextField
https://github.com/vaadin/vaadin/commit/c11121e Move old Field and AbstractField to compatibility package
https://github.com/vaadin/vaadin/commit/58853fe Move old TextField to compatibility package
https://github.com/vaadin/vaadin/commit/50f2945 Move VOptionGroup and dependants to the compatibility package
https://github.com/vaadin/vaadin/commit/f183804 Move PasswordFieldConnector to correct package
https://github.com/vaadin/vaadin/commit/24a888a Move old PasswordField to compatibility package
https://github.com/vaadin/vaadin/commit/9adce46 Convert LoginForm to use new TextField
https://github.com/vaadin/vaadin/commit/ee5e3ec Clean up LoginForm
https://github.com/vaadin/vaadin/commit/d140deb Move Vaadin 7 CheckBox to compatibility package
https://github.com/vaadin/vaadin/commit/0055a46 Reintroduce variables used in OSGi manifests
https://github.com/vaadin/vaadin/commit/ac74d37 Move Vaadin 7 CustomField to compatibility package
https://github.com/vaadin/vaadin/commit/c6c071a Move LegacyWindow back to com.vaadin.ui
https://github.com/vaadin/vaadin/commit/2713507 Change declarative support to use new converters
https://github.com/vaadin/vaadin/commit/38b825c Convert Vaadin 7 converters to Vaadin 8 converters
https://github.com/vaadin/vaadin/commit/fa2a40b Move Item to compatibility package
https://github.com/vaadin/vaadin/commit/33b0e33 Move ProgressBar/ProgressIndicator to correct package
https://github.com/vaadin/vaadin/commit/7daee06 Move Container to compatibility package
https://github.com/vaadin/vaadin/commit/8328038 Rename packages in compatibility-client to use com.vaadin.v7
https://github.com/vaadin/vaadin/commit/a687305 Move ProgressBar/ProgressIndicator to compatibility package
https://github.com/vaadin/vaadin/commit/c6b44ac Move and rename server classes which go into the compatibility package
https://github.com/vaadin/vaadin/commit/762ca74 Include compatibility packages in bom
https://github.com/vaadin/vaadin/commit/6c7d2da Map <vaadin7> declarative prefix to com.vaadin.v7.ui
https://github.com/vaadin/vaadin/commit/17b6232 Remove unused test themes
https://github.com/vaadin/vaadin/commit/dd58702 Move DateField and old validators to compatibility package
https://github.com/vaadin/vaadin/commit/cfe3798 Move TextArea to compatibility package
https://github.com/vaadin/vaadin/commit/f238807 Move RichTextArea to compatibility package
https://github.com/vaadin/vaadin/commit/fe3dca0 Move remaining selects and container implementations to compatibility package
https://github.com/vaadin/vaadin/commit/65370e1 Move Table/TreeTable to compatibility package
https://github.com/vaadin/vaadin/commit/34852cd Move selects to compatibility package
https://github.com/vaadin/vaadin/commit/6e0f2ef Move FieldGroup and Vaadin 7 Grid to compatibility package
https://github.com/vaadin/vaadin/commit/d4dfb58 Use the same groupId for all modules in the project
https://github.com/vaadin/vaadin/commit/e7b9db5 Use versions-maven-plugin 2.3 to avoid NPE while setting project version
https://github.com/vaadin/vaadin/commit/599f6fa Remove dependencies from core framework to old componnets
https://github.com/vaadin/vaadin/commit/1b73770 Add Vaadin 7 compatibility modules
https://github.com/vaadin/vaadin/commit/b565956 Remove accidental dependency from new converters to old
https://github.com/vaadin/vaadin/commit/a836efc Define common test dependencies in the main pom file
https://github.com/vaadin/vaadin/commit/e10ec4c Define dependency version in the main pom file
https://github.com/vaadin/vaadin/commit/f3c8801 Rename legacy packages to v7
