### ISSUE TITLE
Decide whether to drop TestBench 2 support

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#123]
LegacyLocatorStrategy implements support for old TestBench 2 type selectors. It causes dependencies between the core framework and component implementations.

**Comment by zch** [comment]
This would basically kill support for TestBench 3 in FW8. No big deal, except for all our tests that use these – what does this mean for our test coverage?

**Comment by Artur-** [comment]
All framework tests are Java JUnit tests so they are not affected. TB2 tests were removed a while back

**Comment by hesara** [comment]
At least the Liferay integration test still uses TB2, but there is a migrated initial version in gerrit at https://dev.vaadin.com/review/#/c/3332/ (with some issues on older browsers that are not relevant in Vaadin 8).

**Comment by Artur-** [comment]
The Liferay test needs to be changed anyway because it tests Liferay 6.0 on Tomcat 6. Additionally it does not use TB2 selectors although it is in HTML format

**Comment by zch** [comment]
Do all of our JUnit tests use the "new" TestBench Elements APIs, OR do they still use old xpath-style Vaadin locators? Removing LegacyLocatorStrategy would kill any test that uses the old xpath-style Vaadin locators.

Do we have a picture of what tests (other than the Liferay tests) would stop working after this kind of change?

**Comment by Artur-** [comment]
This is a non issue for the framework project, is it an issue for anything else?

**Comment by zch** [comment]
If it's a non issue for the framework project, then kill it. It's not an issue for new apps built with Vaadin Framework 8.
