### ISSUE TITLE
Decide on server support

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#124]
Vaadin 7 supports (vaadin.com/features, separated portals to its own list):

Portals:
- eXo Platform 3 or newer
- GateIn Portal 3.1 or newer
- Liferay Portal 5.2 or newer

Servlet containers:
- Apache Tomcat, version 5.0 or newer
- Glassfish, version 2.0 or newer
- Google App Engine (Due to GAE architecture, it is not recommended for large Vaadin applications.)
- IBM WebSphere® Application Server, version 7 or newer
- JBoss Application Server, 4.0.0 or newer
- Jetty, version 5.0 or newer
- Oracle WebLogic® Server, version 10.3 or newer
- WildFly 8 or newer

"Vaadin supports Java Servlet API 2.4 and JSR-286 Portlet Specifications works with any Java application server that conforms to these standards."

Based on that Vaadin 8 requires Java 8 and Servlet API 3.0 (or JSR-286) we should probably change support to:

Portals:
- eXo Platform (???)
- GateIn Portal (???)
- Liferay Portal 6.2
- Liferay Portal 7 (might need additional work as it is OSGi based)

Servlet containers:
- Apache Tomcat, version 7.0 or newer
- Glassfish, version 4.0 or newer
- Google App Engine (???)
- IBM WebSphere® Application Server, version 8.5.5.9 or newer (???, 8.5 does not support Java8 until  8.5.5.9, version 9 is built on Java 8)
- WildFly 8 or newer
- JBoss EAP 6.0 or newer
- Jetty, version 8.0 or newer
- Oracle WebLogic® Server, version 12.1.3 or newer (12.1 is built on Java 7, 12.2 is built on Java 8)

JBoss Application Server is nowadays Wildfly

Additionally what may affect the list is that if we decide a JavaEE version to support, e.g. JavaEE 7+

**Comment by Artur-** [comment]
Relevant parts of JavaEE7:
- CDI 1.1
- Servlet 3.1 (no reason not to support 3.0+)
- Bean validation 1.1
- Java API for WebSocket

WebLogic 12.2 supports JavaEE7, Websphere 8.5.5.9 supports "6 and 7" according to https://en.wikipedia.org/wiki/IBM_WebSphere_Application_Server, Websphere 9.0 supports JAvaEE7

**Comment by zch** [comment]
Portals:
- Liferay Portal 6.2
- Liferay Portal 7 (might need additional work as it is OSGi based)

Servlet containers:
- Apache Tomcat, version 7.0 or newer
- Glassfish, version 4.0 or newer
- IBM WebSphere® Application Server, version 9 or newer
- WildFly 8 or newer
- JBoss EAP 6.0 or newer
- Jetty, version 8.0 or newer
- Oracle WebLogic® Server, version 12.2 or newer

**Comment by Artur-** [comment]
and primarily JavaEE 7
