### ISSUE TITLE
DateField server side should be based on LocalDate

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#125]
The value type of DateField should be LocalDate.

Support for time zones and picking time-of-day should be removed.

Resolution constants for SECOND,MINUTE,HOUR should be deprecated. Setting the DateField resolution to any of these will set the resolution to DAY. Changing Resolution so that there will be compile errors is done separately.

**Comment by hesara** [comment]
Also change BoV and example to use LocalDate when this is implemented - see https://dev.vaadin.com/review/#/c/14113/

**Comment by denis-anisimov** [comment]
Example will have to be updated since it won't compile anymore (if DateField is going to be updated to use LocalDate, not new class for LocalDate created).
But BoV should be updated, yes.

**Comment by Artur-** [comment]
There is still the question of selecting time which needs to be resolved. Also might need resolving the DateField vs PopupDateField issue, maybe there should be no DateField except for v7.DateField

**Comment by Artur-** [comment]
Time support will be dropped

**Comment by denis-anisimov** [comment]
Should not be taken before #297 is merged (to avoid merge nightmare).

**Comment by Legioth** [comment]
#297 is merged, so this one can be taken now.

**Comment by denis-anisimov** [comment]
https://dev.vaadin.com/review/14502
