### ISSUE TITLE
Decide which themes to include and which is the default

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#133]
Currently the default is still "reindeer"

Included themes are
- (base)
- valo
- reindeer
- runo
- chameleon

**Comment by zch** [comment]
Make Valo the default.

What would be some reasons for keeping the other (old) themes?

**Comment by Artur-** [comment]
Backwards compatibility. The other ones could also be retained in a "compatibility" package

**Comment by zch** [comment]
Put the other themes in a "legacy themes" package or similar to be used for easing the upgrade from 7 to 8. They don't need to be included by default.
