### ISSUE TITLE
Unify Converter/Validator locale-awareness

### ISSUE THREAD

**Issue by jdahlstrom** [vaadin/framework8-issues#136]
`Converter` and `Validator` gets a `ValueContext` which includes
- `getLocale : Locale`
- `getComponent : Optional<Component>`

**Comment by jdahlstrom** [comment]
FWIW, my opinion is that there's not much value in passing the locale to the methods. It can usually be passed either in a constructor or implicitly in a closure, for those convertelidators that need it.

**Comment by tsuoanttila** [comment]
After an ad-hoc design discussion, we decided to not include locale for the Validators, only for the Converters. This needs to be documented in some place where users will actually notice this.

**Comment by Legioth** [comment]
#417 points out one reason for why we should actually also make Locale available to validators: formatting of error messages. I'll create a separate issue about this.
