### ISSUE TITLE
Improve BeanBinder error handling

### ISSUE THREAD

**Issue by jdahlstrom** [vaadin/framework8-issues#137]
Binding a field to a property of an incompatible type without a converter, or an inappropriate converter, should result in clear and early error message.

**Comment by pleku** [comment]
SHOULD HAVE, but not necessary for FW8.

**Comment by pleku** [comment]
`BeanBinder` has been merged into `Binder` and currently using `Binder.bindInstanceFields` throws an `IllegalStateException`, so I consider this one implemented. Not sure what other case this would have meant

**Comment by Legioth** [comment]
This is not implemented. I created a more specific issue: https://github.com/vaadin/framework/issues/8389
