### ISSUE TITLE
Migrate grid editor to Binder

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#138]

**Comment by denis-anisimov** [comment]
Grid Column class has method `setEditorField()` method whose implementation uses `editorFieldGroup` field in a Grid. This is fieldGroup that requires migration to new Binder API.

The GridEditorCustomField UI test should be migrated as a part of the issue.

**Comment by pleku** [comment]
Blocked by #436

**Comment by pleku** [comment]
Proposed design and implementation as a comment in #436, but needs decision, and grooming for this ticket.

**Comment by pleku** [comment]
Based on spike #436, did a quick design for this with @tsuoanttila who will implement a first draft version of this up for evaluation.

**Comment by hesara** [comment]
Current draft (in progress, missing tests) at https://dev.vaadin.com/review/14790

**Comment by tsuoanttila** [comment]
Couple of iterations done, getting to the point where I need to reintroduce all the tests and we might be able to proceed.
