### ISSUE TITLE
Extends Binder API with Consumer<Binding> as a configuration operation

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/framework8-issues#139]
Examples shows that it's not really convenient to use Binding configuration all in one chain:

there are many similar operations for various fields that differs only by validators and getter/setter functions ( + perhaps status change handler).

It's convenient to have one method in the user application code which creates a field and attaches validator + do binding instead of doing it inplace for every field.

But as a result such method requires too many parameters (only getter/setter give two parameters).

So instead of providing a number of parameters into the  method it's better to pass a configuration operation as a Consumer<Binding>.
In that case all common field config may be done in the method and all binding config will be done as an implementation of Consumer<Binding>.

Also I have a feeling that Binding should not be exposed as a standalone object which is done via `forField` method.

API could be changed in the way that Biding is passed as an argument to Consumer<Binding> operation which has to be implemented by the user instead of returning it as a value.

So smth like 
`configure(HasValue<?> field, Consumer<Binding> configOperation)` could be added (or as a replacement for `forField`).

**Comment by Legioth** [comment]
I'm not sure I understand what this means. Could you please provide a short example of what application code would look like?

**Comment by jdahlstrom** [comment]
So if I understand correctly this is about adding a callback to Binder that would get each added binding and do some common configuration for all of them.  But I'm not sure how much common config there actually is - OTOH Denis is the one who has actually written demo code using Binder. Should take a look and see .

**Comment by denis-anisimov** [comment]
Right now Binding is exposed as a return value.
Then you are using it in chain to configure.
And the chain is kind of the only way to use it (so there are checks that prevent you to call one more time `forField` which normally should be idempotent).

And there is a question: why do we need to expose Binding at all ?

Instead user could implement operation which takes a Binding instance as a parameter:

``` java
Binder<?> binder;
HasField<?> field;
binder.configure(field, new Consumer<Binding>(){
  public void accept( Binding binding){
      binding.withValidator(xxxx);
      binding.withConverter(xxxx);
  }
});

```

Instead of 

``` java
binder.forFiel(field).withValidator().withConverter();

```

The suggested way clearly defines the beginning of configuration code and the end of it.
Also in the end it makes clearer that provided `binding` instance becomes "closed" so there is no way to proceed configure it (so if `bind` is called then it should not be used anymore).

This pattern is used here:
https://github.com/vaadin/framework8-demo/blob/af66e6c3d41ff4278371b81a6e844e4b0efd98e1/registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java

**Comment by pleku** [comment]
COULD HAVE, but not necessary for FW8.
