### ISSUE TITLE
Renderers for Grid

### ISSUE THREAD

**Issue by tsuoanttila** [vaadin/framework8-issues#148]
The Renderers in Vaadin 7 for the Grid component were not actually as separate thing from the Grid as originally planned. Since we need to make some not-so-minor changes to the Grid itself, we need to make all the old renderers work with the new Grid.

**Comment by denis-anisimov** [comment]
Terrible issue.
No one who is out of the context is able to understand it.

Either assign this issue to yourself if you are too lazy or write everything required to fixe this issue so that anyone who doesn't know anything about this may start working on the issue.

**Comment by Artur-** [comment]
It's enough if old renderers work for com.vaadin.v7.Grid (after changing imports), and new renderers for com.vaadin.Grid.

**Comment by Legioth** [comment]
https://dev.vaadin.com/review/14320
