### ISSUE TITLE
Write an introductionary data binding text to BoV vol 1

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#15]
There should be a data binding part in BoV vol 1 which deals with creating a form for editing a bean, in a simple way. It should not contain a lot of details but instead refer to volume 2 for more details.

**Comment by jdahlstrom** [comment]
The current preview edition text needs to be updated to reflect the eventual final API

**Comment by pleku** [comment]
SHOULD HAVE, but not necessary for FW8.

**Comment by pleku** [comment]
There is a such documentation in BoV Vol 1
