### ISSUE TITLE
Frozen column support

### ISSUE THREAD

**Issue by tsuoanttila** [vaadin/framework8-issues#151]
Grid component needs Frozen columns like in Vaadin 7 Grid.

See: https://dev.vaadin.com/review/#/c/13842/

**Comment by denis-anisimov** [comment]
Terrible issue.
No one who is out of the context is able to understand it.

Either assign this issue to yourself if you are too lazy or write everything required to fixe this issue so that anyone who doesn't know anything about this may start working on the issue.

**Comment by tsuoanttila** [comment]
Added basic grid features of frozen columns and height modes.
https://dev.vaadin.com/review/#/c/14271/
