### ISSUE TITLE
OptionGroup - unit tests

### ISSUE THREAD

**Issue by elmot** [vaadin/framework8-issues#153]

**Comment by denis-anisimov** [comment]
Terrible issue.
No one who is out of the context is able to understand it.

Either assign this issue to yourself if you are too lazy or write everything required to fixe this issue so that anyone who doesn't know anything about this may start working on the issue.

**Comment by Artur-** [comment]
Let's write tests in the same issue as OptionGroup is implemented (#70) - how could we else know it works?
