### ISSUE TITLE
Do not call setSelectionRange when initializing a text field

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#154]
If you do, the field will be focused in IE11 and "partly" focused in Chrome (not shown as focused but typing anything will make the field focused)

**Comment by Artur-** [comment]
This causes TextFieldBevelTest to fail in IE11

**Comment by Artur-** [comment]
The easiest solution is probably to make setCursorPosition/setSelectionRange an RPC call instead of a state variable as state variables are always set on the initial request (and cursor position should be set if it is set during TextField initialization on the server)

**Comment by jdahlstrom** [comment]
yes, cursor/selection stuff should be RPC as it's a one-time setting, not a permanent state

**Comment by hesara** [comment]
https://dev.vaadin.com/review/14212
