### ISSUE TITLE
TimeField CustomField demo

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#16]
Demonstrates how you can create a custom TimeField for selecting a time, including a time zone, from a list with given intervals 
- TimeField value type is OffsetTime
- Contains two dropdowns beside each other
  - First one contains times with 30min intervals (00:00 - 23:30)
  - Second one contains time zones
- Internally uses a ComboBox<LocalTime> and a ComboBox<ZoneOffset/ZoneId>

Example app which uses
- A DateField to select the date
- The custom field to select time
- Everything bound to

```
public class Person {
   private ZoneOffset homeTimezone;
   private LocalDateTime nextAppointment;
```

**Comment by denis-anisimov** [comment]
Blocked by the CombobBox migration issue.

**Comment by pleku** [comment]
SHOULD HAVE, but not necessary for FW8.
