### ISSUE TITLE
Consider renaming HasValue to ValueSource

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#162]
HasValue really denotes something which can provide a value to the model (a component, a selection, ...) so a more logical name would be ValueSource. Binder then binds a ValueSource to a Model, instead of a "HasValue which ls like a field" to "something"

**Comment by jdahlstrom** [comment]
Input? InputSource?

**Comment by pleku** [comment]
@Legioth please clarify is this a part of the "new DoDo" and add or close.

**Comment by pleku** [comment]
As looking current content inside HasValue, it is starting to make sense to rename HasValue to Field... or something better ?

**Comment by pleku** [comment]
Hey @Artur- thanks for the feedback. Decided to not do this.
