### ISSUE TITLE
Jax RS Rest API Demo initial version

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#17]
Demo which shows read only person data
- Data source http://api.randomuser.me/?seed=12&results=200&page=1
- Grid data type is a bean loaded using JAX RS
- Shows
  - full name
  - email
  - Location in 4 columns: street, postcode, city, state

Initial version does not need lazy loading, only shows the 200 results

**Comment by ahie** [comment]
PR at https://github.com/vaadin/framework8-demo/pull/17
