### ISSUE TITLE
Create and test declarative syntax for all new field components

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework8-issues#183]
Go through all field components and verify that they have declarative syntax tests for all the attributes and possible child elements.

**Comment by Artur-** [comment]
Relevant parts:
* Document which old abstract select features no longer work
* Document which old abstract field features no longer work
* Document features in new abstract listing
* Document features in new abstract field

All other component API should be compatible, probably with a few exceptions

**Comment by denis-anisimov** [comment]
https://dev.vaadin.com/review/14600
