### ISSUE TITLE
Write a migration guide

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework8-issues#187]
Should tell
- What the fundamental differences are between Framework 7 and 8 (couple sentences per item max) and a link to the corresponding book page (web)
  - Binder
  - Data sources
  - New fields
  - New selects
  - Themes
  - Changes in defaults
  - Changes in components
- How you get up and running aka quick'n'dirty migration
  - compatibility packages
  - `Vaadin7WidgetSet`
  - change imports
  - change declarative files
  - where `vaadin8-migratin-tools` might help and how to use it
- How you do a real migration
  - Forms
    - Old fields -> new fields
    - `FieldGroup` -> `Binder`
    - Validator migration
    - Converter migration
  - Data sources
    - `BeanItemContainer` -> `DataSource`
    - `IndexedContainer` -> `DataSource`
    - `JPAContainer` -> `DataSource`
    - `SQLContainer` -> `DataSource`
    - Hierarchical container -> Hierarchical container (no changes)

The document should be placed in `documentation/migration/migrating-to-vaadin8.asciidoc`

**Comment by macjuan** [comment]
Replace should with shall.

**Comment by Legioth** [comment]
Example of simple full migration: https://github.com/Legioth/vaadin-stepbystep-demo-contacts/commit/2e1bc40211e4e0af009220adcf727dac80a50221

Example of stepwise migration: https://github.com/Legioth/commit-browser/commits/master
