### ISSUE TITLE
Addressbook demo - support for sub forms

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#19]
Depends on #9 

Change so that each Contact has List<PhoneNumber> instead of a String field for the phone number
- PhoneNumber has 
  - Role role
  - Roles can be "Home","Mobile", "Work","Fax"
  - String number
- Form contains
  - Role: [Home \/]  Number: [  123123]  x
  - Role: [          \/]  Number: [              ]
- There is always an empty row (last) to enter new data
  - Writing any text in this adds a new empty row
  - There is no explicit "add" button
  - There is a remove button ("x") at the end of each row
    - The last (empty) row has no "x" button
  - Number can only contain spaces+numbers, and optionally start with "+"

**Comment by Artur-** [comment]
Requires NativeSelect

**Comment by pleku** [comment]
SHOULD HAVE, but not necessary for FW8.
