### ISSUE TITLE
UX: CDN usage is confusing

### ISSUE THREAD

**Issue by zch** [vaadin/framework8-issues#190]
CDN usage can be very confusing as the app first says that it couldn't be loading because it might be compiling and then after clicking ok (retry), it says that loading failed.

https://dl.dropboxusercontent.com/u/379904/widgetsetCDN.png

**Comment by zch** [comment]
Sami E has ideas on how the UX could be improved.

**Comment by Artur-** [comment]
Maybe @samie could add those ideas here?

**Comment by zch** [comment]
@samie's thoughts: https://docs.google.com/document/d/1L5xyDwcwxMbarH-dgFA7uw-ASFfNMVnJ6Z3ra3ZuSfA/edit?ts=57ceb092

**Comment by Artur-** [comment]
Can't do anything about this until it is clarified what should be done

**Comment by zch** [comment]
The idea in the document has been clarified, and is sound.
- Display a (Valo CSS) progress bar while compiling
  - Add a text label describing what's happening ("Queuing compilation",  “Resolving dependencies”, “Compiling”, “Publishing”
  - Add a status REST end-point:
    - Add estimatedCompileTime field
    - Add elapsedCompileTime field
    - Use info field for reporting compilation phase 
- Handle errors as follows:
  - Errors are clearly indicted with text and colors
  - Possible error states:
    - Network error (Action: check network, retry)
    - Widgetset not available in CDN (Action: retry, recompile)
    - Compilation failed (Action: check configuration, report to us)
    - Addon not found (Action: report to us)
    - Something else went wrong (Action: report to us)
