### ISSUE TITLE
Fields mapped to a bean property with @NotNull or @NotEmpty should be visually marked as required

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework8-issues#198]
Still needs to consider the exact details since e.g.  @NotNull would accept `""`, even though that is usually not considered acceptable for a required field.

This also relates to https://dev.vaadin.com/ticket/14746

**Comment by pleku** [comment]
SHOULD HAVE, but not necessary for FW8.

**Comment by Legioth** [comment]
#419 detaches the validation logic from the displaying of the standard required indicator. This means that we would only need some way of identifying which validation annotations are such that `field.setRequiredIndicatorVisible(true)` should be called when binding.

This could be done e.g. by configuring `Binder` with a list of annotation types or a predicate that checks each constraint to see if its semantics can be seen as "required." This would include at least `@NotNull` and `@Size(min = 1)` from the standard annotations in JSR-303, and maybe also supplemented with the commonly used `@NotEmpty` constraint defined by Hibernate Validator (though it should be implemented in a way that doesn't require Hibernate Validator classes to be on the classpath).

One open question is whether the configuration would be per `Binder` instance, or if it would be more useful to actually define this in a static fashion so that the same settings would be automatically used in all binders of the applications.

**Comment by pleku** [comment]
Issue moved to [vaadin/framework #8382](https://github.com/vaadin/framework/issues/8382) via [**ZenHub**](https://www.zenhub.com/)
