### ISSUE TITLE
Grid multiple headers

### ISSUE THREAD

**Issue by tsuoanttila** [vaadin/framework8-issues#199]
Headers and Footers can't be configured in the current Grid.

**Comment by Artur-** [comment]
Re-enable `GridContextClickTest.testFooterContextClickWithTypedListener` as part of this

**Comment by jdahlstrom** [comment]
Split the original ticket into this, #303, and #304; may need further splitting

**Comment by jdahlstrom** [comment]
Further split to #311 , #328, and #329
