### ISSUE TITLE
TodoMVC demo using Grid

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#20]
Specs from http://todomvc.com
- Add using a separate text field outside the Grid
- Todos shown in a Grid
- Inline editing of todos in the grid
- Item removal using "x" at the end of the row
- Filtering using given buttons

Data binding
- Uses JDBC and offset + limit when querying DB (not paging)

Simplifications:
- Theme does not have to be the same as on todomvc.com, Valo is good enough

**Comment by pleku** [comment]
initial version https://github.com/vaadin/framework8-demo/pull/11

When this PR gets in, will create further issues on missing thing which depend on grid renderer #148 and custom data source support #75 (?)
