### ISSUE TITLE
Revert ComboBox in compatibility packages to Vaadin 7.7 version or update 7.7 version to the version in the compatibility package

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#201]
ComboBox was refactored in Vaadin 8 before moved into the compatibility package. This will cause problems down the path as we suddenly have three ComboBox versions and should have two.

If the refactorings are deemed safe enough, they should be merged into 7.7

In either case, the code in compatibility-\* in master should be exactly the same as in 7.7

**Comment by denis-anisimov** [comment]
Abandoned patch for 7.7 : https://dev.vaadin.com/review/#/c/14476/

https://dev.vaadin.com/review/#/c/14488/
