### ISSUE TITLE
Run JSR-303 bean level validators automatically

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#206]

**Comment by pleku** [comment]
SHOULD HAVE, but not necessary for FW8.

**Comment by pleku** [comment]
@Artur- what was this issue about ? Run automatically _when_ ? Currently done after binding level validations pass. But when setting bean with `setBean`, no validation is run initially.

**Comment by Artur-** [comment]
Not 100% sure but it was closed in October so let's just forget it.
