### ISSUE TITLE
Dynamic form (aka BPM / CRM / ERP)

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#21]
Input: 
- Metadata describing the form fields
- Same fields as Person from basic AddressBook
- A Map<String, Object> containing the row data

Output: 
- UI for editing a row with callbacks for save

Demonstrates:
- Automatic creation of forms/fields based on metadata

**Comment by pleku** [comment]
SHOULD HAVE, but not necessary for FW8.
