### ISSUE TITLE
Focus and blur events for AbstractSelect

### ISSUE THREAD

**Issue by jdahlstrom** [vaadin/framework8-issues#214]

**Comment by jdahlstrom** [comment]
This needs some helper logic on the client side to keep track of focus/blur when the widget contains several focusable child widgets

**Comment by Artur-** [comment]
ComboBox, NativeSelect and OptionGroup implement FocusNotifier in 7.7
ComboBox implements FocusNotifier in master at the moment

Created #332, #333, #334 for NativeSelect, RadioButtonGroup, CheckBoxGroup
