### ISSUE TITLE
ValueChangeEvent.getSource should return HasValue

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#221]
Design decided on meeting 18.10. :
- `getSource` should return `HasValue`
- `getComponent` should return `Component`
- `ValueChange` should be `ValueChangeEvent` and extends `EventObject`, not `ConnectorEvent`

Might break demos, verify that still compiles.

**Comment by Legioth** [comment]
This causes problems since selection change events also kind of want to be value change events, but for those the connector and HasValue is not the same instance. Will have to reconsider this one once we have a clearer understanding of the overall picture.

Blocked by #331.

**Comment by jdahlstrom** [comment]
IMO should return something some subtype of Component. Both raw HasValue and ClientConnector are less than useful to the user.  Source for selection events should be the listing component, not the selection model (or worse, some internal adapter). As long as selection API is pretty different from value API, selection events should not be-sort-of value change events either.

**Comment by jdahlstrom** [comment]
If I call `t.addListener(...)` for some `t: T` I expect `getSource() == t`.  The static return type of `getSource()` should also be as close to `T` as possible; near-perfect match can be achieved with generics but might make signatures too confusing.

**Comment by Legioth** [comment]
> As long as selection API is pretty different from value API, selection events should not be-sort-of value change events either.

This would cause problems when integrating with `Binder`, since it assumes that it binds to something that fires value change events. This is not only about e.g. `forSelect`, but also e.g. the use cases that would be supported by #39.

**Comment by denis-anisimov** [comment]
https://dev.vaadin.com/review/#/c/14619/
