### ISSUE TITLE
Find a new API diff tool which works with Java 8

### ISSUE THREAD

**Issue by hesara** [vaadin/framework8-issues#227]
The current API diff tool used does not support Java 8. A working API diff build configuration (ideally also listing missing @since annotations) is needed to compile a full list of breaking changes and to keep track of changes between maintenance versions.

**Comment by Artur-** [comment]
https://siom79.github.io/japicmp/ seems to work: 
- http://artur.app.fi/diff-alpha1-alpha2.html

**Comment by Artur-** [comment]
Let's go with japicmp
