### ISSUE TITLE
Implement multiselect for Grid

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#232]
- Implement MultiSelection for communication
- `asMultiSelect() : MultiSelect` uses currently set multi select model
  - flags `setSelectionModel(SelectionModel)` to throw
- convert all V7 multi select tests for V8 Grid

**Comment by Artur-** [comment]
Depends on #331

**Comment by pleku** [comment]
Part 1 https://dev.vaadin.com/review/#/c/14778/

**Comment by pleku** [comment]
Support for multi select added, select all case split into #515
