### ISSUE TITLE
Fix Book of Vaadin examples where messages are joined using newlines and showed in a standard Label

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#238]
A newline will not be shown as a newline in a normal label. Either it should use HTML mode + `<br>` or something else

**Comment by ahie** [comment]
https://dev.vaadin.com/review/#/c/14575/

**Comment by Legioth** [comment]
The committed solution is not acceptable since it invites to script injection vulnerabilities.

**Comment by denis-anisimov** [comment]
Your own error messages are trusted enough , don't they ?

**Comment by Legioth** [comment]
How do I know that my own error messages do not in some cases contain user-provided values, e.g. `Invalid number: "one"`

**Comment by ahie** [comment]
Which solution would be better: Map the error strings through Jsoup.clean (or some other utility) or use preformatted?

**Comment by Legioth** [comment]
Preformatted would require customizing the styling to avoid the monospace font, so it seems like Jsoup.clean would be the clearest solution (though it's still a small distraction from the actual purpose of the code example)
