### ISSUE TITLE
Revert NativeSelect DOM structure change

### ISSUE THREAD

**Issue by tsuoanttila** [vaadin/framework8-issues#239]
The missing div around the select makes old TB element throw. we should not break backwards compatibility on a DOM level to avoid theming problems.

**Comment by Artur-** [comment]
Also remove the hack in `NativeSelectElement` when doing this

**Comment by jdahlstrom** [comment]
"we should not break backwards compatibility on Java API level to avoid breaking old applications"

**Comment by pleku** [comment]
Could be done with `VNativeSelect extends Composite` and then wrapping the `ListBox` with a `div`. Could have public API for `ListBox getListBox()` (orwhatnot) so that API doesn't need to be duplicated.
