### ISSUE TITLE
Move com.vaadin.server.data classes to com.vaadin.data

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#245]
Data classes are not related to the server (servlet/service) in any way

**Comment by jdahlstrom** [comment]
c.v.server.data classes are related to server-side data communication. c.v.data is for ~pure data model stuff.

 c.v.server is a huge mess currently with no coherent theme except "this happens on server". There are lots of high-level UI/comms stuff like extensions and connectors that don't have anything to do with servlet/service either. Also, FontAwesome.

**Comment by pleku** [comment]
@Legioth please clarify is this part of the "new DoDo" and add or close.

**Comment by Legioth** [comment]
Duplicate of #110
