### ISSUE TITLE
SelectionModels should have a common API for adding listeners

### ISSUE THREAD

**Issue by tsuoanttila** [vaadin/framework8-issues#248]
Right now adding a listener for selection is absolutely horrible. Some common APIs in selection models should exist and helpers should be provided in component APIs.

**Comment by jdahlstrom** [comment]
To do that either some interfaces need moving to shared, or a separate server-side SelectionModel interface needs to be added.

**Comment by Legioth** [comment]
I would say that `SelectionModel` should be server-side only and include API for adding listeners. In addition to this, there should be a much simpler client-side helper API that connectors can use.

**Comment by pleku** [comment]
SHOULD HAVE, but not necessary for FW8.

**Comment by pleku** [comment]
Implemented in 8.0.0.beta1
