### ISSUE TITLE
Unify communication constants

### ISSUE THREAD

**Issue by jdahlstrom** [vaadin/framework8-issues#249]
DataCommunicatorConstants has symbolic names for various strings used as JSON keys. CheckBoxGroupConstants has its own and CheckBoxConstants a few more. Some of these are redundant and some conflict. Should unify somehow.

**Comment by Legioth** [comment]
I have a feeling the unifying should really happen on the concept level and not only for those few constants.

**Comment by pleku** [comment]
@Legioth this is issue is missing from the "new DoDo", please add it or close it.
