### ISSUE TITLE
Binder.withConverter

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#25]
```
TextField yearOfBirthField = new TextField("Year of birth");

binder.forField(yearOfBirthField)
  .withConverter(
    new StringToIntegerConverter("Must enter a number"))
  .bind(Person::getYearOfBirth, Person::setYearOfBirth);

// Slider for integers between 1 and 10
Slider salaryLevelField = new Slider("Salary level", 1, 10);

binder.forField(salaryLevelField)
  .withConverter(Integer::doubleValue, Double::intValue)
  .bind(Person::getSalaryLevel, Person::setSalaryLevel);
```

```
binder.forField(yearOfBirthField)
  .withConverter(
    Integer::valueOf,
    String::valueOf,
    // Text to use instead of the NumberFormatException message
    "Please enter a number")
  .bind(Person::getYearOfBirth, Person::setYearOfBirth);
```

**Comment by jdahlstrom** [comment]
e03679d15dced63f3f72fa9ffe98d1d790f38621
- called "setConverter" (but can be called multiple times and chained properly)
- withConverter() overloads missing, instead Converter.from(...)

**Comment by denis-anisimov** [comment]
Custom ConversionException is used in DateField (it's quite unrelated to Converters functionality but it's just logically related).
This exception should be either kept as is (TODO should be removed) or some existing exception in Converters functionality should be used.
Anyway DateField requires update.

**Comment by Artur-** [comment]
In https://github.com/vaadin/vaadin/commit/f2bb3c886c0b68c9a4e8212d6625614575148f80
