### ISSUE TITLE
Refactor CheckBoxGroup to not rebuild the DOM for every change

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework8-issues#252]
The hack in CheckBoxGroupElement.selectByText should also be removed since it would no longer be needed.

**Comment by pleku** [comment]
SHOULD, but not a must for 8.0.0

**Comment by pleku** [comment]
Issue moved to [vaadin/framework #8408](https://github.com/vaadin/framework/issues/8408) via [**ZenHub**](https://www.zenhub.com/)
