### ISSUE TITLE
Binder.withValidator

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#26]
```
binder.forField(emailField)
  // Explicit validator instance
  .withValidator(new EmailValidator(
    "This doesn't look like a valid email address"))
  .bind(Person::getEmail, Person::setEmail);

binder.forField(nameField)
  // Validator defined based on a lambda and an error message
  .withValidator(
    name -> name.length() >= 3,
    "Full name must contain at least three characters")
  .bind(Person::getName, Person::setName);

```

```
binder.setForField(emailField)
  .withValidator(new EmailValidator(
    "This doesn't look like a valid email address"))
  .withValidator(
    email -> email.endsWith("@acme.com"),
    "Only acme.com email addresses are allowed")
  .bind(Person::getEmail, Person::setEmail);
```

**Comment by jdahlstrom** [comment]
8fcacd0a0afc5216d4d85898a28a39a846b66602
- called "addValidator"
- overload missing, instead Validator.from(...)

**Comment by denis-anisimov** [comment]
// This will make all current validation errors visible
Set<BinderResult> validationErrors = binder.validate();

if (!validationErrors.isEmpty()) {
  Notification.show("Validation error count: "
    + validationErrors.size());
}

**Comment by denis-anisimov** [comment]
8fcacd0a0afc5216d4d85898a28a39a846b66602 // basic validation
c674a979101001831391baa12dfebfdfef8e4278 // adds validate(), error reporting

**Comment by denis-anisimov** [comment]
https://dev.vaadin.com/review/14056
https://dev.vaadin.com/review/14055
