### ISSUE TITLE
Define API for setting user originated values

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#261]
`AbstractField` uses 
`protected boolean setValue(T value, boolean userOriginated)`

`SimpleSingleSelect` uses `setSelectedFromClient` and `setSelectedFromServer`

**Comment by jdahlstrom** [comment]
The problem is that the client talks in keys and the server in T. Would be nice to unify somehow though.

**Comment by pleku** [comment]
SHOULD HAVE, but not necessary for FW8.
