### ISSUE TITLE
Migrate changes from 7.7.1, 7.7.2, 7.7.3

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#262]
All changes from 7.7.1 must be migrated to master
- Component changes go into `compatibility-(server|client|shared)`
- Data binding and all other compatibility related fixes go into `compatibility-(server|client|shared)`
- Relevant component changes are ALSO merged into `vaadin-(server|client|shared)`

**Comment by Legioth** [comment]
Should not be done before #201 since 7.7.1 contains changes to ComboBox

**Comment by denis-anisimov** [comment]
https://dev.vaadin.com/review/14517
