### ISSUE TITLE
Add SelectionModel.Multi.setSelectedItems(Set<T> items)

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework8-issues#265]
This would allow doing bulk updates without firing lots of small events.

It would also help setting the selected items to come in a specific order without having to first remove them all and then adding them back in the desired order.

**Comment by jdahlstrom** [comment]
Yes, should be there to mirror getSelectedItems.

**Comment by pleku** [comment]
COULD HAVE, but not necessary for FW8.

**Comment by pleku** [comment]
Moved to vaadin/framework#8307
