### ISSUE TITLE
Refactor Listings

### ISSUE THREAD

**Issue by elmot** [vaadin/framework8-issues#270]
- Unify Selection Model between NativeSelect and RadioButtonGroup
- Reuse icon, caption, itemEnabled providers
- Make common superclass for RadioButtonGroup and CheckBoxGroup

**Comment by hesara** [comment]
Icon and caption providers also apply to (and are already present as interfaces in) ComboBox.

**Comment by elmot** [comment]
- Data generators refactoring/unification
- Tests unification

**Comment by elmot** [comment]
Blocked by #291

**Comment by pleku** [comment]
SHOULD HAVE, but not necessary for FW8.

**Comment by pleku** [comment]
This has been pretty much implemented for 8.0.0.beta1
