### ISSUE TITLE
Update sampler master to use 8.0-SNAPSHOT

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#271]
Roughly the steps needed should be:
1. Change Vaadin version from 7.7.0 to 8.0.0.alpha2
2. Import `vaadin-compatibility-server`/`vaadin-compatibility-shared`/`vaadin-compatibility-client`/`vaadin-compatibility-client-compiled` instead of `vaadin-server`/`vaadin-shared`/`vaadin-client`/`vaadin-client-compiled` 
3. Run the migration tool to update imports
4. Possibly extend or use Vaadin7WidgetSet instead of DefaultWidgetSet

Out of scope for this issue: Migration of old concepts to new

**Comment by pleku** [comment]
https://dev.vaadin.com/review/#/c/14434/
