### ISSUE TITLE
Update Liferay 6 test to TB4 for Framework 7.7

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#276]
The old TB2 test script is in https://github.com/vaadin/vaadin/blob/7.7/uitest/integration-testscripts/Liferay-6/integration-test-liferay-6.0.5.html. It should be replaced by a TB4 Java JUnit test.

This is executed through https://github.com/vaadin/vaadin/blob/7.7/uitest/integration_tests.xml#L244, which should be updated to use the new unit test

Note that this issue is not related to "integration-test-liferay6-theme", which is currently also broken

**Comment by hesara** [comment]
Possibly can use https://dev.vaadin.com/review/#/c/3332/ as a starting point

**Comment by pleku** [comment]
SHOULD HAVE, but not necessary for FW8.
