### ISSUE TITLE
Required field indicator not showing for text fields

### ISSUE THREAD

**Issue by aspan** [vaadin/framework8-issues#277]
Shouldn't AbstractTextFieldConnector extend AbstractFieldConnector instead of AbstractComponentConnector?

**Comment by aspan** [comment]
Affects vaadin 8.0.0.alpha2

**Comment by jdahlstrom** [comment]
Thank you for the report! It should indeed.

**Comment by Artur-** [comment]
https://dev.vaadin.com/review/14425
