### ISSUE TITLE
Use FlexibleOptionGroup in Sampler

### ISSUE THREAD

**Issue by pleku** [vaadin/framework8-issues#282]
The add-on FlexibleOptionGroup has is used but been disabled in Sampler, it should be enabled again once it has been converted to Vaadin 8.

https://dev.vaadin.com/review/gitweb?p=sampler.git;a=blob;f=sampler-core-samples/src/main/java/com/vaadin/demo/sampler/features/layouts/LayoutSampleUtil.java

https://dev.vaadin.com/review/gitweb?p=sampler.git;a=blob;f=sampler-web/src/main/resources/com/vaadin/demo/sampler/AppWidgetset.gwt.xml
AND
sampler-core-samples/src/main/resources/com/vaadin/demo/sampler/features/CoreSamplesWidgetset.gwt.xml

Also enable dependencies in pom.xml for sampler-web

Might need to convert it to Vaadin 8, should be easy to create a version of it that uses the OptionGroup from Compatibility package.

**Comment by Artur-** [comment]
Moved to sampler issues
