### ISSUE TITLE
Use AceEditor in Sampler

### ISSUE THREAD

**Issue by pleku** [vaadin/framework8-issues#283]
The add-on AceEditor is used in Sampler for declarative html editor, but has been disabled. It should be enable once AceEditor has a Vaadin 8 version available.

https://dev.vaadin.com/review/#/c/14434/2/sampler-core-samples/src/main/java/com/vaadin/demo/sampler/features/declarative/DeclarativeSample.java

https://dev.vaadin.com/review/gitweb?p=sampler.git;a=blob;f=sampler-web/src/main/resources/com/vaadin/demo/sampler/AppWidgetset.gwt.xml

Also enable dependency in pom.xml for sampler-core

Unsure how big task it should be to convert it.

**Comment by Artur-** [comment]
Moved to sampler issues
