### ISSUE TITLE
Use ExpandableTextArea in Sampler

### ISSUE THREAD

**Issue by pleku** [vaadin/framework8-issues#284]
The add-on ExpandableTextArea is used in Sampler, but has been disabled for now. It should be enable once ExpandableTextArea has a Vaadin 8 version available.

https://dev.vaadin.com/review/gitweb?p=sampler.git;a=blob;f=sampler-web/src/main/java/com/vaadin/demo/sampler/component/ThemeEditor.java

https://dev.vaadin.com/review/gitweb?p=sampler.git;a=blob;f=sampler-web/src/main/resources/com/vaadin/demo/sampler/AppWidgetset.gwt.xml

Also enable dependency in pom.xml for sampler-web

Should not be a big task to create a Vaadin 8 version of the add-on which extends the TextArea in compatibility package.

**Comment by Artur-** [comment]
Moved to sampler issues
