### ISSUE TITLE
CheckBoxGroup is empty when it's disabled and doesn't become non-empty after enabling

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/framework8-issues#286]
Use the following test UI:

```
public class CheckBoxGroupDisabled extends AbstractTestUI {

    @Override
    protected void setup(VaadinRequest request) {
        CheckBoxGroup<String> group = new CheckBoxGroup<>();
        group.setItemCaptionProvider(item -> item);
        group.setDataSource(DataSource.create(Arrays.asList("a", "b")));
        group.setEnabled(false);
        addComponent(group);

        Button button = new Button("Enable", event -> group.setEnabled(true));
        addComponent(button);
    }

}

```
- The first issue: group is "not visible" when it's disabled. Is it correct ?
- The second issue: it's still empty after enabling it using the button. This is definitely a bug.

**Comment by elmot** [comment]
RadioButtonGroup should be tested fot the issue

**Comment by denis-anisimov** [comment]
RadioButtonGroup has the same issue.
This is generic issue with disabled component and DataSource.

**Comment by denis-anisimov** [comment]
Uint tests: https://dev.vaadin.com/review/14454
Use the patch as a base for the fix.

**Comment by pleku** [comment]
Fix should be applied only to the initial state or when the DataProvider is changed.

Test all the listings, not just CBG and RBG

**Comment by denis-anisimov** [comment]
I don't know how to do it in a reasonable way with current approach without touching disabled connectors communication.
Here are the short explanation how it works at the moment and reason why I don't see how to do it:

The logic is spread out between client side and server side. That's the main problem. Server side tries to send something to the client but client decides what to do with this data.

What happens initially:
- DataCommunicator server side class contains variable `pushRows` which is a range of data that should be sent to the client.
- It's initially set to 0..40.
- This range of data is used to send rows from the server to the client inside `beforeClientResponse`. 
- So not all data is sent to the client initially (if e.g. the size of data is more than 40 then everything whose index is over 40 won't be sent).
- `pushRows` is emptied after the chunk of data is sent.
- The client side `DataCommunicatorConnector` class delegates its call `setData` to the `AbstractRemoteDataSource.setRowData` method.
- This method is written in a way that it totally ignores the fist data which is sent (because of initial state : `requestedAvailability` range is empty). That can be fixed. But it doesn't fix the issue of insufficient data.
- Then internal magic happens ( which depends on DataSource nature. There are several implementations of DataSource. Default one uses default `addDataChangeHandler` method implementation which uses `SimpleDataChangeHandler` . This class is for widgets that don't support lazy loading. But it will be different for other DataSource and Grid uses different implementation). The result of this magic: client knows (because server said it to it before sending data) about whole data size. But only some chunk of data has been sent (e.g. 40 items). Client requests more data. The way how it's done depends on a widget. E.g. not lazy loading widgets like `CheckBoxGroup` uses `SimpleDataChangeHandler` which requests all data from the server until it gets all required data (and it sets this data once it gets it as a whole, see below). Lazy loading widgets decide on their own how much data should be requested additionally from the server.
- Not lazy loading widgets (like `CheckBoxGroup`) uses `SimpleDataChangeHandler` which has the method `dataAvailable` (called by `AbstractRemoteDataSource.setRowData`) whose implementation doesn't set any data to the widget until its completely fetched from the server. This method schedules a task which fetches data from the server (chunk by chunk) if data is not complete. (*)

Now what could be done but it doesn't work:
- As I said : the client totally ignores the initial chink of data and request it from the server one more time. This can be fixed.
- But this is still just an initial chunk of data (not more than 40).
- Then the client requests more data and since the server doesn't accept requests from disabled connectors it doesn't send more data.
- Since  `pushRows` is emptied after the first request any subsequent `setDataSource` call doesn't do anything at all: `pushRows` is supposed to be updated by the client all the time but it's not  updated for disabled connector.
- What can be done: reset `pushRows` to some number of rows (e.g. as initially to 40).
- BUT IT'S AGAIN HARDCODED number. It can be not enough.
- Technically server should send at least 40 items to the client which should be shown (everything else is expected to not be shown). But even this doesn't happen. See (*) above. If the whole number of items is more than sent rows (hardcoded 40) then `SimpleDataChangeHandler` doesn't update a widget (doesn't call a consumer which is supposed to update a widget). It sends instead request to the server to get all data.
- `SimpleDataChangeHandler` can be fixed to update widget immediately with a chunk of data. But it still won't be able to request remaining data. But at least 40 items will be shown.
- Lazy loading widgets has a different logic and they calculate required items number based on their own size/sate, etc...

As a result: 
- Server DOESN'T know how many items should be sent to the client.
- It's the client who decides how many items required. The whole logic about size is now on the client side. Server doesn't know anything about it by design. There is a hardcoded number of rows for initial request: 40. But it's not possible to rely on this size since any number above 40 (or any other hardcoded value) will be incorrect.
- Two ways of solving this : 
  - Send the whole data explicitly  (don't use hardcoded 40, but rather send the while data size based on data source). This will work but totally eliminates Lazy loading feature.
  - Move some logic from the client side to the server side: e.g. whether the component is lazy loading or not. This will allow to send whole date from the server to the client for not lazy loading widgets (as a result : there is no any need in `SimpleDataChangeHandler` and a whole magic related to different ways of handling DataSource: it's known whether it's lazy or not from the very beginning and for not lazy loading widgets everything will be done on the server side).
  - But there is still a question: what to do with lazy loading widgets when they are disabled ? They still need the way of requesting additional data from the server but they won't be able to do that because of disabled connector. So for lazy loading components there still should be some hardcoded initial number of rows to send but again: what to do if it's not enough ?

So we can solve it for not lazy loading components (it will require a lot of changes: different design and removal unneeded parts of logic from client side). But I still don't see a way to do it for lazy loading widgets (like Grid).

The simplest way to solve: return back to the question about possibility to handle disabled connectors. This won't require any change in current design (though the implementation design is very misty and once should just know how it works or spend a lot of time on understanding). It will require only one localized thing which is not related to anything except communication.

So the question is : what to do ?

**Comment by pleku** [comment]
If the hardcoded number would be configurable, then at least the developer can decide on how many items to send initially, e.g. if 40 is not enough, send 100.

While it again looks like data requests from disabled components might make sense, I think one reason why we discarded it for now was that 40 should be enough, as disabled widgets (Grid) don't allow scrolling.

**Comment by denis-anisimov** [comment]
Hmm,
what if I'm trying to set more than 40, 100 ?

So that was the initial suggestion: use hardcoded number to send those rows ? And ignore those ones that are above of this hardcoded number ?

Looks like a very dirty hack for me which doesn't solve an issue at all but if that's the decision ...

**Comment by pleku** [comment]
A hardcoded number that is configurable by the app developer, and fix client ignoring the initial chunk of data. This is _the least_ we should do for this IMO.

Another option would be to do a proper fix, make it possible for disabled components to request data with enabling rpc calls from those (the separate ticket).

**Comment by denis-anisimov** [comment]
Well, OK.

**Comment by pleku** [comment]
Probably might make more sense to fix it for good just straight out, instead of discussing about what we should do. Might even save ours and the users time in the longer run.

**Comment by denis-anisimov** [comment]
https://dev.vaadin.com/review/14454

**Comment by denis-anisimov** [comment]
It still doesn't fix the Grid and it can't fix it.
There is InitiallyDisabledGrid test UI with InitiallyDisabledGridTest. Its method `worksWhenEnabled` is disabled for now (ignored) because of this issue.
Server side Grid sends 40 rows to the client side which are shown. 
But when a Grid becomes enabled scrolling doesn't show up remaining rows.
I don't know the details of client side Grid impl but what I assume is :
Grid gets some number of rows and it knows which number it wants to have in its cache DEPENDING on its size ( to be able to show all of them and have some window in advance).
And it requests more rows right away with the size that is used in the test.
It fails to fetch this additional data and becomes in unsync state.
When it becomes enabled it doesn't work anymore.

Such behavior is confirmed by setting `getDataCommunicator().setMinPushSize(70);`.
In this case Grid has enough data for its window and doesn't send more requests to the server when it's disabled.
When it become enabled it requests more data on demand (scrolling).

And any hardcoded number won't work here: since client side grid calculate window size based on its actual visual size (which is not known on the server side).
So it can work theoretically with 40 rows even (if a Grid is small) and it won't work with 100 rows if a Grid is very big.
