### ISSUE TITLE
It is not possible to edit twice the same row in the Spring CRUD demo

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/framework8-issues#287]
- Use Spring archetype CRUD demo application.
- Select a row.
- Edit it.
- Save it.
- Deselect and select it again.
- Edit and try to save.

Result: error message appears.

The reason is:
Grid uses Person instances as a data. But once Person is updated in the DB the previous instance becomes "outdated". Its "serial" field "version" is increased by JPA provider and new Product instance should be used for next update operation. So the current Person instance becomes outdated .
But this instance is still in the Grid.
As a  result the second edit tries to save outdated instance and it fails.
Grid should somehow be updated with new Product instance which is the result of `dataService.updateProduct(product);` inside CommitHanlderImpl.

And that's the issue with current API : there is no simple way to do it. API allows to refresh only an existing instance with data inside it but it doesn't allow to refresh this instance with another one .
There is a way to refresh everything (a whole DataSource) via removing old one and inserting new one, then `refreshAll` but this is ugly.

**Comment by Legioth** [comment]
Teemu was also having some similar issues.

I believe that the best way of solving this would be introduce the `DataSource.refresh` method that is described in BoV but not implemented (and I couldn't find any ticket for it). It should be used to make DataSource and by extension also Grid aware that the row has changed and that a new version should be shown. Whenever this happens, references to the old instance should be cleared in favor of a fresh instance from the DataSource.

**Comment by Artur-** [comment]
#77

**Comment by denis-anisimov** [comment]
Should we close this one and replace it with #77 ?

**Comment by denis-anisimov** [comment]
Well, actually not.
This one is about Spring CRUD demo. 
#77 is API to fix it in the demo.

**Comment by denis-anisimov** [comment]
Blocked by #77.

**Comment by Legioth** [comment]
Wouldn't proper use of JPA in an asynchronous context like Vaadin Framework mean that you should always do `EntityManager.refresh(bean)` when the user starts editing the bean?

**Comment by denis-anisimov** [comment]
See Spring CRUD demo.
There is no any references to EntityManager. It's just hidden in the services abstraction, repository abstraction.
Should user introduce refresh method in those abstraction layers just because it's a restriction in the framework ?
What if backend is given to you with those abstractions and you are not able to modify ?
What if I don't even use JPA at all but it's convenient for me to use immutable classes in the DataSource and I don't want to make them mutable just because of FW restriction. And it's preferable to replace one instance by another one rather than "refresh" (and the instance even might be a subclass of the original class).

**Comment by Artur-** [comment]
Depends on #339

**Comment by pleku** [comment]
SHOULD HAVE, but not necessary for FW8.

**Comment by Artur-** [comment]
How can a fundamental flaw in an example be SHOULD?

**Comment by pleku** [comment]
Might be that this is fixed by someone anyway, but unless this is a marketing demo, who cares that it is a SHOULD instead of a MUST ?

**Comment by Legioth** [comment]
#77 that should fix the actual issue is still in scope, so it might actually make sense to also quickly update the demo once the underlying issue has been fixed.

**Comment by pleku** [comment]
Closing since #77 has been unscoped as SHOULD for beta for now.

**Comment by Legioth** [comment]
Was this fixed by https://github.com/vaadin/framework/issues/8271, or is there still something that needs to be done?

**Comment by denis-anisimov** [comment]
The way to fix is provided in the FW.
But the way should be applied to the example.
I don't think it works out of the box.

Should be checked at least.
