### ISSUE TITLE
Improve AbstractStringToNumberConverter

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/framework8-issues#288]
`getErrorMessage()` method doesn't have a value to convert as an argument.
As a result only static error message may be used to report a user about failure. And this message cannot contain the value which is incorrect.

Two improvements can be made:
- AbstractStringToNumberConverter CTOR should accept parameterized error message e.g. "Could not convert vlaue to '{}' Integer" (like AbstractValidator does).
- In case user wants to have a complete control over the error message the method `getErrorMessage()` should have a parameter which is the converted value.

**Comment by jdahlstrom** [comment]
AbstractValidator internally uses an "error provider" T->String, might be reasonable to change APIs to take those instead of strings with special format. OTOH the latter is somewhat more convenient to write.

**Comment by pleku** [comment]
COULD HAVE, but not necessary for FW8.
