### ISSUE TITLE
Null handling for HasValue and Binder

### ISSUE THREAD

**Issue by jdahlstrom** [vaadin/framework8-issues#295]
**See last(ish) comment about design**

There should be a general way to specify what to do with nulls coming from the backend, with some reasonable defaults for most common use cases. With single selection, null currently means empty selection. #290 proposes that null value bound to a multiselection should work and denote an empty selection. For text fields nulls should be represented by an empty string. Whether there should be a reverse mapping back to null seems to be vary from case to case.

**Comment by Legioth** [comment]
There are two basic cases to consider here:
1) It might be useful to convert `null` values originating from the business layer into something more meaningful for the currently used field.
2) It might be useful to convert empty field values (e.g. `""` from a `TextField` or the empty set from a `CheckBoxGroup`) to `null` before being passed to the business layer.

The next question is whether this should somehow be the done automatically by `Binder`, whether there should be helper API for it or whether it's completely on the application developer's responsibility to provide whatever converter would be suitable in any particular case.

**Comment by denis-anisimov** [comment]
Abandoned patch for Select component: https://dev.vaadin.com/review/#/c/14443/
Original issue is #290.

**Comment by jdahlstrom** [comment]
If converters (and validators) in general are expected to pass nulls around unchanged, both cases are easy to handle with an appropriate converter set as the first (closest to the field) converter of the binding. A helper "null converter" could be provided that takes a `Predicate<FIELDVALUE>` and a `Supplier<FIELDVALUE>`, the first determining whether a given value should be passed to the model as null, the second providing a representation for a null value coming from the model.

**Comment by Legioth** [comment]
One might also argue that the "null converter" should be last (closest to the bean) since null values might just as well originate from that direction. The most flexible option would probably be to let it be in any part of the chain, e.g. `Binder.withNullConverter` that is just a shorthand for the regular `Binder.withConverter` method.

In addition to the proposed Predicate + Supplier, I also see value for a shorthand that uses static values instead of callbacks since most cases are probably of a static nature.

**Comment by pleku** [comment]
**Resolution after design meeting**
HasValue:
- `default T getEmptyValue() { return null; }`
- `default boolean isEmpty() { return Objects.equals(getValue(), getEmptyValue()); }`

All `HasValue` implementations should return _a sensible value_, e.g. for `TextField` should return `""`

Binder:
- There is default automatic conversion from null -> HasValue<T> : getEmptyValue : T. Doesn't not convert back from empty value to null. NOTE: not a converter, just coversion
- `binder.forField(field).withNullRepresentation(T nullRepresentation)` adds converter that converts `null` -> nullRepresentation -> `null`
- Adding any converter will disable the default automatic conversion, but can be used together with `withNullRepresentation(T)` **Split out to #404**

**Comment by denis-anisimov** [comment]
https://dev.vaadin.com/review/#/c/14609/
