### ISSUE TITLE
Move all themes except Valo into a new compatibility-themes package

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#298]
Copy paste old themes module to a new module, remove unnecessary stuff from both modules. All Java references to themes should be updated and moved to corresponding modules, e.g. Reindeer theme constants to vaadin-compatibility-server.

**Comment by Artur-** [comment]
Depends on #365

**Comment by Artur-** [comment]
Ensure that the new module is included in the `all` module also

**Comment by pleku** [comment]
@Legioth please clarify should this be closed now or not, as part of the new "DoDo" ?
