### ISSUE TITLE
Integrate japicmp into the build

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework8-issues#299]
Produce a build configuration which provides a similar API diff as for 7.7 but using japicmp

**Comment by Artur-** [comment]
http://r2d2/viewType.html?buildTypeId=Vaadin80_APIDiff

**Comment by denis-anisimov** [comment]
Japicmp is added into POM as a part of inactive profile:
https://dev.vaadin.com/review/14552

**Comment by denis-anisimov** [comment]
https://dev.vaadin.com/review/14561

**Comment by denis-anisimov** [comment]
https://dev.vaadin.com/review/14556
