### ISSUE TITLE
Issues with ItemCaptionProvider

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/framework8-issues#300]
RadioButtonGroup:

```
addDataGenerator(new DataGenerator<T>() {
            @Override
            public void generateData(T data, JsonObject jsonObject) {
                jsonObject.put(RadioButtonGroupConstants.JSONKEY_ITEM_VALUE,
                        itemCaptionProvider.apply(data));
```

itemCaptionProvider should be accessed using getter since it's overridable.

And there should be a check against null value returned by caption provider with an appropriate error message.
At the moment there is NPE with cryptic stacktrace.

**Comment by denis-anisimov** [comment]
Check the same for CheckBoxGroup.

**Comment by ahie** [comment]
https://dev.vaadin.com/review/#/c/14507/
