### ISSUE TITLE
Rename DataSource apply to fetch and write javadoc

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/framework8-issues#307]
```
DataSource<T>
        extends Function<Query, Stream<T>>
```

`apply` method should be overriden and have javadoc explaining what it does.

**Comment by Legioth** [comment]
As discussed in #264, `DataSource` is not really a pure `Function`. This means that the super type should be removed and the method should instead have a name that explains what what it does, i.e. `fetch`.

**Comment by pleku** [comment]
Verify that documentation has no references to this method, update if are.

**Comment by denis-anisimov** [comment]
https://dev.vaadin.com/review/#/c/14519/
