### ISSUE TITLE
Research how to create a good Maven based workflow for sass compilation

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#310]
Probably want to use 
https://github.com/warmuuh/libsass-maven-plugin

**Comment by Artur-** [comment]
https://dev.vaadin.com/review/#/c/13527 contains code for using the ruby sass compiler in the framework project

**Comment by pleku** [comment]
Needs to support old workflow and recompile to CSS on changes and refresh.
Needs to be able to find sass files inside the classpath, e.g. jar files. Talk to Marlon, who has prototyped this at some point.

Result should be a github project which uses this.

**Comment by johndevs** [comment]
@Artur- 

The Vaadin Designer will need to do the exact same thing as the archetype does, with the difference that it should work for every project, not only Maven. 

To get this working properly could this code be distributed with the framework (extraction of themes, running the compiler, etc) in a similar way that currently the widgetset compiler is distributed? It would mean we would get a similar behaviour in both products without duplicate effort.

**Comment by Artur-** [comment]
@johndevs The idea here is completely the opposite. We do not want to distribute a tool to unzip jar files with the framework, nor do we want to bundle a sass compiler or a way to run a sass compiler. There are generic plugins in Maven which handle these tasks much better and are much more flexible than something we would hack together.

**Comment by pleku** [comment]
@johndevs for your (Vaadin Designer) use case you should maybe look at building a solution based on
1. https://github.com/cathive/sass-java for triggering sass compilation from java
2. anything that watches over file changes somewhere
3. https://github.com/ronmamo/reflections for scanning classpath (jars) for .scss resources to compile

**Comment by pleku** [comment]
https://github.com/pleku/vaadin-libsass

**Comment by johndevs** [comment]
@Artur- Basically that will mean we will have to duplicate the work that has been done here. It is also fine, but would have been nice with a headsup about this.

@pleku Thanks for the pointers, we'll see if we can make use of them in the Designer. 

Also, if you guys needs hints on unpacking the themes and making it work, the Gradle plugin already has this functionality and you might be able to re-use some parts of it.. maybe :) The meat of it is found in https://github.com/johndevs/gradle-vaadin-plugin/blob/master/src/main/groovy/fi/jasoft/plugin/tasks/CompileThemeTask.groovy
