### ISSUE TITLE
Update demo/archetype validation server to latest Wildfly 10

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#312]
7.7 release build has random failures in archetype and demo deployment (War result/demos/sampler.war failed to deploy: ('Connection aborted.', error(104, 'Connection reset by peer'))

These need to be resolved so that intermittent failures do not prevent a release

**Comment by Artur-** [comment]
Let's start by updating to latest Wildfly 10 and see if it resolves the problem

**Comment by Artur-** [comment]
If this does not resolve the problem, create a new issue about remaining problems

**Comment by pleku** [comment]
Wildfly updated. Results still pending the alpha 4 build.

**Comment by pleku** [comment]
Wildfly is accepting demos for in the build (for now).
