### ISSUE TITLE
Define a workflow for migrating issues from Vaadin 7

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#313]
Start migrating and take notes on how it works, should produce a Migration Checklist that can be referenced as a starting point for all future migrations.
- Component changes go into `compatibility-(server|client|shared)`
- Data binding and all other compatibility related fixes go into `compatibility-(server|client|shared)`
- Relevant component changes are ALSO merged into `vaadin-(server|client|shared)`

**Comment by denis-anisimov** [comment]
- Define a list of changes in git.
  E.g. for 7.7.1- 7.7.3 you can use `git log 7.7.0..7.7.3`
- Go through all of them one by one and see the changes.
- To be able to see changes in a more suitable view you can use URL `https://github.com/vaadin/vaadin/commit/$commit_hash$`
- Analyze the commit
  - Server side changes might go into one place only (If they have not been migrated to compatibility module then it's the same class most likely (not always) If the code has been migrated to compatibility then it's compatibility module. Think does the change make sense for the modern component code (most likely not) and migrate it there if it does.
  - Client side/shared changes are like server side changes: there are changes in common classes, classes  that have not been migrated (previous ones are part of this group) and changes in classes that have been migrated. Use the same pattern as for server side classes. For the client side classes change should be applied to both modules: main and compatibility in most cases (opposite to the server side  where this is usually one one place).
  - If a class has not been migrated at all then it might be that master already contains the change and there is no need to do anything.
  - Each change contains most likely a test (plus UI class in case of ui test). Depending on changes which have been made into the codebase do the following: 
    - For a plain JUnit test put the test into the correct package (compatibility if change goes into compatibility).
    - Make a copy in the main module (vaadin-server) if it has been affected as well (test code might require update).
    - For UI test put it to the uitest module. Use .v7 packages for migrated to V7 components.
    - Make a copy of the test (as is) if it's relevant for V8 components as well.
    - Modify the test UI (and accompanied junit test) if needed if there are API changes (it might be you actually need to rewrite the code completely actionwise but keeping the idea of the tested feature).
- Update release notes and similar changes are not applicable at all.
- Sometimes POMs, .gwt.xml (documentation) files should be updated. It might be that there is nothing to do: they are already there. Most likely it's just only about one POM/.gwt.xml file (parent). So no need to care about other files. But keep in mind that there is Vaadin7WidgetSet.gwt.xml and POM files in compatibility modules. No "duplicated" Documentation files.
- Update version changes are not applicable at all.
- [Optional?] Consider to add Git commit comment for each change in the form : `commit XYZ - description (might be as is from the corresponding git commit message), Description of what has been done (V7 or both, what changes to the original commit)`.

**Comment by denis-anisimov** [comment]
The same is available here : https://drive.google.com/open?id=1bxfnN4_ZVi0K-ciextSG7j3L_eAvSF_Mx_azd01zAV4
