### ISSUE TITLE
TwinColSelect should support adding new items regardless of data source

### ISSUE THREAD

**Issue by pleku** [vaadin/framework8-issues#315]
Currently TwinColSelect cannot add new items directly into data source if the DS is anything else than ListDataSource. And even then it will have to reset all items.

Should be fixed, one option would be to require a handler for added new items, instead of just adding them to the data source.

**Comment by pleku** [comment]
Blocked by #77, also need a bit design on how to handle the "conversion" when data source data type is different from string. E.g. probably a new item added handler ?

**Comment by hesara** [comment]
IMO the new TwinColSelect definitely should NOT have the old "New items allowed" feature at all. The only listing component for which it is appropriate is ComboBox.

**Comment by Artur-** [comment]
+1 to removing "new items allowed" for components which do not have a text input by default

**Comment by pleku** [comment]
That would be awesome. So would be removed from ListSelect too (#68).
@Legioth can we close this ?

**Comment by Legioth** [comment]
Please also remove from ListSelect if it's already implemented there.
