### ISSUE TITLE
Release alpha3

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework8-issues#316]
Release checklist: https://docs.google.com/spreadsheets/d/1WzJC10c9XhhNUTpmqPLzka0xtJzvcFQOwCCKJ0i0Z4s/edit#gid=2123246184

**Comment by Artur-** [comment]
Let's release an alpha weekly without separate issues all the time

**Comment by denis-anisimov** [comment]
> You do not have permissions to create build configurations in this project

Apparently this task cannot be done by an arbitrary team member.

**Comment by Legioth** [comment]
> Apparently this task cannot be done by an arbitrary team member.

What part of the release process caused that message?

**Comment by denis-anisimov** [comment]
For me personally: (almost?) any step related to r2d2.devnet.vaadin.com.
So effectively starting from the second step : 

Update vaadin.plugin.version parameter in top-level project
http://r2d2.devnet.vaadin.com/admin/editProject.html?projectId=Vaadin80&tab=projectParams
