### ISSUE TITLE
Confirmation message support for Binder

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#32]
```
binder.forField(emailField)
  .withValidator(new EmailValidator(
    "This doesn't look like a valid email address"))
  .withConfirmationMessage(
    email -> email + " looks like a valid email address");
  .bind(Person::getEmail, Person::setEmail);
```

The default handler shows confirmation messages in a status label, if set. It is not set as a "component error". IF there is a custom handler, then it can decide what to do with the message.

**Comment by pleku** [comment]
SHOULD HAVE, but not necessary for FW8.

**Comment by pleku** [comment]
Issue moved to [vaadin/framework #8387](https://github.com/vaadin/framework/issues/8387) via [**ZenHub**](https://www.zenhub.com/)
