### ISSUE TITLE
Automatically test archetype-application-example using Java 9

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#321]
Java 9 compatibility should be tested as part of the framework build (not validation but full build)

**Comment by pleku** [comment]
COULD HAVE, but not necessary for FW8.

**Comment by Legioth** [comment]
Actually a MUST HAVE to quickly test this, but fixing anything that turns out to be broken is out of scope for now.

**Comment by pleku** [comment]
Should be done as a part of #330 , or after it, or at least taken into consideration when implementing it.

**Comment by pleku** [comment]
There is a separate ticket for manual testing this with all the archetypes #410, so still a COULD for FW8
