### ISSUE TITLE
Make all new components use the old testbench tests

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework8-issues#325]
Anything that worked through the browser in Framework 7 should also be verified to work through the browser with the non-legacy components in Framework 8.

To achieve this, all test UIs should be updated to use non-compatibility components. Some tests also need to be moved out from `v7` packages to where there were temporarily moved to be out of the way.

Related to #406

Will require splitting per test packages or components, and should be split into several issues.

**Comment by denis-anisimov** [comment]
#582 - SQLContainer tests cleanup
#585 - Form related tests 
#584 - DateField related tests
#583 - Calendar tests
#586 - Grid UI tests (part 1).
#588 - Grid UI tests (part 2).
#589 - Grid UI tests (part 3).
#592 - Grid UI tests (part 4).
#8373 - Grid UI tests (part 5).
#8419 - Grid UI tests (part 6).
#8436 -Grid UI tests (part 7).
