### ISSUE TITLE
Add DesignAttributeHandler from Vaadin 7 to compaitibility-server

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#326]
Component with custom declarative support can more easily be migrated if this helper class is available in `com.vaadin.v7`

**Comment by Legioth** [comment]
Not clear what exactly is the problem. One thing that was discovered when migrating was that `DesignFormatter`, which is accessed through `DesignAttributeHandler`, uses the new `Converter` instead of the old one.

**Comment by Artur-** [comment]
The problem was not actually the described one and there is no need to add DAH to the compatibility package. Both compatibility and new declarative format files can be read and parsed using the one and only Design/declarative implementation and new style converters
