### ISSUE TITLE
Deploy master documentation to vaadin.com/docs

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#327]
The documentation from the master branch should be available vaadin.com/docs as "Framework 8.0" documentation

**Comment by Artur-** [comment]
Handled by the docs team

**Comment by pleku** [comment]
DoDo: Both "Book of Vaadin 7" and "Book of Vaadin 8" deployed at  vaadin.com/docs

**Comment by hesara** [comment]
Now deployed to https://vaadin.com/docs8/ .
