### ISSUE TITLE
Test that cross field validation works as expected

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#33]
```
PopupDateField departing = new PopupDateField("Departing");
PopupDateField returning = new PopupDateField("Returning");

// Store return date binding so we can revalidate it later
FieldBinding<Trip, LocalDate> returnBinding = binder
  .forField(returning)
  .withValidator(
    returnDate -> !returnDate.isBefore(departing.getValue()),
    "Cannot return before departing")
  .bind(Trip::getReturnDate, Trip::setReturnDate);

// Revalidate return date when departure date changes
departing.onChange(newValue -> returnBinding.validate());
```

**Comment by denis-anisimov** [comment]
There is no `onChange()` method for AbstractTextField/AbstractComponent.

Also there is no public `validate()` method in Binding. This one is added (just changed visibility).

What to do with `onChange()`?
At the moment the test uses `addValueChangeListener()`.
Several options available in that regard:
- Update docs accordingly (they still have to be updated, example is incorrect).
- Add method `onChange`. Q: how should it work , where  it should be added ?

**Comment by jdahlstrom** [comment]
onChange is #106. No need to add it now, just use addVCL

**Comment by denis-anisimov** [comment]
OK, good. Thanks.

**Comment by denis-anisimov** [comment]
https://dev.vaadin.com/review/#/c/14113/
