### ISSUE TITLE
Design selection models

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#331]

**Comment by pleku** [comment]
This has quite big effects, is blocking #232 which is a bigger issues, and effecting other components too, should design should be resolved rather soonish.

**Comment by pleku** [comment]
Plan for fixing SelectionModels:
- Remove SelectionModel(s) from client side, only used by Grid currently #421 
- Remove SelectionModel API (getter) from Listing & AbstractListing #424
  - Only public SelectionModel API should be visible in Grid
- interface SingleSelect<T> extends Listing<T>, HasValue<T> #422
- interface MultiSelect<T> extends Listing<Set<T>>, HasValue<Set<T>> #423
  - MultiSelect should have addSelectionChangeListener for listening to SelectionEvent which extends ValueChangeEvent for better API
- Add AbstractSingleSelect & AbstractMultiSelect which extends AbstractListing and implements corresponding interfaces (couple lines up) for the existing Selection components, except Grid...
- Grid is not HasValue but can be used in binder with:
  - grid.asMultiSelect : MultiSelect<T> #232 
  - grid.asSingleSelect : SingleSelect<T> #425

**Comment by pleku** [comment]
Split into sub tickets for implementation.
