### ISSUE TITLE
Implement focus and blur events for CheckBoxGroup

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#334]
OptionGroup in 7.7 implements FocusNotifier, CheckBoxGroup should do the same

There should not be any focus events fired when focus changes between the options. Events are fired only when the focus/blur moves to/from another component. This logic should be extracted to be reusable. The old V7 optiongroup had this, but do not copy from there.

**Comment by denis-anisimov** [comment]
https://dev.vaadin.com/review/14666
