### ISSUE TITLE
Generate an id for each Grid column

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#337]
To be consistent whether you are using a bean or not and to be able to mix bean property columns with custom columns, each column should have a `String` id. The id is automatically generated when a column is created or later set using `Column.setId`.

Note that this id is only for the user and not to be used internally for identifying the column!

```
Column getColumn(String id)
```

returns a Column for the given id.

Visible columns can be set using

```
setColumns(String... columns)
```

`setColumns` is not really useful together with `Column` objects. Either you have created the columns already in the correct order and `setColumns` is not needed, or you are e.g. restoring the order from something stored in the database for the user and cannot identify the columns by instances.

The following methods accept either a `Column` object or a `String` id.

```
removeColumn(Column column);
removeColumn(String columnId);
sort(Column column)
sort(String columnId)
sort(Column column, SortDirection direction)
sort(String columnId, SortDirection direction)
StaticRow.join(Column... columns)
StaticRow.join(String... columns)
```

Generated column ids are in the form `generated_[running number]`

**Comment by jdahlstrom** [comment]
So there's already `Column.setId`, `Column.getId`, `Grid.getColumn(String id)`. These relate to the ids used in communication (and maybe other bookkeeping?) and are assigned from a KeyMapper. 

Then the columns have connector ids (because columns are extensions these days) that apparently can't used to keep track of the columns because they're only assigned on attach (but surely you don't need communication keys until attach anyway? Might warrant investigating.) 

And then there should be this third type of id used as handles in user-facing API. Could this mess be simplified somehow?

**Comment by Artur-** [comment]
The public methods should be changed to use this user facing id. If an internal id is needed for communication (in addition to connector ids), then so be it.

**Comment by tsuoanttila** [comment]
If we make the users provide an ID for the column, we can then start using connector ids for communication and mostly forget the "internal communication id" in use now. Just make sure that the communicational parts don't happen while columns do not have connector ids

**Comment by jdahlstrom** [comment]
The user-handle should still be autogenerated unless explicitly set or implicitly mapped from a source of some sort.

**Comment by jdahlstrom** [comment]
(BTW, how long until we realize it would be cool if the data source also optionally had some sort of a concept of "columns" or "properties"...)

**Comment by Legioth** [comment]
> BTW, how long until we realize it would be cool if the data source also optionally had some sort of a concept of "columns" or "properties"...

Realized that ages ago, but at the same time also realized that it would make it significantly more messy to implement data sources.
