### ISSUE TITLE
Allow overriding entity identification in data sources

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#339]
Design doc: https://docs.google.com/document/d/17WksIcZXDL77b1Y5eTKnR-avvRD2n8She_KQjHgtTZI/edit

```
interface DataSource<T> {
  // Return type is not parameterized since it's not needed anywhere else
  // Never returns null
  default Object getIdentifier(T item) { return item; }
}

// Most "simple" data sources provide an API for customizing this
MyDataSource<Person> persons = ...;
persons.setIdentifier(Person::getEmail); // Function<T, Object>

// Advanced data sources are covered by another issue
```

The rest of the features from the design document are currently categorised as "nice to have, but not a priority before 8.0 unless more evidence is presented"

**Comment by pleku** [comment]
SHOULD HAVE, but not necessary for FW8.

**Comment by pleku** [comment]
Fixed by https://github.com/vaadin/framework/commit/294ca0a2f5c29b65f9c4dc5887bfa0abc1cb7c7f
