### ISSUE TITLE
Support filtering backend data sources

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#340]
Using `BackEndDataSource.filteredBy(BackEndFilter filter)` you can specify a filter for the data source. This returns a new `DataSource` which is based on the original data source but includes the filtering info.

```
DataSource<Person> dataSource = ...

grid.setDataSource(dataSource
  .filteredBy(new NamePrefixFilter("Ge"))
  .sortedBy(new SortOrder(
    "yearOfBirth", SortDirection.ASCENDING)));

comboBox.setDataSource(dataSource
  .sortedBy(new SortOrder(
    "name", SortOrder.DESCENDING)));
```

**Comment by Legioth** [comment]
One open question is how combine multiple filters originating either from multiple `filteredBy` invocations or from the user through a component such as `ComboBox`

**Comment by elmot** [comment]
Update TodoMVC afterwards.

**Comment by pleku** [comment]
Spend MAX half a day on coming up with a low level DataProvider/Query API design for covering filtering with the following backends:
- List<T>
- SQL
- API (e.g. Spring Data)
  Please take into note Per-Åke's patch for making Query more generic https://dev.vaadin.com/review/#/c/14645/4

**Comment by Legioth** [comment]
Not to forget the four different types of components:
- ComboBox (single filter input, integrated into the component)
- FilterableGrid (multiple filter inputs, integrated into the component)
- AddressBook (single filter input, outside the component)
- Advanced search for (multiple filter inputs, outside the component)

**Comment by heruan** [comment]
Wondering about the progress on this. I can see `BackEndDataProvider` firing requests with `Query` objects carrying limit and offset values, but always an empty set of filters.

**Comment by pleku** [comment]
Hi @heruan , we are pretty close to having final design for Filtering, see #467 for further info. Implementation of this is soon to follow.

**Comment by pleku** [comment]
Design in #467 , which will be split into subtickets for implementation
