### ISSUE TITLE
Implement Binder.isValid

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#344]
`Binder.isValid()` checks the validation status but does not make all validation errors visible in the way that `validate()` does

**Comment by pleku** [comment]
SHOULD HAVE, but not necessary for FW8.

**Comment by pleku** [comment]
Issue moved to [vaadin/framework #8378](https://github.com/vaadin/framework/issues/8378) via [**ZenHub**](https://www.zenhub.com/)

**Comment by pleku** [comment]
In progress with vaadin/framework#8274
