### ISSUE TITLE
Update vaadin-archetype-application to use only Vaadin 8 API

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#347]
- No com.vaadin.v7 API is in use

**Comment by denis-anisimov** [comment]
@Artur- has already updated vaadin versions in all archetype projects in the commit 505da7bd5e2a57f2dd248b50f3ed821885393273.
Apparently source code in the application archetype has not been updated to use v7 compatibility packages.
So everything works as is.
Nothing to do.
