### ISSUE TITLE
Mess with FieldEvents classes

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/framework8-issues#363]
There are two FieldEvents classes: one in the compatibility module and another one in the main.

v7.Grid uses FieldEvents from the main module.
WTH ?

No components in v7 should use FieldEvents which is not in the v7.

Then non-v7 FieldEvents should be gotten rid of removeXXListener() methods in its nested interfaces since it may be considered as a completely new.

**Comment by pleku** [comment]
@Legioth not part of the "new DoDo", please add or close.
