### ISSUE TITLE
Make Valo independent of base

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#365]
At least grid.scss and fonts.scss import stuff from the base theme .These parts should be copied from the `base` theme to `valo` to make `valo` standalone.

````components/_grid.scss:@import "../../base/grid/grid";
fonts/_fonts.scss:  @include v-font(ThemeIcons, "#{$fontawesome-pathPrefix}../base/fonts/themeicons-webfont");
fonts/_fonts.scss:      @include v-font(FontAwesome, "#{$fontawesome-pathPrefix}../base/fonts/fontawesome-webfont");

```
```

**Comment by jdahlstrom** [comment]
It is confusing to maintenance people, though, that Valo doesn't use `base`. Of course it's even more confusing that _some_ parts of it do, but on the other hand copypasta causes another maintenance issue. Perhaps `base` should be renamed to `legacy-theme-base` or something?

**Comment by Artur-** [comment]
base will be in `compatibility-themes`, see #298

**Comment by hesara** [comment]
Also note that valo was originally developed not to be on top of base - the links to base should be few in number and only the relevant parts should be copied, and base will most likely stay unchanged after the move to the compatibility package.
