### ISSUE TITLE
Update Dashboard master to use 8.0.0.alpha2

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/framework8-issues#366]
See #272 for checklist and the details.
It's similar task.

**Comment by Legioth** [comment]
How is this different from #273?

**Comment by denis-anisimov** [comment]
The same. Didn't find it.

**Comment by denis-anisimov** [comment]
Or actually I thought that #273 is about converting to use new V8 components. Not about straightforward migration.......
But yes, it's the same.
