### ISSUE TITLE
Update image files in documentation with new component hierarchy

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/framework8-issues#369]
There are at least two SVG files referring to a component hierarchy: 
- components/original-drawings/component-diagram.svg
- components/original-drawings/field-diagram.svg

May be there are also binary images (at least I see .png files with suffices -lo and -hi).

The component hierarchy is outdated: contains obsolete components and wrong hierarchy.

All such files should be updated.

**Comment by denis-anisimov** [comment]
See also #237.

**Comment by hesara** [comment]
See spreadsheet Framework Team/Documentation/Figures in Book of Vaadin .

**Comment by pleku** [comment]
Closed by https://github.com/vaadin/framework/commit/74342821007c1fa1f99df9c7b3703404c3fc7c08
