### ISSUE TITLE
Vaadin Spring Plugin update for 8

### ISSUE THREAD

**Issue by tsuoanttila** [vaadin/framework8-issues#371]
Currently an API change made in Vaadin 8 makes spring plugin unusable for V8 projects.

This currently blocks building the demo project.

**Comment by Legioth** [comment]
Let's start publishing 2.0 snapshots built against 8.0 in the same way as 1.0 snashots are built today.

To keep the impact low for now, it might be best to do a separate `2.0` branch, even though we are assuming this will eventually be the `master` branch

**Comment by elmot** [comment]
Unfortunately, we have to use vaadin 8.0-SNAPSHOT but not alpha3.
