### ISSUE TITLE
Use archetypes from https://github.com/vaadin/archetypes

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#372]
7.7 and 8.0 builds use https://github.com/vaadin/maven-integration/ where archetypes used to be located in a sub foder. The archetypes are now moved to https://github.com/vaadin/archetypes.

All 7.7 and 8.0 builds need to be updated to use the new location. Note that the archtypes are now in the root repository directory and there is a root pom.xml which can be used to build all the archetypes.

The release checklist needs to be updated, at least about what to tag and where.

´scripts/BuildArchetypes.py` probably needs an update to use the correct repository

As a final step, the archetypes should be deleted from https://github.com/vaadin/maven-integration/. This is done in https://github.com/vaadin/maven-integration/pull/6

**Comment by hesara** [comment]
Updated for Vaadin 8 (master) build configurations and changed a comment in release checklist, no need to update the script as it uses archetypes from an already built Maven repository.

**Comment by hesara** [comment]
Updated 7.7 build configurations

**Comment by hesara** [comment]
Created #426 for archetype testing script, submitted vaadin/maven-integration#6 .
