### ISSUE TITLE
Binder.hasChanges() method has no sense for unbound Binder

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/framework8-issues#375]
Method `setHasChanges` is called only once in a Binder: when method `handleFieldValueChange()` is called in a Binding.
This method is called only when there is a bean instance which binder is bound to.

As a result in case of using methods `load()`/`save()` the method `hasChanges` always returns `false`.
I'm not sure whether this is by design. But it definitely is useless in this case.
And javadoc should mention the unexpected behavior at least.

Similar issue with validation: "automatic" validation is done only when a binder is bound to a bean.
As a result: there is no way to get any event about any status change.
So in case of using `load()`/`save()`  methods user has to call `validate()` methods explicitly.
But the logic may be changed to do it automatically even if there is bound bean instance.

**Comment by denis-anisimov** [comment]
See https://github.com/vaadin/framework8-demo/pull/36.

At the moment it's kind of ugly:
one has to make a copy of Product which is selected on the table to be able to edit it correctly.
Otherwise any change is done directly to the currently selected bean immediately : no need to press any "save" button for that. As a result even without pressing "save" button currently selected product is updated whenever any change happens in the editor. 
They are not visible immediately in the Grid just because some action is required to refresh the Grid.
But next rendering phase will show the changes that have not been saved: e.g. deselect and select a row back.

So the patch uses new Product and copy all properties of currently selected product to the copy. And original product has to be saved somewhere to be able to update it later in the datasource.
Once changes are made (now they don't affect original bean) and "save" is pressed one more time copy is required: to store new values from a copy to the original bean.

Fortunately Spring has BeanUtils class that allows to do it without custom boilerplate code. What to do when we don't use Spring ?

The better way would be to use "load"/"save" methods instead of binding to the copy (or even worse to the original bean).
But as I mentioned: changes in the fields don't update "hasChanges" flag and they don't do automatic validation. It should be done manually. So an unbound Binder is quite useless. But it's preferable in the Spring CRUD demo and similar applications.

**Comment by pleku** [comment]
@Legioth this is not a part of the "new DoDo", please add or close.

**Comment by pleku** [comment]
Prioritized this since it is causing bad Dev UX in example app archetype.

**Comment by denis-anisimov** [comment]
The result of this ticket grooming :

automatic validation (which is a consequence of value change listeners added to fields) should be done for unbound bean in the same way as for bound.
In addition to that the method `setHasChanges` should be called as well when a field is changed.
It will require some tweaking in the BindingImpl logic to distinguish cases when binder is bound and when it's unbound. But this should not be a big issue. Most of the logic will be the same.

There will be unit failed tests that has to be either removed completely (since they test exactly current behavior  when nothing happens if binder is unbound) or corrected.
More new tests will be required.
