### ISSUE TITLE
Fix Broken tests broken after migrating V7 patches

### ISSUE THREAD

**Issue by pleku** [vaadin/framework8-issues#376]
Not necessarily all related to V7 patch migration, but might be that some screenshots were not updated? 

Also widgetset for ValoThemeUI are broken for some reason 
http://r2d2.devnet.vaadin.com/viewLog.html?buildId=144541&buildTypeId=Vaadin80_VaadinTests_ModernBrowsers&tab=artifacts#!1knan6kkqqt0s

**Comment by denis-anisimov** [comment]
Some of those could relate to migration patch.

But there is a number of tests that fails because of absence of component in Default widgetset.
(like NativeSelect). This definitely doesn't have any relation to migration patch.

So each test requires failure analysis.

**Comment by pleku** [comment]
Yeah, might, might not. All I know is that some widgetset related patches were migrated, while at the same time the used widgetset for ValoThemeUI has not changed but yet it is completely broken.

**Comment by denis-anisimov** [comment]
There are many failures because of wrong widgetset for ValoThemeUI test. Some of them will be fixed by https://dev.vaadin.com/review/#/c/14533/ most likely.
Other failures still require investigation.

SplitPanelWithMinimumAndMaximumTest failure: happens only for Chrome40. The reason of the failure: split panel has minimum split position set to 10 percents. But Chrome40 allows to move splitter to relative location x=58.xx. Test expects 0.1*(component width == 600). I'm going to correct the allowed error value .

**Comment by Artur-** [comment]
SplitPanelWithMinimumAndMaximumTest is a problem introduced in some Chrome version (a scrollbar is shown where it should not be if I remember correctly, and this affects the width). The test is ignored for 7.7

**Comment by denis-anisimov** [comment]
OK, thanks.
But how is it ignored ? Muted ? For all browsers ?

**Comment by denis-anisimov** [comment]
Test GridColumnHidingTest is new. It's added during V7 patches migration.
It fails only for FF. For some reason DnD action is not working.

Fixed by https://dev.vaadin.com/review/14537

**Comment by denis-anisimov** [comment]
Fix for ValoThemeUI: https://dev.vaadin.com/review/#/c/14538/
New screenshots with DateField component (LocalDate based) are uploaded and used in the test.

**Comment by denis-anisimov** [comment]
BasicCrudGridEditorRowTest: the reason is most likely is similar to SplitPanelWithMinimumAndMaximumTest.testMoveHorizontalSplitsToLimits (muted).
There is some difference in column widths in Grid. I've uploaded new screenshots for Chrome.
