### ISSUE TITLE
Test for tracking regressions in memory usage with in-memory data sources

### ISSUE THREAD

**Issue by pleku** [vaadin/framework8-issues#387]
There should be an artifact similarly as in the Hummingbird project that reports the memory consumption for the case built in #256.
The test should not be run by default, e.g. not every time you build the project locally.

Module for hummingbird tests is https://github.com/vaadin/hummingbird/tree/master/hummingbird-tests/test-scalability

Blocked by #256

**Comment by denis-anisimov** [comment]
Has no sense to do separately from #256.
Performance tests should be in the separate module otherwise it will affect each validation build.

**Comment by pleku** [comment]
You can also categorize tests not setup them not to be run always
https://github.com/vaadin/hummingbird/blob/7e3843a5b7af8656484555853ed336d2e2c3f960/hummingbird-server/src/test/java/com/vaadin/hummingbird/testcategory/SlowTests.java

**Comment by pleku** [comment]
Unless the other tests would effect the memory usage..

**Comment by Legioth** [comment]
Anything else being run against the same server at the same time will affect memory usage if the Hummingbird approach is used.
