### ISSUE TITLE
Create and test declarative syntax for all new listing components except grid

### ISSUE THREAD

**Issue by pleku** [vaadin/framework8-issues#388]
Will need to port old OptionGroup syntax to be new syntax for CheckBoxGroup and RadioButtonGroup. Make sure NativeSelect, ListSelect, TwinColSelect, ComboBox have tests for declarative syntax.

Listing options are only for type <String>, no custom types are supported in declarative syntax.

**Comment by denis-anisimov** [comment]
As a part of this issue: fix TwinColSelectDeclarativeTest and TwinColSelect declarative support.
Test has serialized data but it's not read during deserialization and selection items are not set as well.
Test doesn't check data source (data items in TwinColSelect) and it doesn't check selected items (value).

**Comment by denis-anisimov** [comment]
https://dev.vaadin.com/review/#/c/14795/
