### ISSUE TITLE
Design and implement declarative syntax for new Grid

### ISSUE THREAD

**Issue by pleku** [vaadin/framework8-issues#390]
Should be possible to set column data provider using indexing, since declarative syntax doesn't define the data source or property-id for columns.

`grid.getColumn(1).setDataProvider`which returns the "same" column with new type. The grid needs to be refreshed when the data providers change. If no data provider for a column has been set, no data should be displayed for that column.

Blocked until all the Grid features have been implemented.

**Comment by Artur-** [comment]
What does this mean? Does this cover inline data or is this about something else?

**Comment by denis-anisimov** [comment]
Yes, inline data.

**Comment by tsuoanttila** [comment]
The way I see it possible for us to allow in-line data from a design is to use Grid<String[]> and generate columns with a ValueProvider than indexes the given Array.

**Comment by denis-anisimov** [comment]
Is it still blocked ?

**Comment by pleku** [comment]
Don't think so.
