### ISSUE TITLE
Listing components must be able to specify their data (generics) type in the declarative format

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#392]
**UPDATE: See comment https://github.com/vaadin/framework8-issues/issues/392#issuecomment-262622369 for what to implement**

Designer needs to be able to generate a Java class with mapped fields based on the declarative format. Right now the only thing which can be generated is

```
protected NativeSelect<?> countrySelect;
```

which is not very useful

**Comment by Legioth** [comment]
I don't see how that could work since the instance itself doesn't even know what it is typed to, and it would thus not be able to produce that data in `writeDesign()`.

**Comment by denis-anisimov** [comment]
Technically designer can store type information by itself.
I.e. in the same way as it handles custom components (any user component, even which is derived from Vaadin component without any client side): it adds a custom HTML element and write mapping between package name and element prefix in a META tag.
The same can be done for type in a Generic.

Producing any java related stuff directly in declarative format doesn't look correct for me.

**Comment by Artur-** [comment]
Package mapping is a bit different as it is a global setting. 

Writing the type of an element to a meta tag would require including mapping to the given element somehow, which pretty quickly becomes ugly. The logical place to write, regardless of who writes, would be an attribute on the element tag so that you get it applied to the correct component. 

Would it work to specify a "namespace" for attributes on the elements so that Designer could write whatever it wants in e.g. `designer-<name>` attributes and components would ignore all `designer-*` attributes and not emit warnings about those?

**Comment by denis-anisimov** [comment]
I think it's a good approach.
But should be use REAL namespace not just a prefix ?
So designer:fqn="a.b.c.D" not designer-fqn="a.b.c.D"

**Comment by Legioth** [comment]
An XML namespace would only make sense if the design file would be XHTML.

I would instead suggest the regular HMTL approach, i.e. prefixing the attribute name with `data-`.

**Comment by Artur-** [comment]
How does a colon make it more of a REAL namespace? It's not XML

**Comment by Artur-** [comment]
`data-` would work also if `readDesign()` would ignore those by default

**Comment by johndevs** [comment]
Another approach if we don't want to add special attributes is to use xml/html comments inside the elements that has this meta information.

**Comment by Legioth** [comment]
Making `readDesign()` ignore `data-` attributes and then somehow figure out a way for getting the attributes back through `writeDesign()` sounds like the most sensible approach.

Do you @johndevs believe that this particular detail, as well as any other aspects caused by changing e.g. from `NativeSelect` to `NativeSelect<T>` would work out for Designer in this way, or do you at this point know anything else that would have to be taken into account?

**Comment by johndevs** [comment]
> Making readDesign() ignore data- attributes and then somehow figure out a way for getting the attributes back through writeDesign() sounds like the most sensible approach.

This shouldn't be a problem as all attributes are currently stored in the `DesignContext` and re-written with `writeDesign()` if you use the correct Design.write() variant. Which the Designer does, as it supports any (even unknown) attributes in an element.

> Do you @johndevs believe that this particular detail, as well as any other aspects caused by changing | e.g. from NativeSelect to NativeSelect<T> would work out for Designer in this way, or do you at this point know anything else that would have to be taken into account?

The Designer doesn't currently care what is written to the Java file, the Java file is never parsed in any way. The only thing it needs is the meta information to know how to write that Java file correctly. That meta information can come from the declarative format or we can in the Designer ask the user for that information. But, if we want this information to be persistent then it needs to be embedded in the HTML file somehow or provided by the Declarative parser at runtime.

**Comment by johndevs** [comment]
But to note, one thing the Designer will not be able to do is support is user types, for example `NativeSelect<MyBean>` won't work as the Designer will not have MyBean on its classpath.

**Comment by ripla** [comment]
@johndevs If the generic type is just metadata we write, then I don't think we need to know about the user types? And you can already use add-ons in the companion file, so that should work as well.

**Comment by johndevs** [comment]
@ripla 

Yes, we can write anything into the Java file but we can't render it on screen. So if the user has a custom bean `MyBean` then we can't render a `NativeSelect<MyBean>`, everything we render is either a native type or `<Object>` if type is not on the CP of the Designer. 

But we can create the Java file with `NativeSelect<MyBean>` sure.

The same goes for addons, we currently use a placeholder class to render the addons as we do not have the addon class on the classpath of the Designer.

**Comment by ripla** [comment]
@johndevs absolutely true. Visually the Designer will only show `NativeSelect<Object>`. I guess that might be a problem if the user expects to see the fields from their object, e.g. in the case of `Grid<MyBean>` where bean properties would be displayed as columns.

**Comment by Legioth** [comment]
> Yes, we can write anything into the Java file but we can't render it on screen.

This actually made me realize some other challenges with how the new components are supposed to work.

Instead of a purely declarative configuration through e.g. `setItemCaptionPropertyId`, the "property" to be used as the caption is instead configured as a `Function<T, String>` (e.g. `MyBean::getTitle`), which cannot be sensibly represented in the design file.

The next problem is related to how inline data (e.g. `<v-native-select><option>Foo</option></v-native-select>`) elements is handled. In that case, `readDesign` of a `NativeSelect<MyBean>` would cause the items of the instance to still be of type `String`, with lots of opportunities for `ClassCastException` down the road if the developer does any programmatic configuration that assumes `MyBean` (e.g. `MyBean::getTitle`).

**Comment by ripla** [comment]
@Legioth Is this currently implemented with `data-item-type`?

**Comment by pleku** [comment]
@denis-anisimov care to comment, how is this handled in #388 ?

**Comment by denis-anisimov** [comment]
It does not relate anyhow to #388.
The fix for #388 is only about `String`s as data type which is explicitly mentioned there.
Anything except string will throw `ClassCastException` of deseriaization attempt.

We need a different ticket if we are going to support type other than `String`s. And this ticket here is also not covered by the #388 at all (the fix for latter ticket is very big already at the moment).

**Comment by Artur-** [comment]
I think the conclusion here is
* The component instance does not know it's data type and cannot thus write it
* Designer knows the data type, can and should write it (and read it)
* Inline data is always a collection of Strings as Designer should ensure the type is `String` when inline data is used
* Framework should ignore "data-*" attributes (not print warnings if such are used)

If this is correct, then only the last point is something that should be done in the framework

**Comment by pleku** [comment]
This issue is about verifying and adding a test that `data-*` attributes are ignored and don't cause any warnings or errors with the framework.

**Comment by denis-anisimov** [comment]
Declarative support already handles any kind of custom attributes (doesn't matter which prefix is used and even their name). Those attributes should not be just "standard" components attributes (they are detected via introspection plus some hardcoded attributes).

Any custom attributes is ignored on `readDesign` and added into DesignContext instance. It can be read from there after deserialization.
It works in the same way for writing : any custom attribute which is set to a DesignContext will be written into declarative format as is. So one has to care about appropriate DesignContext content.

I've extended declarative format tests to check how it works with "data-type" attribute. No other changes are made.

https://dev.vaadin.com/review/14853
