### ISSUE TITLE
Update vaadin-archetype-widget to use only Vaadin 8 API

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework8-issues#407]
No com.vaadin.v7 API is in use

**Comment by denis-anisimov** [comment]
@Artur- has already updated vaadin versions in all archetype projects in the commit 505da7bd5e2a57f2dd248b50f3ed821885393273.
Apparently source code in the application archetype has not been updated to use v7 compatibility packages.
So everything works as is. Verified.
Nothing to do.

**Comment by pleku** [comment]
Atleast the Connector could have been updated to use Java 8 syntax, since it if it isn't now, it never will

``` java
        getWidget().addClickHandler(new ClickHandler() {
            public void onClick(ClickEvent event) {
                final MouseEventDetails mouseDetails = MouseEventDetailsBuilder
                        .buildMouseEventDetails(event.getNativeEvent(),
                                getWidget().getElement());

                // When the widget is clicked, the event is sent to server with ServerRpc
                rpc.clicked(mouseDetails);
            }
        });
```

**Comment by denis-anisimov** [comment]
https://github.com/vaadin/archetypes/pull/103
