### ISSUE TITLE
Test manually Java 9 EA with all the archetypes

### ISSUE THREAD

**Issue by pleku** [vaadin/framework8-issues#410]
#321 is for automating this, but we should verify manually before beta that it works.

Should test both creation and running of the apps.

Excluding the liferay archetype.

**Comment by ahie** [comment]
For java 9 compatibility maven-war-plugin dependencies need to be upgraded from 2.6 to 3.0.0 or later. Additionally the `compile` goal in vaadin-maven-plugin is broken, meaning anything with a custom widget set will not build, which is all the archetypes this issue covers except vaadin-archetype-application.

Running the compile goal with jdk9 gives the following error:
```
[INFO] --- vaadin-maven-plugin:8.0-SNAPSHOT:compile (default) @ widget-test-demo ---
[INFO] auto discovered modules [AppWidgetset]
[INFO] Compiling module AppWidgetset
[INFO]    [ERROR] Hint: Check that your module inherits 'com.google.gwt.core.Core' either directly or indirectly (most often by inheriting module 'com.google.gwt.user.User')
```
Which originates from gwt.
