### ISSUE TITLE
Gerrit Review queue resolving for Sprint 2 

### ISSUE THREAD

**Issue by pleku** [vaadin/framework8-issues#411]
The goal is 27 updates on gerrit open PRs for framework.

Add comment on this issue per each review PR.

**Comment by pleku** [comment]
https://dev.vaadin.com/review/#/c/1664/ abandoned

**Comment by tsuoanttila** [comment]
https://dev.vaadin.com/review/#/c/11414/ Abandoned
https://dev.vaadin.com/review/#/c/2332/ Replaced with an appropriate javadoc fix

**Comment by denis-anisimov** [comment]
https://dev.vaadin.com/review/4985 : abandoned

**Comment by denis-anisimov** [comment]
https://dev.vaadin.com/review/2040 abandoned
https://dev.vaadin.com/review/1946 abandoned

**Comment by pleku** [comment]
https://dev.vaadin.com/review/#/c/5835/ abandoned and issue `#8705` closed as worksforme

**Comment by denis-anisimov** [comment]
https://dev.vaadin.com/review/#/c/5389/ abandoned.
https://dev.vaadin.com/review/#/c/5183/ abandoned.

**Comment by tsuoanttila** [comment]
https://dev.vaadin.com/review/#/c/5603/ Abandoned

**Comment by denis-anisimov** [comment]
https://dev.vaadin.com/review/#/c/4222/ integrated.
https://dev.vaadin.com/review/#/c/4917/ abandoned.
https://dev.vaadin.com/review/#/c/5412/ abandoned.
https://dev.vaadin.com/review/#/c/5413/ abandoned.
https://dev.vaadin.com/review/#/c/5187/ integrated.
https://dev.vaadin.com/review/#/c/5668/ abandoned.

**Comment by pleku** [comment]
https://dev.vaadin.com/review/#/c/8180/ abandoned (doesn't apply anymore)
https://dev.vaadin.com/review/#/c/8032/ abandoned (issue is won't fix)

**Comment by denis-anisimov** [comment]
https://dev.vaadin.com/review/#/c/5178/ abandoned.
https://dev.vaadin.com/review/#/c/4368/ abandoned.
https://dev.vaadin.com/review/#/c/4311/ abandoned.
https://dev.vaadin.com/review/#/c/4534/ abandoned.
https://dev.vaadin.com/review/#/c/8707/ abandoned.
https://dev.vaadin.com/review/#/c/11198/ abandoned.

**Comment by pleku** [comment]
​https://dev.vaadin.com/review/#/c/8691/ abandoned then reopened (owner responded)

**Comment by pleku** [comment]
https://dev.vaadin.com/review/#/c/8690/4 integrated to 8 and being backported to 7.7

**Comment by denis-anisimov** [comment]
https://dev.vaadin.com/review/8632 abandoned.
https://dev.vaadin.com/review/#/c/5472/ integrated.
