### ISSUE TITLE
Use setInputPrompt instead of setPlaceholder

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework8-issues#413]
Previous framework versions have used `setInputPrompt` for configuring a helper message that is shown in an input component before any value has been set. `AbstractTextField` and `DateField` are now instead using `setPlaceholder` for the same functionality.

We should change those back to use the old names that is used in existing applications and that all our documentation (including old versions) refers to unless someone can show that the new name is clearly superior.

**Comment by Artur-** [comment]
Pros:
- "Placeholder" is familiar to web developers
- It communicates that something has changed and helps explaining why old theme rules do not work

Cons: 
- Not backwards compatible, but this is handled by the `.v7.` component

**Comment by heruan** [comment]
I approve the new `setPlaceholder` and I think it's semantically more correct: it holds the _place_ of a missing value (e.g., a default value). It *could* be used as an "input prompt", but that's just a particular use case. For example:

```java
TextField bandwidthLimit = new TextField("Bandwidth Limit");
bandwidthLimit.setPlaceholder("Set the bandwidth limit"); // <== used as "input prompt"
bandwidthLimit.setPlaceholder("Unlimited"); // <== used as "default value"
```

Placeholders are often used as "help text" and "input prompt", but their semantic is more generic; also, in my opinion a better place for "help text" and "input prompt" could be a small text under the field or a tooltip when the field is focused.
