### ISSUE TITLE
Remove API for validator result values

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework8-issues#414]
`Validator.apply` returns a `Result<T>` that must contain a value if validation passes. The value passed to `Result<T>` is however never used since `ValidatorAsConverter` is explicitly implemented to use the original value instead.

Requiring a result value makes it harder to understand and use the `Validator` API. The result value could in theory be used to allow validators to also sanitize the value, but that's a quite special use case that can already be implemented using the more versatile `Converter` API, which is already explicitly expected to modify the value if it is accepted.

We could also introduce a separate `SanitizingValidator` helper API if that use case is something that we'd want to explicitly support, but that work should be prioritized, designed and implemented separately.

**Comment by pleku** [comment]
`interface ValidationResult`  (which is not Result) :
- `private ValidationResult() {}` document in javadocs that static factory methods should be used
- `getErrorMessage: String throws IllegalStateException` (if isError == true)
- `isError : boolean`
- `static ok() : ValidationResult`
- `static error(String errorMessage) : ValidationResult`

**Comment by denis-anisimov** [comment]
Demos should be updated since Validation API is broken.

**Comment by denis-anisimov** [comment]
https://dev.vaadin.com/review/14729

#433 is created to update demos.
