### ISSUE TITLE
BeanValidator should use component locale

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#417]
`BeanValidator` currently requires a Locale to be given in the constructor. 

This is tricky to use 
- if `BeanValidator` is initialized by the framework - where does the locale come from?
- if the developer initializes the `BeanValidator` he needs to know the locale that will be in use in the end, something typically not available in a constructor (the final locale is the component locale, a parent component locale, the UI locale or the VaadinSession locale)

**Comment by Legioth** [comment]
I would suggest removing the constructor parameter and adding `Locale` (or `ValueContext`) as a parameter to at least `getMessage` once #418 has been implemented.

**Comment by pleku** [comment]
Because ValueContext has been introduced to apply method, can now remove Locale from the constructor and as a field completely.

**Comment by pleku** [comment]
https://dev.vaadin.com/review/#/c/14674/
