### ISSUE TITLE
Remove HasValue from Grid

### ISSUE THREAD

**Issue by pleku** [vaadin/framework8-issues#425]
- `grid.setSelectionModel(SelectionModel)` currently only supports single select
- `grid.asSingleSelect() : SingleSelect`
  - uses currently set single selection model
  - switches from MultiSelectModel to default singe select model if necessary
  - Flags the `setSelectionModel(SelectionModel)` method to throw, cannot change selection type when bound to binder\* Maps to single select mode and allows using Grid in the binder

**Comment by pleku** [comment]
Blocked by #422, maybe good to do after #424

**Comment by denis-anisimov** [comment]
Please keep in mind that currently (after #423) Grid extends AbstractSingleSelect and contains a number of inherited methods from there that are not in sync in Grid SelectionModel (so there is Grid::select which doesn't do the same as Grid.getSelectionModel().select).

**Comment by pleku** [comment]
https://dev.vaadin.com/review/#/c/14760/1
