### ISSUE TITLE
Make it possible to specify an alternate JVM forked by the Maven plug-in goals

### ISSUE THREAD

**Issue by hesara** [vaadin/framework8-issues#428]
Integration testing of an archetype runs commands with the default JVM. As e.g. UpdateThemeMojo does not use AbstractGwtShellMojo.createJavaCommand(), it is not possible to override the JVM used from the command line parameters to Maven.

Alternatively, find another way to make the integration tests work in an environment where the default JVM is an older version.

**Comment by hesara** [comment]
Issue https://dev.vaadin.com/ticket/20432 addressed by https://dev.vaadin.com/review/#/c/14667/ .

**Comment by denis-anisimov** [comment]
Is it done ?
