### ISSUE TITLE
BeanBinder field level bean validation support

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#43]
```
public class Person {
  @Min(2000)
  private int yearOfBirth;

  //Non-standard constraint provided by Hibernate Validator
  @NotEmpty
  private String name;

  // + other fields, constructors, setters, and getters
  ...
}
```

**Comment by jdahlstrom** [comment]
84e225eccff1a56abc77feb6e9ff34b4845f4364

This is actually a prerequisite for the BeanBinder patch

**Comment by denis-anisimov** [comment]
The validator is already there. BeanBinder just should use it.
But this requires BeanBinder.
Depends on #42.

**Comment by jdahlstrom** [comment]
https://dev.vaadin.com/review/#/c/14114/3

**Comment by jdahlstrom** [comment]
https://dev.vaadin.com/review/#/c/14114/5
