### ISSUE TITLE
Spike: Grid Editor based on Binder

### ISSUE THREAD

**Issue by pleku** [vaadin/framework8-issues#436]
Spike on #138 timeboxed as 1, which is roughly half a working day, to figure out any:
- API changes (e.g. FieldGroupFieldFactory has no replacement in Binder)
- any blockers
- any open implementation questions

After this it should be possible for team to give a new estimate on the (remaining) work for getting #138 done.

**Comment by pleku** [comment]
``` java
Grid<Person> grid = new Grid<>();
// setup columns
Binder<Person> binder = new Binder<>();
// setup binder fields, converters, validators
grid.setBinder(binder); // or ?
grid.setEditor(binder);
```
- The Grid uses the Fields from the Binder mapping to each Column. All editing goes through the Binding. Both buffered and unbuffered modes can be supported with Binder
- Framework handles mapping from Column's `SerializableFunction valueProvider` to the Binding's `SerializableFunction valueProvider` ?
  - Won't work if the value provider is an inline lambda instead of method reference
  - We need another way of either mapping those automatically, or making it possible for user to map the column to a Binding in Binder.
- No support for FieldFactory or whatnot since not part of Binder currently, and if Binder would get that feature, then Grid doesn't really care but just uses the Fields the Binder provides
- Displaying any Field that the Binder provides inside the Grid should work the same way as with V7 Grid.

The supported methods from V7 Grid:

``` java
setEditor(Binder) : void // previously setEditorFieldGroup(FieldGroup)
setEditorBuffered(boolean) : void
setEditorEnabled(boolean) : void
setEditorSaveCaption(String) : void
setEditorCancelCaption(String) : void
resetEditor() : void // package-protected in V7
saveEditor() : void
isEditorActive() : boolean
isEditorBuffered() : boolean
isEditorEnabled() : boolean
getEditedItem() : <T> // previously getEditedItemId()
getEditor() : Binder // previously getEditorFieldGroup()
getEditorSaveCaption() : String
getEditorCancelCaption() : String
```

Or replace with _Editor_ with _Binder_ ?

Not supported methods from V7 Grid:

``` java
setEditorErrorHandler(EditorErrorHandler) : void // should go through Binder error handling
setEditorFieldFactory(FieldGroupFieldFactory) : void // will use Binder FieldFactory, if it is ever added
```

**Comment by heruan** [comment]
What's the status of this? I'm testing 8.0-SNAPSHOT but I'm unable to make `Grid` editable with a `Binder`. I'm trying this:

```java
Binder<User> userBinder = new Binder<>();
TextField firstNameField = new TextField();
userBinder.bind(firstNameField, User::getFirstName, User::setFirstName);

Grid<User> userGrid = new Grid<>();
userGrid.setDataProvider(userDataProvider);
userGrid.addColumn("First Name", User::getFirstName).setEditorComponent(firstNameField).setEditable(true);
```

but that's only a guess, since I understand there's no relation between `userGrid` and `userBinder`.

**Comment by pleku** [comment]
@heruan you need to use `grid.getEditor().setBinder(userBinder);` with that.

Unfortunately the Binder in Grid does not currently map automatically corresponding columns to the binder fields, but that auto-magic will probably made possible by the BeanGrid (#250) later on.

**Comment by heruan** [comment]
Thank you @pleku, got finally the editor to show up! Just another question: how to attach a listener on editor save? For example to commit the bean to its database.

I really love how FW8 is sharping its steel 😎

**Comment by heruan** [comment]
I'm still testing the grid with editor and binder in 8.0.0.beta1, but I'm stuck on committing editor changes. This is what I've done:

```java
Binder<User> binder = new Binder<>();
TextField firstNameField = new TextField();
binder.bind(firstNameField, User::getFirstName, User::setFirstName);
Grid<User> grid = new Grid<>();
grid.getEditor().setBinder(binder).setEnabled(true);
grid.addColumn(User::getFirstName).setEditorComponent(firstNameField);
```
This makes the grid beans editable, i.e. the `firstNameField` gets bound to the bean property and if I make changes to it the value in the grid updates. But, where can I put code to persist the change to the database? I tried this:

```java
binder.addStatusChangeListener(change -> {
    if (change.getBinder().hasChanges()) {
        User user = (User) change.getBinder().getBean();
        this.userService.save(user);
    }
});
```
but `getBean()` always returns `null`, plus it gets called on every keystoke. How can I listen on the editor's save action?

**Comment by tsuoanttila** [comment]
Thank you @heruan for pointing this out. I added a new ticket vaadin/framework#8202 for adding the events to Editor. For now as a workaround, you can override the `Binder.writeIfValid(T bean)` method, and handle the saving there. The method should look like this:
```
boolean valid = super.writeIfValid(bean);
if (valid) {
    // Your update logic
}
return valid;
```

**Comment by heruan** [comment]
Thank you @tsuoanttila for opening the new ticket. Should I use this repository [framework8-issues](https://github.com/vaadin/framework8-issues) or the other one [framework](https://github.com/vaadin/framework) to open issues on FW 8?

**Comment by Legioth** [comment]
> Should I use this repository framework8-issues or the other one framework to open issues on FW 8?

@heruan: Please use https://github.com/vaadin/framework for any new issues.

https://github.com/vaadin/framework8-issues was only intended to be a stopgap until we got all tickets from https://dev.vaadin.com/ migrated to GitHub.
