### ISSUE TITLE
Demonsterize Grid.java

### ISSUE THREAD

**Issue by elmot** [vaadin/framework8-issues#437]
Grid.java contains 2600 lines of code and 22 inner classes, and those numbers are going to grow. The class looks really huge.
That is not a java way to write code, it and it does not look like readable stuff, and our customers could get wrong impression about framework code quality.
Grid.java should be refactored and split into parts of a reasonable size.

**Comment by denis-anisimov** [comment]
👍 +1

**Comment by Legioth** [comment]
Please define the user value from this change.

**Comment by snyholm** [comment]
This would not bring direct user value but instead could be considered marketing value since anyone doing a review of our products would not be scared away. This would also bring developer value in the form of #FFS since extending any functionality of Grid would be made easier. This would also at the same time allow you to redesign/rethink Grid so that it actually IS extendable and not another VScrollTable type solution.

**Comment by jouni** [comment]
> Please define the user value from this change.

We, and perhaps external developers also, would be able to produce more features quicker. No facts to back this up, but it’s a strong feeling.

Perhaps not going to help Framework 8 just yet, but the next version of our Core Elements grid will do exactly this. It’s basically the opposite of the current monolith, where all the features are broken into separate files.

You can browse them here (all the vaadin-grid-*.html files): https://github.com/vaadin/vaadin-grid/tree/2.0-dev, where the biggest file, vaadin-grid-table.html is a bit less than 500 LOC (most of them under 200 LOC).

With this approach, there’s of course maybe slightly more cognitive load for you when you try to figure out in which file to look when searching for a particular feature. And it’s of course JavaScript, so there’s no great code navigation tools (yet) available such as the powerful Java IDEs you’re used to.

**Comment by macjuan** [comment]
"Grid.java should be refactored and split into parts of a reasonable size."

Refactored how? Split into what parts? What is reasonable size? Sebastian already touched on the user value part but I ask again: what is the end user value of doing something that is not clearly defined?

**Comment by denis-anisimov** [comment]
There are common Java style rules.
One of such rule: the size of one class cannot be more than 1000 lines (of course 1000 can be customized). If it has more then it means that class does too may things. It takes too much responsibility and has to be refactored. Such large code is hard to maintain and hard follow the logic.
It helps further development.
But it doesn't bring immediate user value. That's true. The question is the definition of user value.

**Comment by jouni** [comment]
It enables end user value, and brings direct user value for developers. It is, after all, an open source framework, so developers are probably interested in extending the thing somehow.

**Comment by tsuoanttila** [comment]
Also the internals of the Grid class are mostly already split to pieces inside the Grid.java, so splitting them out is more of a policy question than anything else.

**Comment by elmot** [comment]
@Legioth, @macjuan 
Direct user value:
- Javadocs for the Grid API is much more readable, there is no need to jump over huge file looking for small but important stuff.
- Grid split into parts is much easier to extend or customize.
- #ffs in general

Indirect user value:
- Huge component being split into parts is much easier to maintain, that means better code quality, shorter response time for customers feature requests and bug reports

Marketing value:
- Better customer impression of our Grid
- Better customer impression of our codebase quality in general
- Better formal code quality metrics (I am pretty sure somebody did or will do that kind of analysis over our codebase)

**Comment by elmot** [comment]
@macjuan

Obviously, there is no strict rules when and how to refactor classes. And we do not have any formal rules for that. My personal criteria are:
- No more than three(good) or five(acceptable) inner classes per source file. 
- One to three code screens per function (i.e. 100-200 lines). There might be exceptions but not too many.
- 1000 lines per class at maximum (imports are not counted in, javadocs are)
