### ISSUE TITLE
https://dev.vaadin.com/review/#/c/4222/ broke static resource handing for Spring Boot application

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/framework8-issues#445]
Spring Boot application is broken because of changes made by 
https://dev.vaadin.com/review/#/c/4222/

It's not possible to handle properly now e.g. this URL as a static resource:
http://localhost:8080/VAADIN/vaadinBootstrap.js?v=8.0-SNAPSHOT

`pathInfo` is "/vaadinBootstrap.js"
`request.getServletPath()` is en empty string

As a result `VaadinServlet::getStaticFilePath()` returns null.

**Comment by Artur-** [comment]
If servletPath is `""` and pathInfo is `/vaadinBootstrap.js`, where did `/VAADIN`go?

**Comment by denis-anisimov** [comment]
I have no idea.

**Comment by denis-anisimov** [comment]
Spring CRUD demo is broken because of that.

**Comment by Legioth** [comment]
I think Spring Boot deploys separate servlets for each UI and then one servlet for handling "`VAADIN`" in order to avoid conflicts with e.g. Spring MVC servlets that can in theory exist in the same app. @hesara should know the details about this.

**Comment by denis-anisimov** [comment]
https://dev.vaadin.com/review/#/c/14777/

**Comment by elmot** [comment]
https://github.com/vaadin/spring/pull/155

**Comment by mstahv** [comment]
Has anybody looked into getting rid of "static file serving" altogether? Now when dropping support to older than servlet 3, we might be able to just use /META-INF/resources/ and default servlet.

**Comment by Legioth** [comment]
@mstahv Servlet 3.0 only solves half of the problems with static file serving. The other problem is that the servlet container still wouldn't serve any static resources when there's a servlet mapped to `/*`. We have looked into that in Hummingbird, but I wouldn't want to delay Framework 8 by integrating it at this point.

**Comment by mstahv** [comment]
That's why I mentioned default servlet. We'd still need to map that for "VAADIN" or do the same with filter or by forwarding requests to it from VaadinServlet.

**Comment by Legioth** [comment]
"default" is not defined in the servlet spec and it's not supported by some of the more enterprisey servlet containers that we want to support
