### ISSUE TITLE
Bump CDI add-on version to 2.0

### ISSUE THREAD

**Issue by pleku** [vaadin/framework8-issues#455]
Might consider updating https://github.com/vaadin/cdi-tutorial to FW8, but not part of the DoDo.

**Comment by hesara** [comment]
CDI project test fixes in https://github.com/vaadin/cdi/pull/182 .
Will submit a PR for Vaadin 8 compatibility after 182 is merged.

Basic changes to tutorial code in https://github.com/vaadin/cdi-tutorial/pull/3 (update dependencies and use binder, no additional cleanup). There seem to be some problems with admin access to the create user view in the tutorial application (to be investigated).

Tutorial text is still untouched.

**Comment by hesara** [comment]
Closed the PR for the tutorial and left the changes in the vaadin-8 branch - to be kept separate until FW8 release.

**Comment by pleku** [comment]
vaadin/cdi#182 is merged

**Comment by hesara** [comment]
Changes for Vaadin 8 in the CDI add-on are now in the vaadin-8 branch https://github.com/vaadin/cdi/tree/vaadin-8 

Remaining work: make a separate 1.0 branch and merge vaadin-8 branches to master in both add-on and tutorial projects, update tutorial text, set up automatic snapshot building for the both branches (travis configuration for making snapshots from master exists).

In addition, the tutorial issue with user authentication and the create user view should be investigated.

**Comment by hesara** [comment]
When closing this ticket, please also close https://github.com/vaadin/cdi/issues/181

**Comment by hesara** [comment]
Released 2.0.0.beta1 of the Vaadin CDI add-on.
Tutorial will be updated for the final version - see #vaadin/cdi-tutorial#4.
