### ISSUE TITLE
Implement filtering

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework8-issues#467]
## Changes to be split into tickets of suitable sizes

* Make `Query` generic on a filter type and add this method: `Optional<F> getFilter()`. `DataProvider` gets a new type parameter `<F>` and is changed to require `Query<F>` instead of `Query`.
* New methods in `DataProvider<T, F>`
  * `default <M> DataProvider<T, M> convertFilter(Function<M, F> mapper)` for wrapping the provider into a provider that filters by some other type
  * `default DataProvider<T, Void> setFilter(F filter)` for wrapping the provider into a provider with the provided filter
* `interface AppendableFilterDataProvider<T, F> extends DataProvider<T, F>` with these methods:
  * `F appendFilters(F a, F b)`
  * `default AppendableFilterDataProvider<T, F> appendFilter(F filter)` for wrapping the provider into a provider that uses the provided filter in addition to the filter in the original query (or just the provided filter if there is no filter in the query).
* Components that do not care about filtering are changed to accept `DataProvider<T, ?>` instead of `DataProvider<T>`.
* Components that care about filtering are changed to require a specific `DataProvider` type, i.e. `DataProvider<T, String>` for `ComboBox<T>`.
  * Provide a separate `ComboBox.setUnfilterableDataProvider(DataProvider<T, ?>)` method that can accept any data provider but completely disables all filtering features of the component.
* `ListDataProvider<T> implements AppendableFilterDataProvider<T, Predicate<T>>`.
* `ComboBox.setItems` is configured to use something like `new ListDataProvider<>(items).convertFilter(filterText -> item -> getItemCaptionGenerator().apply(item).toLowerCase(getLocale()).contains(filterText.toLowerCase(getLocale())))`.
  * This does change the default filtering mode from `startsWith` to `contains` and makes it case insensitive, based on feedback from the UX team. 
* Add an overload of  `ComboBox.setItems` that also accepts a `BiPredicate<String, String>` to be used instead of `String::contains`.

## The user impact of this design
```
ComboBox<Person> comboBox = new ComboBox<>();
Grid<Person> grid = new Grid<>();
ListDataProvider<Person> ldp = new ListDataProvider<>(...);

// It shouldn't matter if this is done before or after setItems
comboBox.setItemCaptionGenerator(Person::getFirstName);

// Result: typing "en" into the search field finds "Enrique Iglesias" and "Henry Dunant", but not "Erwin Engelbrecht"
comboBox.setItems(enrique, henry, erwin);

// Result: typing "Er" finds "Erwin Engelbrecht", whereas "en" or "er" finds nothing
comboBox.setItems(String::startsWith, enrique, henry, erwin);

// Compile error, because of invalid data provider filter type
comboBox.setDataProvider(ldp);

// Filters by last name, regardless of the item caption generator
comboBox.setDataProvider(ldp.convertFilter(text -> person -> person.getLastName().contains(text)));

// Same as above, but only showing persons that the user has access to
comboBox.setDataProvider(ldp
    .appendFilter(person -> User.getCurrent().hasAccess(person))
    .convertFilter(text -> person -> person.getLastName().contains(text)));

// Works fine, because Grid doesn't care about data provider types
grid.setDataProvider(ldp);

// Only lists persons that the user has access to
grid.setDataProvider(ldp.setFilter(person -> User.getCurrent().hasAccess(person)));

```

**Comment by pleku** [comment]
Split into subtickets
- [ ] #469
- [ ] #470
- [ ] #471
- [ ] #472
- [ ] #474
- [ ] #475
- [ ] #476
