### ISSUE TITLE
Filtering 2: Add Filtering methods to DataProvider

### ISSUE THREAD

**Issue by pleku** [vaadin/framework8-issues#470]
* `DataProvider` gets a new type parameter `<F>` and is changed to require `Query<F>` instead of `Query`.
* New methods in DataProvider<T, F>
  * `default <M> DataProvider<T, M> convertFilter(Function<M, F> mapper)` for wrapping the provider into a provider that filters by some other type
    * Example:
```java
// Filters by last name, regardless of the item caption generator
comboBox.setDataProvider(ldp.convertFilter(text -> person -> person.getLastName().contains(text)));
```
  * `default DataProvider<T, Void> setFilter(F filter)` for wrapping the provider into a provider with the provided filter
* Components that do not care about filtering are changed to accept `DataProvider<T, ?>` instead of `DataProvider<T>`.
* Components that care about filtering are changed to require a specific DataProvider type, i.e. `DataProvider<T, String>` for `ComboBox<T>`.

Will require fixes for many parts when doing the above

This will break demos #471

**Comment by hesara** [comment]
First part (points 1 and 4): https://dev.vaadin.com/review/#/c/14794

**Comment by hesara** [comment]
Implemented convertFilter() in https://dev.vaadin.com/review/#/c/14796 .

Split off setFilter() to #486 .
