### ISSUE TITLE
Filtering 4: Filtering with ComboBox

### ISSUE THREAD

**Issue by pleku** [vaadin/framework8-issues#474]
ComboBox.setItems is configured to use something like: 
* `new ListDataProvider<>(items).convertFilter(filterText -> item -> getItemCaptionGenerator().apply(item).toLowerCase(getLocale()).contains(filterText.toLowerCase(getLocale())))`.
  * This does change the default filtering mode from startsWith to contains and makes it case insensitive, based on feedback from the UX team.
* Add an overload of ComboBox.setItems that also accepts a `BiPredicate<String, String>` to be used instead of `String::contains`.

All ComboBox examples:
```java
ComboBox<Person> comboBox = new ComboBox<>();
Grid<Person> grid = new Grid<>();
ListDataProvider<Person> ldp = new ListDataProvider<>(...);

// It shouldn't matter if this is done before or after setItems
comboBox.setItemCaptionGenerator(Person::getFirstName);

// Result: typing "en" into the search field finds "Enrique Iglesias" and "Henry Dunant", but not "Erwin Engelbrecht"
comboBox.setItems(enrique, henry, erwin);

// Result: typing "Er" finds "Erwin Engelbrecht", whereas "en" or "er" finds nothing
comboBox.setItems(String::startsWith, enrique, henry, erwin);

// Compile error, because of invalid data provider filter type
comboBox.setDataProvider(ldp);

// Filters by last name, regardless of the item caption generator
comboBox.setDataProvider(ldp.convertFilter(text -> person -> person.getLastName().contains(text)));

// Same as above, but only showing persons that the user has access to
comboBox.setDataProvider(ldp
    .appendFilter(person -> User.getCurrent().hasAccess(person))
    .convertFilter(text -> person -> person.getLastName().contains(text)));
```

**Comment by hesara** [comment]
https://dev.vaadin.com/review/#/c/14811/

**Comment by hesara** [comment]
Old patch replaced by https://dev.vaadin.com/review/#/c/14818/ + a follow-up for it to implement filtering (to be committed).
