### ISSUE TITLE
Filtering 5: Update vaadin-archetype-application-example-app

### ISSUE THREAD

**Issue by pleku** [vaadin/framework8-issues#476]
Implement using the built-in filtering from DataProvider

**Comment by tsuoanttila** [comment]
Should not be touched until #348 has passed review.

**Comment by hesara** [comment]
https://github.com/vaadin/archetypes/pull/110

**Comment by hesara** [comment]
Some more updates are needed after the latest filtering changes.

**Comment by hesara** [comment]
Additional changes in https://github.com/vaadin/archetypes/pull/111
