### ISSUE TITLE
Ensure all Vaadin Components have their own SharedState type

### ISSUE THREAD

**Issue by pleku** [vaadin/framework8-issues#480]
Makes it possible to add new features to components by using SharedState without breaking any components that subclass that component and use their own state type.

This means that all components in FW8 (not in compatibility package of course) should have a SharedState type of their own, even it would be empty. Also applies for abstract classes.

**Comment by hesara** [comment]
Based on a quick scan of the components in vaadin-server (some might not be independent classes that should have all the methods):

Components that are missing getState():

AbstractComponentContainer, ColorPickerPreview, ColorPicker, ColorPickerArea, InlineDateField, PasswordField, CustomField, ColorPickerHistory, ColorPickerSelect, NativeButton, AbstractListing, AbstractSingleComponentContainer, LegacyWindow, CustomComponent, DragAndDropWrapper, Embedded

In addition, some more AbstractClientConnector subclasses that are not components might be missing state (to check).

Connectors that have getState() but are missing getState(boolean):

AtmospherePushConnection, AbstractJavaScriptExtension, VaadinSession, ColorPickerGradient, AbstractJavaScriptRenderer, AbsoluteLayout, AbstractJavaScriptComponent, AbstractLayout, Accordion, Audio, BrowserFrame, CssLayout, FormLayout, HorizontalLayout, HorizontalSplitPanel, Image, JavaScript, TextField, VerticalLayout, VerticalSplitPanel, Video

Classes with getState(boolean) but no getState():

LocaleService, Page, StaticSection, Grid.HeaderImpl, Grid.FooterImpl

**Comment by hesara** [comment]
Add missing state classes for Abstract(Single)ComponentContainer in https://dev.vaadin.com/review/#/c/14823/ .

**Comment by hesara** [comment]
Add missing getState(boolean) methods for connectors that have getState() in https://dev.vaadin.com/review/#/c/14824/ . This change does not address JavaScript related connectors.

**Comment by hesara** [comment]
Non-issues:
* not a shared state: AtmospherePushConnection, VaadinSession
* transmitted as a part of some other state: LocaleService, Page, StaticSection, Grid.HeaderImpl, Grid.FooterImpl

Known remaining work:
* Check state type and add getState(boolean): AbstractJavaScriptExtension, AbstractJavaScriptRenderer, AbstractJavaScriptComponent
* Add state type: ColorPicker*, InlineDateField, PasswordField, CustomField, CustomComponent, NativeButton, AbstractListing, LegacyWindow, DragAndDropWrapper, Embedded
* Check all subclasses of AbstractExtension including renderers

**Comment by hesara** [comment]
InlineDateField, NativeButton and Embedded already had state classes, but they weren't used. Added getState(*) methods for those in https://dev.vaadin.com/review/14825 .

LegacyWindow probably should not be updated as it only exists to ease migration from Vaadin 6.

**Comment by hesara** [comment]
Added shared state for CustomComponent and DragAndDropWrapper in https://dev.vaadin.com/review/14826 .

For CustomField, we should adapt the approach that was added to 7.7 in https://dev.vaadin.com/review/#/c/14518/ and then reverted in https://dev.vaadin.com/review/14804 due to API incompatibility.

**Comment by hesara** [comment]
Previously mentioned cases addressed, I will not work on this further right now.

Remaining known issues:
* JavaScript related connectors such as AbstractJavaScriptExtension, AbstractJavaScriptRenderer, AbstractJavaScriptComponent
* Add state type: ColorPicker*, PasswordField, CustomField, NativeButton, AbstractListing
* Check all subclasses of AbstractExtension including renderers

**Comment by pleku** [comment]
Updated estimate to 2 and consider this to be partly done for now.

**Comment by denis-anisimov** [comment]
I'm not so sure about some classes like `ColorPickerPreview`: they are "composites" (don't have any client side implementation). So I just don't see any sense for them to have their own state. State should be and will be added once someone decides to provide some client side impl.
