### ISSUE TITLE
Filtering 0: Review and integrate make Query generic patch from Per-Åke Minborg

### ISSUE THREAD

**Issue by pleku** [vaadin/framework8-issues#481]
https://dev.vaadin.com/review/#/c/14645/

**Comment by hesara** [comment]
Will not integrate the patch as-is (too many changes have taken place in the project) but in smaller steps.

**Comment by hesara** [comment]
Most relevant changes have been integrated in some form or other in the context of various filtering and sorting steps. Some final javadoc corrections inspired by this patch in https://dev.vaadin.com/review/#/c/14846/ .

**Comment by hesara** [comment]
Abandoned original patch after integrating the javadoc fixes.
