### ISSUE TITLE
Vaadin Spring is broken when communicating over reverse proxy

### ISSUE THREAD

**Issue by pleku** [vaadin/framework8-issues#490]
https://github.com/vaadin/spring/issues/30

**Comment by pleku** [comment]
There is a workaround provided for this, it is currently being tested

**Comment by phillipjohnson** [comment]
What's the status of getting the workaround into a release?

**Comment by pleku** [comment]
@phillipjohnson please comment on https://github.com/vaadin/spring/issues/30, since this repository is was only for issues before we migrated the vaadin/framework to github.
