### ISSUE TITLE
com.vaadin.v7.ui.Upload implementation is not in sync with version in Framework 7

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework8-issues#491]
It seems like some overall API changes had been introduced into the `Upload` implementation before it was copied over to the compatibility package. I observed that various addXyzListener methods return `Registration` instead of `void`, but there might also be other changes.

Make sure the implementation is as closely in sync with the Framework 7 version as possible.

**Comment by hesara** [comment]
Registration changes reverted in https://dev.vaadin.com/review/#/c/14827/ . It seems this was the only functional change introduced before copying (others were formatting etc. related).

**Comment by pleku** [comment]
Fixed by https://github.com/vaadin/vaadin/commit/4f4b47d46823264dfbf18578ed452b6cd7c97f30
