### ISSUE TITLE
Make *all* addXyzListener methods return a Registration object

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework8-issues#492]
There are still some listener addition methods in e.g. `VaadinService` that have not been updated to return `Registration`. Should also remember to deprecated the old methods for removing the listeners.

**Comment by denis-anisimov** [comment]
We have test for this.
It means that it doesn't cover all possible situations. The test should be fixed as well.

**Comment by denis-anisimov** [comment]
#399 ticket is about RemoveListenersDeprecatedTest which is completely broken at the moment.
Will be done separately.

**Comment by denis-anisimov** [comment]
https://dev.vaadin.com/review/#/c/14819/

**Comment by Legioth** [comment]
Still some parts not fixed:
```
$ find server/src/main/java/ -type f | xargs egrep "void add[a-zA-Z]+Listener"
server/src/main/java//com/vaadin/event/SortEvent.java:        public void addSortListener(SortListener listener);
server/src/main/java//com/vaadin/navigator/Navigator.java:    public void addViewChangeListener(ViewChangeListener listener) {
server/src/main/java//com/vaadin/server/VaadinPortletSession.java:    public void addPortletListener(PortletListener listener) {
server/src/main/java//com/vaadin/server/VaadinSession.java:    public void addBootstrapListener(BootstrapListener listener) {
server/src/main/java//com/vaadin/ui/declarative/DesignContext.java:    public void addComponentCreationListener(
```

**Comment by denis-anisimov** [comment]
Will be done as a part of #399.
Only VaadinService methods are done here.
Closing "as a duplicate"
