### ISSUE TITLE
Integrate compatible ComboBox refactorings into master

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#5]

**Comment by hesara** [comment]
Most of the changes in review (https://dev.vaadin.com/review/14034 and its ancestors). Still to pick:
13488e71b0acc95b4c3ed382302b9317a9d5a84d
af4ab7933a7c231b230ee79b70d0da7a8640f4c0
d00406641e0183349656db2348432f3e8b7d1b99
020fe73bfd861bb8713bfe6e012c483a74dc4074
76a702c1c063a1e9f1bc515e13bc496bda9f96a9
