### ISSUE TITLE
Update Slider to extend AbstractFieldNew

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#50]
1. Rename current field implementation, prefix with "Legacy" + retain old field implementation class (unused at this point). Do this in one commit.
2. Change the field implementation to extend AbstractField and fix any problems which arise (probably quite many) in tests and elsewhere
   - All field specific tests must be updated to use the new field
   - Any tests which only uses the field to implement a test for some other component should be updated if it does not require a huge effort, otherwise left for now to use the Legacy component version

**Comment by jdahlstrom** [comment]
ebd32b3fba0942b366634504015ce54dc7b30d3e (in tokka)

**Comment by jdahlstrom** [comment]
https://dev.vaadin.com/review/#/c/13960/ Replace old Slider with new Slider

**Comment by denis-anisimov** [comment]
As agreed: move old impl to legacy package.

**Comment by Artur-** [comment]
https://github.com/vaadin/vaadin/commit/d41411e0f51f29c87b1631e06d46db3399af3266

No LegacySlider created
