### ISSUE TITLE
When configuring Grid columns, I want to add column by just adding the getter, and expect grid to do toString() call to the returned object regardless of type.

### ISSUE THREAD

**Issue by pleku** [vaadin/framework8-issues#500]
```java
grid.addColumn(Person::getAge);
```
instead of 
```java
grid.addColumn(person -> person.getAge().toString());
```
#ffs

It should map the return type value to the types of the existing renderers, or use a TextRenderer and Object.toString on the returned value. 

It must be documented properly that the Sorting might not work in the case of automatically applying toString().

Return type of the addColumn(...) should be not-type-safe Column<?> if we cannot make it type safe.

**Comment by mstahv** [comment]
Thanks dudes, nice enhancement!
