### ISSUE TITLE
Java 9 early access support is broken for widget compilation

### ISSUE THREAD

**Issue by ahie** [vaadin/framework8-issues#503]
The `compile` goal in vaadin-maven-plugin is broken, meaning anything with a custom widget set will not build.

Running the compile goal with jdk9 gives the following error:
```
[INFO] --- vaadin-maven-plugin:8.0-SNAPSHOT:compile (default) @ widget-test-demo ---
[INFO] auto discovered modules [AppWidgetset]
[INFO] Compiling module AppWidgetset
[INFO]    [ERROR] Hint: Check that your module inherits 'com.google.gwt.core.Core' either directly or indirectly (most often by inheriting module 'com.google.gwt.user.User')
```
Which originates from gwt.

**Comment by Legioth** [comment]
Probably related to https://groups.google.com/d/msg/google-web-toolkit-contributors/7rDWQVWc9fU/JpW3AzX7AgAJ

**Comment by raner** [comment]
Confirming that this is still broken for JDK 9.0.1 release version.

**Comment by sajjadafridi** [comment]
@Raner how to conform that?
