### ISSUE TITLE
CheckBox required indicator is not shown

### ISSUE THREAD

**Issue by anssit** [vaadin/framework8-issues#505]
Setting requiredIndicatorVisible to true has no visible effect on CheckBox in any of the layouts.

**Comment by denis-anisimov** [comment]
See #459 for the reference.
The component manages its captions by itself.
But it doesn't contain a logic for required indicator.

Nowadays it's a field but client side logic has not been updated (previously it had not "required" property).

**Comment by denis-anisimov** [comment]
It may seem that this has no sense: required indicator for checkbox means that it should always be checked. So why it's needed at all ?

Because of requiring explicit user action: e.g. marking license agreement as read.
