### ISSUE TITLE
Required indicator not shown in Panel, VerticalSplitPanel and HorizontalSplitPanel

### ISSUE THREAD

**Issue by anssit** [vaadin/framework8-issues#506]
If a component with requiredIndicatorVisible==true is added as the direct child of any of the Panels, its required indicator is not displayed. 

Workaround is to wrap the component with a layout, such as HorizontalLayout or VerticalLayout and not directly add it to the Panel.

**Comment by denis-anisimov** [comment]
See #459 for the reference.

Those components are not layouts. So they doesn't contain a logic for components caption at all.
All components that don't manage their caption by themselves will have the issue inside such non-layout "containers".

Old issue.
Most likely has no sense to fix it in FW8.
