### ISSUE TITLE
Integrate V6 fix and release new version

### ISSUE THREAD

**Issue by pleku** [vaadin/framework8-issues#507]
Commit patch to V6 SVN and release a new vaadin 6 version.

**Comment by Ansku** [comment]
[patch.txt](https://github.com/vaadin/framework8-issues/files/613210/patch.txt)

**Comment by pleku** [comment]
Patch LGTM and is verified manually.

**Comment by Artur-** [comment]
What does the patch fix?

**Comment by Ansku** [comment]
https://gitlab.com/mrts/vaadin-6-scrolling-error

**Comment by Ansku** [comment]
...my commit message would have been 'Fallback for Integer values sent from client-side as Doubles' but I don't seem to have write rights to the repo.

**Comment by pleku** [comment]
Fixes apparently any case where the encoded value type has changed from integer to double, caused by browser updates I presume. The way it is implemented can't break IMO any existing stuff, unless someone depends on this being broken.

**Comment by Artur-** [comment]
LGTM

The "real" fix would probably be https://github.com/vaadin/gwt/commit/381270acf9c2921ca9893dd8e93cafbec7d52b1f but that is only in GWT 2.6+. Can't remember right now what Vaadin 6.8 uses

**Comment by Legioth** [comment]
Before making a V6 release, I also have a security fix that should go in (coordinated with a maintenance release of 7.7)

**Comment by hesara** [comment]
Vaadin 6.8 uses GWT 2.3, so needs this fix. @Legioth please contact me privately about anything else that might need to be fixed.

**Comment by Legioth** [comment]
@hesara I don't have anything else to fix.

It turned out that the security issue was actually in caused by problems in application code. There's some hardening we could apply for 7.x, but it's not relevant for 6.x.

**Comment by hesara** [comment]
Fix merged to SVN as revision 26254.

**Comment by hesara** [comment]
Released in 6.8.18
