### ISSUE TITLE
Date and time elements

### ISSUE THREAD

**Issue by heruan** [vaadin/framework8-issues#509]
Testing Vaadin 8 alpha I noticed that there aren't elements to represent time and date-time values, there's just a `DateField` element which bounds to Java 8 `LocalDate`.

Adopting Java 8's `java.time` in Vaadin is great, then why not having elements bound to `LocalTime`, `LocalDateTime` and `ZonedDateTime`?

This was also discussed on Gitter: https://gitter.im/vaadin/vaadin?at=582c7a5e88fa21d53c2d5cfe

**Comment by nikkijuk** [comment]
I don't know if this is really an issue, but keeping 7.4 DateRenderer (DateRenderer extends AbstractRenderer<Object, Date> ) in ui.renderers and not offering LocalDateRenderer might not feel logical.

**Comment by pleku** [comment]
Updating the `DateRenderer` to be `LocalDate` based is planned for 8.1 currently https://github.com/vaadin/framework8-issues/issues/367

**Comment by nikkijuk** [comment]
Thanks for info. I just noted this today while CheckBoxRenderer was away in alpha 10. No drama, I just converted grid to use html as I didn't need inline editing anyway --- now our prototype app is again feeling well, so thanks and keep on good work. 

As a note: as API user I would feel ok if there would be DateRenderer & LocalDateRenderer, so legacy & java 8, and this would also IMHO be better decision for naming than having same class in vaadin 7 & 8 but with different specs and more even same class with different specs in vaadin 8 and 8.1. For clarity of demos and documentation I'd try to be consistent here to avoid unnecessary noise. 

And yes: of course this needs to be consistent with framework generally, so you might favor of keeping it DateRenderer, but even then switching spec between 8.0 and 8.1 for one component and delivering some other (DateField) out of the box in 8.0 with java8 LocalDate doesn't seems quite consistent.

**Comment by Legioth** [comment]
Components for `LocalDateTime` are covered by https://github.com/vaadin/framework/issues/8132

Having `DateRenderer` and `LocalDateRenderer` in parallel might have its merits.

**Comment by pleku** [comment]
Closing this as has been split into vaadin/framework#8132 (DateTimeField) (WIP for 8.0) and #367 (LocalDateRenderer) (planned for 8.1) and further discussion should be those tickets, thanks.
