### ISSUE TITLE
Update TextField to extend AbstractFieldNew

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#51]
1. Rename current field implementation, prefix with "Legacy" + retain old field implementation class (unused at this point). Do this in one commit.
2. Change the field implementation to extend AbstractField and fix any problems which arise (probably quite many) in tests and elsewhere
   - All field specific tests must be updated to use the new field
   - Any tests which only uses the field to implement a test for some other component should be updated if it does not require a huge effort, otherwise left for now to use the Legacy component version

**Comment by jdahlstrom** [comment]
619e69e548465af15e9b95d9bee6a5fee21e7795 // new TextField
c2769f3e1a71ef3362d768f3b63cb5861e69264d // add AbstractTextField
809a8827217e0fb906994bebe4db1c696e371823 // more API to ATF
5dff0964bdd1b3016fd05ec9b3033ec64d67859d // "text change mode" support

**Comment by jdahlstrom** [comment]
https://dev.vaadin.com/review/13962 // Try to replace old TF with new, x zillion errors

**Comment by hesara** [comment]
Also a handful of other changes seem to touch TextField, AbstractTextField et al. including:
ff768d1f888ab77bc3659fe7e8e178037a46a639
57d6cf71500bb676260bcb65b0bfe83dbe198d10
32a5a7616abafc42b08adb9ccf18f4636a0a56da
f9296a34ddf84f289350e8c7b59618fe3368c57a
as well as some move/rename changesets etc.

**Comment by denis-anisimov** [comment]
As agreed: move old impl to legacy package.
