### ISSUE TITLE
BeanBinder should allow setting validators and converters without declaring both Field and property name (or getter/setter)

### ISSUE THREAD

**Issue by mstahv** [vaadin/framework8-issues#511]
Something like:

        bb.forMemberField(birthDate).withConverter(localDate -> {
            return new Date();
        }, date -> {
            return LocalDate.now();
        }); // saves rules to use later when doing name based binding
        bb.bindInstanceFields(this); // <- this would now managed to do the binding with the above hing

**Comment by pleku** [comment]
Would be nice to have in beta, but might not make it.

Update Spring demo app to use this feature.
