### ISSUE TITLE
Remove InheritableThreadLocal support

### ISSUE THREAD

**Issue by pleku** [vaadin/framework8-issues#514]
Cherry-pick the following two commits to master:
https://github.com/vaadin/hummingbird/commit/c7230d9a8330e5f45a1bcfa1ff2a873403366d08
https://github.com/vaadin/hummingbird/commit/a5bc14b

Set milestone for ticket https://dev.vaadin.com/ticket/20463 to be the 8.0.0 alpha that releases this fix. This won't be backported to 7 at least for now.

**Comment by elmot** [comment]
https://dev.vaadin.com/review/#/c/14852/

This change might affect Spring, CDI, and demo.
