### ISSUE TITLE
Grid.setSelectionMode(SelectionMode.NONE | SINGLE | MULTI)

### ISSUE THREAD

**Issue by pleku** [vaadin/framework8-issues#519]
Similarly as in V7, there should be a method in Grid which takes in an enum representing the three different types of selection modes supported, and switches the Grid's selection model to the corresponding one.

**Comment by pleku** [comment]
https://dev.vaadin.com/review/#/c/14850/

**Comment by denis-anisimov** [comment]
Not migrated yet into GitHub ?
