### ISSUE TITLE
BeanBinder getBean() should not return Optional

### ISSUE THREAD

**Issue by mstahv** [vaadin/framework8-issues#523]
Optional is a nice feature in Java 8, but one shouldn't overuse it. E.g. with BeanBinder I'd claim that when developer is calling getBean (most often that would be in save/delete handler), he can most often be sure that the BeanBinder is already bound. Thus it just add boilerplate code to UI code (or makes developers store the reference to edited bean somewhere else.

**Comment by Legioth** [comment]
Agreed

**Comment by mstahv** [comment]
Closed without patch?

**Comment by ahie** [comment]
Merged PR: https://github.com/vaadin/framework/pull/109
