### ISSUE TITLE
Vaadin BOM should contain version numbers for add-ons

### ISSUE THREAD

**Issue by tsuoanttila** [vaadin/framework8-issues#524]
The Vaadin build should test our add-ons against the new version of the framework and provide the tested version numbers to customer projects. This way we can avoid many incompatibility issues with combining Vaadin and Add-ons like spring plugin, CDI plugin, TestBench...

**Comment by pleku** [comment]
First iteration should be adding Spring add-on version to BOM, and integration testing it.
