### ISSUE TITLE
Button has two properties to allow html content in caption

### ISSUE THREAD

**Issue by anssit** [vaadin/framework8-issues#525]
Button has setCaptionAsHtml and setHtmlContentAllowed - both allow HTML in button text. Which one should be used and shown in designer properties? Is either one of them deprecated?

**Comment by denis-anisimov** [comment]
Good point.
`setCaptionAsHtml` is inherited from AbstractComponent and is available for any component.
`setHtmlContentAllowed` is the Button's own method. Should be removed since it has no sense to duplicate the functionality (at the moment it does exactly the same as `setCaptionAsHtml`).

**Comment by anssit** [comment]
Thanks Denis, will use setCaptionAsHtml then.

**Comment by pleku** [comment]
Button methods should be deprecated.
