### ISSUE TITLE
Change default settings for VerticalLayout and HorizontalLayout

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework8-issues#526]
`VerticalLayout` should by default have spacing = true and margin = true.
`HorizontalLayout` should by default have spacing = true and margin = false.

Create subclasses using the old defaults in the compatibility package (i.e. `com.vaadin.v7.ui.VerticalLayout` and `com.vaadin.v7.ui.HorizontalLayout`) and update all our old tests to use those new classes so that all screenshots still look the same.

**Comment by macjuan** [comment]
+1

**Comment by pleku** [comment]
Effects following demos:
* Quicktickets dashboard
* archetype-demo-app (bookstore)
* sampler
  * horizontal & vertical layout demos should use the new defaults out of the box
  * can use v7.*layout everywhere else
* framework8-demos
  * no visual changes
  * optional: redundant settings

**Comment by mstahv** [comment]
Awesome, I love Vaadin 8 already. The archetype(s) can now be optimised as well. Is there an issue for that?

**Comment by pleku** [comment]
@mstahv #559

**Comment by kiru** [comment]
Hello,
I am migrating an application from Vaadin 7 to 8 and trying to fix the breaking changes.
This changes breaks our application quite heavily.  I am not familiar with the way vaadin was designed and try to understand the reason behind this change?

What are thoughts here, why this change?

Thank you,
Kiru

**Comment by Legioth** [comment]
@kiru This change was made based on observations on how these components are typically used. With the new defaults, less boilerplate code would be needed in most applications.

If you are migrating an application written based on the previous defaults, you can use the legacy versions of these components from the `com.vaadin.v7.ui` package instead of the default `com.vaadin.ui` package. As long as you haven't used any wildcard imports, you can thus easily update your entire project with a simple search & replace. You also need to have `vaadin-compatibility-server` on the classpath in addition to the regular `vaadin-server` dependency.

**Comment by kiru** [comment]
You are right, I can just use the Legacy classes, but they also need to be replaced somewhen, the vaadin-compatibility-server just postpones the actual migration.

I don't think that it is a good idea to create a separate class with the same name, but different package just for the sake of having different defaults. IMHO a constructor method would have been a better solution. Like `HorizontalLayout.createWithSpace()`.
