### ISSUE TITLE
All components are tested on all supported browsers

### ISSUE THREAD

**Issue by pleku** [vaadin/framework8-issues#535]
Automated tests on supported browsers for all components:
- Mozilla Firefox 48+, ESR 45
- Internet Explorer 11
- Edge 14+
- Safari 9+
- Google Chrome 53+

Manual testing on mobile browsers, or if possible to setup automated tests, for components that should work on mobile devices:
- Safari 9+ or newer on iOS
- Chrome 42+ or newer on Android

**Comment by hezamu** [comment]
Consider https://hiptest.net/ for managing the testing. You can talk with Designer team, Risto in particular to learn more.

**Comment by pleku** [comment]
Issue moved to [vaadin/framework #8668](https://github.com/vaadin/framework/issues/8668) via [**ZenHub**](https://www.zenhub.com/)
