### ISSUE TITLE
Grid SelectionListener missing ?

### ISSUE THREAD

**Issue by alvegh** [vaadin/framework8-issues#541]
Hi

I am playing around with Vaadin 8, alpha 8 

addSelectionListener on the Grid seems to be missing, I can only find addItemClickListener, which is not really the same

Thanks
Alex

**Comment by pleku** [comment]
Hi. It is currently missing _by design_, as the selection type is dependent on the selection model used currently. We'll probably sort this out rather soon than later.

In alpha 8 by default in single select mode grid you can use either
```java
grid.asSingleSelect().addValueChangeListener(...)
```
where the event value is the selected item in grid.

Or you can use more specific listener
```java
((SingleSelectionModelImpl) grid.getSelectionModel()).addSelectionListener(...);
```
