### ISSUE TITLE
Inconsistency with AbstractListing server side hierarchy and client side hierarchy

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/framework8-issues#544]
`public abstract class AbstractListing<T> extends AbstractComponent `
`public abstract class AbstractListingConnector extends AbstractFieldConnector`

The problem is necessity to have "read-only"  and "required-indicator" for listings (and Grid as a listing).
But Grid is not a field.

Server side logic for common set/is "readonly" relies on an `AbstractFieldState`.

Perhaps this should be rewritten somehow.

**Comment by pleku** [comment]
This is a won't fix for now
