### ISSUE TITLE
There should be an "offical" way of configuring Grid to not allow selection from the user

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework8-issues#546]
It's possible to configure Grid to not allow user selection through `grid.asSingleSelect().setReadOnly(true)` (or the corresponding for `asMultiSelect`). Those methods are however intended for use with `Binder`. There should also be some way of directly configuring this behaviour without using the far-from-obvious API in `HasValue`. 

This might not be a "popular" enough feature to warrant bloating the API of `Grid` itself, but it could be added to the selection models instead.

**Comment by pleku** [comment]
So what do you think the user would expect when the selection model is changed ?
E.g. should `grid.setUserSelectionAllowed(true);` (or similar) then also force the selection model changed into be read-only ? Should the grid setter and the selection model setter override each other always ?

This seems like it would add the kind of complexity that we just got rid off with immediate-mode and explicit immediate mode. E.g. the newly set selection model is set to read only, if grid has been explicitly set to not allow user selection ...

**Comment by Legioth** [comment]
Problems with changing selection models would be soved by putting the API in the the selection model instead of directly in Grid. That would also slightly hide the API, while still having it in a logical place (which cannot be said about `asSingleSelect().setReadOnly()`).

**Comment by denis-anisimov** [comment]
`SelectionModel` is definitely a better place for this.

**Comment by pleku** [comment]
I agree in having it as a feature for all grid's selection models, adding it to
```java
interface GridSelectionModel<T> {
  ...
  void setUserSelectionAllowed(boolean allowed);

  boolean isUserSelectionAllowed();
}
```
Then it could work with `grid.getSelectionModel().setUserSelectionAllowed();`
Then implementation could be moved completely to `AbstractSelectionModel`, currently not in server side but is on client side so.

Not sure about the naming though, it currently is using `userSelectionAllowed`. Is it better than `userSelectionEnabled` ?
