### ISSUE TITLE
Update CheckBox to extend AbstractFieldNew

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#55]
1. Rename current field implementation, prefix with "Legacy" + retain old field implementation class (unused at this point). Do this in one commit.
2. Change the field implementation to extend AbstractField and fix any problems which arise (probably quite many) in tests and elsewhere
   - All field specific tests must be updated to use the new field
   - Any tests which only uses the field to implement a test for some other component should be updated if it does not require a huge effort, otherwise left for now to use the Legacy component version

**Comment by jdahlstrom** [comment]
c2769f3e1a71ef3362d768f3b63cb5861e69264d and its ancestors

Focus/blur events missing (needs discussion)

**Comment by denis-anisimov** [comment]
As agreed: move old impl to legacy package.

**Comment by hesara** [comment]
It seems no legacy version is needed at the moment for CheckBox as the relevant parts of the API and the client side will be almost identical except for the removal of some obsolete methods inherited from Field/AbstractField - a general helper/wrapper can be added later to handle setPropertyDataSource() if necessary

**Comment by hesara** [comment]
preliminary version at https://dev.vaadin.com/review/#/c/14058 (no legacy version, so no Boolean support in DefaultFieldFactory)
