### ISSUE TITLE
Redundant parameter to CheckBoxRenderer constructor

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework8-issues#551]
When creating a `CheckBoxRenderer`, you need to give the renderer a `getter` callback that is to my understanding always the same as the value provider that you are already using to configure the column. The application developer is thus required to provide the same configuration twice in the same context (in this case "MyItem::isEnabled"): `myGrid.addColumn(MyItem::isEnabled, new CheckBoxRenderer(MyItem::isEnabled, MyItem::setEnabled));`

It seems like the only reason for this parameter is that the `CheckBoxRenderer` is implemented to abuse `ClickableRenderer` for getting data from the client instead of properly passing the actual checkbox value to the server (or fetching it from the renderer's parent connector which should be the corresponding column instance).

**Comment by elmot** [comment]
The problem here is, that CheckBoxRenderer is the only Renderer which modifies item field values. I'll remove this functionality and both constructor parameters from there.

**Comment by Legioth** [comment]
Why can't a renderer update values in the item? This sounds like the entire design of renderers i quite broken.

**Comment by elmot** [comment]
_Default_ renderers can not. Customized ones apparently can. 
Why renderers, not editors must do that?

In Vaadin 7 default renderers also could not modify Properties, but there is a GridRenderers collection  (see directory) which can modify data.

And we have Grid Editor functionality.
