### ISSUE TITLE
Listing components should implement Focusable

### ISSUE THREAD

**Issue by alvegh** [vaadin/framework8-issues#552]
Hi

I have a Window consisting of a TextField for searching and a Grid displaying the results of the search.

After searching I would like to focus the grid so the user can select the item he is interested in.

I could do this in Vaadin 7

But Grid does not seem to implement Focuseable anymore in Vaadin 8/alpha 8 ?

Regards
Alex

**Comment by pleku** [comment]
Thanks for the input, we just noticed this is missing for all of the Listing components, and will be fixed for those too.

**Comment by alvegh** [comment]
Really quick, looking forward to beta1

Thanks
Alex
