### ISSUE TITLE
Data provider should still be appendable after filter conversion

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework8-issues#554]
`AppendableDataProvider.convertFilter` should return `AppendableDataProvider<T, F>` instead of `DataProvider<T, F>` so that multiple filters of the converted type can be combined.

**Comment by pleku** [comment]
What is the use case for this ? Trying to determine if this actually brings any value or is just academic question.

**Comment by Legioth** [comment]
I don't have any specific use case, but it's confusing that you can do `provider.applyFilter(convertedFoo).convertFilter(converter)` but not `provider.convertFilter(converter).applyFilter(unconvertedFoo)`.

**Comment by Legioth** [comment]
All patches merged. Everything is awesome!
