### ISSUE TITLE
Test fail with Finnish locale on build machine

### ISSUE THREAD

**Issue by macjuan** [vaadin/framework8-issues#555]
8.0-snapshot from master build fails on a developer machine where locale is set to Finnish with the following error report:

BinderBookOfVaadinTest.converterBookOfVaadinExample1:270 expected:<1[,]972> but was:<1[ ]972>

Build works fine if locale is set to English(US).

Environment:
- Mac OS X 10.0.5
- Finnish locale
- Macbook Pro 6,2 (mid-2010 2.53 GHz Core i5)

Command to used to build Vaadin 8.0-snapshot:
mvn -U clean install

**Comment by hesara** [comment]
As far as I can tell, this particular test is not fixed by #7957 but requires using a fixed locale for the component in the test (or using a locale dependent reference value).
