### ISSUE TITLE
CustomField as editor component in Grid is broken

### ISSUE THREAD

**Issue by pleku** [vaadin/framework8-issues#558]
In FW8, when using a `CustomField` as an editor component in `Grid`, the `setValue()` is triggered for the CustomField before `initContent()`. This is caused by `EditoImpl::doEdit(T bean)` setting the bean to the binder before the component is attached to the Grid and `initContent()` is triggered.

As a component developer, I would expect the `initContent()` to be triggered by framework before calling `setValue` / `getValue`. Depending on the custom component implementation, this might cause surprising behaviour like NPE the `setValue` / `getValue` methods.

**Comment by Legioth** [comment]
The most safe approach is probably that `setValue` and `getValue` in `CustomField` are implemented to trigger an `initContent()` unless it has already been run. In that way, the component works as expected in all cases, not just together with `Grid`.
