### ISSUE TITLE
Adjust demos and archetypes according to new Vertical/Horizontal layout

### ISSUE THREAD

**Issue by elmot** [vaadin/framework8-issues#559]
horizontal & vertical layout demos should use the new defaults out of the box (See #526)
- [x] Quicktickets dashboard
- [x] archetype-demo-app (bookstore)
- [ ] sampler
- [x] framework8-demos
- [ ] optional: redundant settings

**Comment by hesara** [comment]
Archetype updates in https://reviewable.io/reviews/vaadin/archetypes/114 (need testing).
Framework 8 demos in https://github.com/vaadin/framework8-demo/pull/67 (need testing).

**Comment by hesara** [comment]
Quicktickets dashboard changes in https://github.com/vaadin/dashboard-demo/pull/21

**Comment by hesara** [comment]
Sampler updates split off to #571, other parts done.
