### ISSUE TITLE
Desynchronization between v7.Grid and V8 Grid.

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/framework8-issues#561]
vaadin-compatibility-client/src/main/java/com/vaadin/v7/client/connectors/GridConnector.java has `columnsUpdatedFromState` variable which doesn't exist in 
vaadin-client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java

This variable is used inside `columnResizeHandler` which is `ColumnReorderHandler` to prevent sending multiple resize events from client to the server (it doesn't send events until a resize action is finished).
Actually the variable is used in many other related handlers : visibility, reorder, etc....

Modern Grid connector uses lambdas registered in the `init` method and neither of them doesn't uses any mechanism to prevent spamming the server with bunch of similar events.

This ticket is not about reintroducing back the `columnsUpdatedFromState` variable (this is just an option). It's about the fix of the behavior : prevent spamming the server with events ( at least with resize events). It can be solved in the same way as in the v7 or any other way. This is an implementation detail.

**Comment by denis-anisimov** [comment]
The behavior can be tested with com.vaadin.tests.components.grid.basics.GridBasics UI once https://reviewable.io/reviews/vaadin/framework/7969 is integrated.
It contains a listener for Column resizing.
Each time when column is moved (while DnDing) the event is fired.

**Comment by tsuoanttila** [comment]
at least to me it looks like the event is not fired "all the time", but there is a difference in our GridBasic test compared to GridBasicFeatures for v7. In GridBasics the columns are auto width on init. This actually results into column sizes being locked when the first resize is started, and it happens exactly the same way if you set all columns autowidth in the v7 test as well. What really "spams" the server is updates to sizes on the server end, but these could be filtered out with isUserOriginated check I think.
