### ISSUE TITLE
Create a DateField/InlineDateField/PopupDateField which extend AbstractField

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#57]
1. Rename current field implementation, prefix with "Legacy" + retain old field implementation class (unused at this point). Do this in one commit.
2. Change the field implementation to extend AbstractField and fix any problems which arise (probably quite many) in tests and elsewhere
   - All field specific tests must be updated to use the new field
   - Any tests which only uses the field to implement a test for some other component should be updated if it does not require a huge effort, otherwise left for now to use the Legacy component version

**Comment by denis-anisimov** [comment]
What about DateField which is currently superclass for PopupDateField ?
Should it be updated first ? 
And should current hierarchy be kept ?
Meaning that the ticket is incorrect ?

**Comment by Artur-** [comment]
Makes sense to do DateField + InlineDateField + PopupDateField at once since InlineDateField == DateField and PopupDateField is only a few methods on top of DateField (which should have nothing to do with data binding). The related issue is #56

**Comment by denis-anisimov** [comment]
OK

**Comment by denis-anisimov** [comment]
Let's do it after validators are in place. Otherwise it will require one more round.

**Comment by denis-anisimov** [comment]
As agreed: move old impl to legacy package.

**Comment by denis-anisimov** [comment]
https://dev.vaadin.com/review/#/c/14081/
