### ISSUE TITLE
Grid.select is missing

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#577]
In 7.7, there is `Grid.select` documented as `This method is a shorthand that delegates to the selection model`. This is missing from 8.0.0.beta1

**Comment by pleku** [comment]
Not sure if this should be done as it is not that hard to do `grid.getSelectionModel().select(item)` and the decision has been to move more API from Grid to subclasses (like has always been with Column).

Could add a mention to this to breaking changes though, since all the selection API has been moved from Grid to SelectionModel.

**Comment by denis-anisimov** [comment]
I've faced the same issue (during updating the tests).
Selection model is something that you should aware of but it's a bit not-obvious: selection model becomes quite obvious once you need to work closely with the selection logic in various aspects.
But when you need just only one action (just to pre-select one item) then `grid.getSelectionModel().select(item)` is not really visible.

So I agree that it would be better to keep all selection logic inside selection model.
But it seems that shorthand in a `Grid` is also useful (though I wouldn't say that I'm happy with it).

**Comment by Legioth** [comment]
I'd say that `SelectionModel` is there to make the complex case possible, but the simple cases should still be doable without it.

**Comment by pleku** [comment]
Edited: my bad

**Comment by Artur-** [comment]
Really? https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/data/SelectionModel.java#L118

**Comment by pleku** [comment]
Add
```java
void select(T item) { getSelectionModel().select(item); }
```
and
```java
Set<T> getSelected() { return getSelectionModel().get...; }`
```
and tests (obviously).
Javadocs should only mention that the method delegates to the used selection model
