### ISSUE TITLE
Update layout chapter for Vaadin 8

### ISSUE THREAD

**Issue by hesara** [vaadin/framework8-issues#581]
Update documentation chapter 7 (Layouts) for Vaadin 8.
Update code examples to reflect the changed defaults of HorizontalLayout and VerticalLayout by removing redundant setMargin(true) and setSpacing(true) calls. Remove the use of compatibility components in examples.

**Comment by pleku** [comment]
Closed by https://github.com/vaadin/framework/commit/11f10b827e92ed7c07d6584a181f7f1374e8109b
