### ISSUE TITLE
Grid Renderer contract is poorly defined

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/framework8-issues#587]
Grid renderer is declared as 
`
public abstract class AbstractRenderer<T, V> extends AbstractExtension
        implements Renderer<V> {
`

So renderer should be able to handle `V` type which is the representation type.
This type should be handled on the both sides: server and client.

Renderer should be able to encode the value. So in most cases the type should be `Serializable`.
Also the client should be able to create an instance of the class. So it should have default CTOR.
This is how default serialization-deserialization works.
It's possible to change this behavior but the default one should be clearly written in the javadoc at least.

Also it might be useful to require `V extends Serializable` to prevent WTH.

Right now I have an issue with handling `Void` as a representation type (quite rare and corner case yes, but it's applicable to any type if you provide only `null` as values ).
Server is able to handle `null` value regardless of required type (see `JsonCodes.encode`).
But client side is not able to create an object without the default CTOR.
As a result I have a client side exception

java.lang.RuntimeException: Can not deserialize java.lang.Void
	at Unknown.Xg(com.vaadin.tests.widgetset.TestingWidgetSet-0.js)
	at Unknown.fh(com.vaadin.tests.widgetset.TestingWidgetSet-0.js)
	at Unknown.Chc(com.vaadin.tests.widgetset.TestingWidgetSet-0.js)
	at Unknown.Fhc(com.vaadin.tests.widgetset.TestingWidgetSet-0.js)
	at Unknown.vmc(com.vaadin.tests.widgetset.TestingWidgetSet-0.js)
	at Unknown.xpc(com.vaadin.tests.widgetset.TestingWidgetSet-0.js)
	at Unknown.zpc(com.vaadin.tests.widgetset.TestingWidgetSet-0.js)
	at Unknown.C4d(com.vaadin.tests.widgetset.TestingWidgetSet-0.js)
	at Unknown.u$d(com.vaadin.tests.widgetset.TestingWidgetSet-0.js)
	at Unknown.K_d(com.vaadin.tests.widgetset.TestingWidgetSet-0.js)
	at Unknown.v$d(com.vaadin.tests.widgetset.TestingWidgetSet-0.js)
	at Unknown.L2d(com.vaadin.tests.widgetset.TestingWidgetSet-0.js)
	at Unknown.n4d(com.vaadin.tests.widgetset.TestingWidgetSet-0.js)
	at Unknown.Yi(com.vaadin.tests.widgetset.TestingWidgetSet-0.js)
	at Unknown.Oi(com.vaadin.tests.widgetset.TestingWidgetSet-0.js)
	at Unknown.wi(com.vaadin.tests.widgetset.TestingWidgetSet-0.js)
	at Unknown.vi(com.vaadin.tests.widgetset.TestingWidgetSet-0.js)
	at Unknown.eval(com.vaadin.tests.widgetset.TestingWidgetSet-0.js)
	at Unknown.d(com.vaadin.tests.widgetset.TestingWidgetSet-0.js)
Caused by: com.vaadin.client.metadata.NoDataException: There is no constructor for java.lang.Void
	at Unknown.bh(com.vaadin.tests.widgetset.TestingWidgetSet-0.js)

**Comment by pleku** [comment]
Is there other thing that should be done than
- specify more closely on javadocs on server side renderer what are the requirements 
- require the type `V` to be serializable
- improve error message from client side when Renderer cannot initialize the type

**Comment by Legioth** [comment]
I don't see why `V` would need to be serializable. Are we storing those values anywhere?

> So renderer should be able to handle V type which is the representation type.
This type should be handled on the both sides: server and client.

This is not true. `V` is only the server-side type. The client-side `Renderer` interface has its own type (`T`), but it's not required to be strictly the same as the server-side type as long as the automatic JSON encoding / decoding between the two types are compatible or custom encoding / decoding is implemented (`AbstractRenderer.encode(V)` on the server, `AbstractRendererConnector.decode(JsonValue)` on the client).

**Comment by denis-anisimov** [comment]
Javadocs should be updated: yes.

I'm not sure about type serializability: Serializable is not enough actually. The object is not sent to the client as a serialized Java object. There is a number of known types that are serialized into JSON and send to the client where they are "deserizalized" (but the deserialization mechanism is not the Java one).
It's just an implementation detail that all known types (that can be serialized by default) are serializable. But as I understand it's possible to implement custom Renderer so that it has it's own serialization/deserialization mechanism which doesn't require neither `Serializable` interface nor default CTOR presence.
So I'm not sure here.

As I mentioned above: it's also about default CTOR presence. Current logic wants default CTOR. It should be mentioned in the javadocs (default requirements).

Error message: not sure again. At the moment is mentions serializability which is confusing since `Serializable` is not applicable here as is. Technically serializability is not the same as implementing `Serializable` but in the Java context it's confusing since there is Java serializability.
(again the default CTOR issue). May be the word "deserialize" should be replaced with something else (can be mentioned in addition with explanation). But it's still not that visible since it's a client side exception. It's better to prevent it as early as it's possible (via API contract or servers side exception).

I think it requires some discussion and decision about this.

**Comment by Legioth** [comment]
The thing with `Void` is not really that it doesn't have a default constructor, but more about the fact that since there's no explicit support for that type, then the framework will fall back to the default logic of treating the type as a JavaBean, which obviously doesn't work. We might still need to update some parts of the documentation, but we should probably also implement explicit support for doing a JSON decode of `Void`.

**Comment by denis-anisimov** [comment]
>This is not true. V is only the server-side type. The client-side Renderer interface has its own type (T), but it's not required to be strictly the same as the server-side type as long as the automatic JSON encoding / decoding between the two types are compatible or custom encoding / decoding is implemented (AbstractRenderer.encode(V) on the server, AbstractRendererConnector.decode(JsonValue) on the client).

This is the default implementation. That's the problem.
Yes, you can implement a custom renderer which handles serialization/deserialization by itself. 
But you are not aware of it until you find that serialization doesn't work for you out of the box. 
And it's far away from obvious that you have to care about serialazablity in any way (not Java ser-ty). Contract doesn't say anything about that.
So something should be done to reveal this fact via the contract.

**Comment by denis-anisimov** [comment]
>The thing with Void is not really that it doesn't have a default constructor, but more about the fact that since there's no explicit support for that type, then the framework will fall back to the default logic of treating the type as a JavaBean, which obviously doesn't work. We might still need to update some parts of the documentation, but we should probably also implement explicit support for doing a JSON decode of Void.

Void is just a special case here.

There is an issue with ANY type if the value is `null`. `null` is always encoded as null value. Regardless of the type. So if a type is not "serializable" then nothing is said about that (if the value is `null`). If value is not null then there will be an exception thrown in case `JsonCodes` is not able to serialize the type).

So either null should not be encoded by default in case the type is not suitable 
or
client side should handle `null` value regardless of its type (do not try to deserialize a type itself if the value is `null`).
