### ISSUE TITLE
UI close method ignores some of the CurrentInstances

### ISSUE THREAD

**Issue by szolo** [vaadin/framework8-issues#593]
During UI close operation all pending tasks will be executed:

```
    public void close() {
        closing = true;

        boolean sessionExpired = (session == null
                || session.getState() != State.OPEN);
        getRpcProxy(UIClientRpc.class).uiClosed(sessionExpired);
        if (getPushConnection() != null) {
            // Push the Rpc to the client. The connection will be closed when
            // the UI is detached and cleaned up.

            // Can't use UI.push() directly since it checks for a valid session
            if (session != null) {
                session.getService().runPendingAccessTasks(session);
            }
            getPushConnection().push();
        }

    }
```

Inside **runPendingTasks** method - _oldInstances_ are preserved:

```
    public void runPendingAccessTasks(VaadinSession session) {
        assert session.hasLock();

        if (session.getPendingAccessQueue().isEmpty()) {
            return;
        }

        FutureAccess pendingAccess;
        Map<Class<?>, CurrentInstance> oldInstances = CurrentInstance
                .setCurrent(session);
        try {
            while ((pendingAccess = session.getPendingAccessQueue()
                    .poll()) != null) {
                if (!pendingAccess.isCancelled()) {
                    pendingAccess.run();

                    try {
                        pendingAccess.get();

                    } catch (Exception exception) {
                        pendingAccess.handleError(exception);
                    }
                }
            }
        } finally {
            CurrentInstance.clearAll();
            CurrentInstance.restoreInstances(oldInstances);
        }
    }
```

Problem is in the **setCurrent** method, right now it only restores **VaadinSession** and **VaadinService**, other instances (e.g. **VaadinRequest**) will be ignored.

```
    public static Map<Class<?>, CurrentInstance> setCurrent(
            VaadinSession session) {
        Map<Class<?>, CurrentInstance> old = new HashMap<>();
        old.put(VaadinSession.class, set(VaadinSession.class, session));
        VaadinService service = null;
        if (session != null) {
            service = session.getService();
        }
        old.put(VaadinService.class, set(VaadinService.class, service));
        return old;
    }
```

This issue was introduced in this [commit](https://github.com/vaadin/framework/commit/6d1abeb9fc1103af0a04dfd79d56b0f883de6f72#diff-28f7e9d6ae1f3ce848d7a760a2e4cb38L1863).

I'll add a workaround to Designer right now, so we won't be blocked completely.

P.S. this is beta1.

**Comment by Legioth** [comment]
`VaadinRequest` has never been available in "access tasks" since the old behaviour was to only make "inheritable" instances available.

What has changed though is that the entire concept of "inheritable" has been removed since it caused unexpected memory leaks. This unfortunately means that any custom current instance that you defined will no longer be available automatically, which should also be quite clear since the `CurrentInstance.setInheritable` method has also been removed.

**Comment by szolo** [comment]
@Legioth I wasn't talking about "access tasks" and we have never used it that way. After your patch I can't use it in **beforeClientResponse** because its invocation is right after your logic, but corresponding **ThreadLocal** (it's the same) doesn't contain **VaadinRequest**. Do we have a limitation now, that **VaadinRequest** stops being accessible in **beforeClientResponse**?

**Comment by Legioth** [comment]
I cannot reproduce the issue you're describing. `VaadinService.getCurrentRequest()` seems to be defined inside  `beforeClientResponse` both when handling a regular request and a request that does `UI.close()`.

In the code that you're showing, `CurrentInstance.restoreInstances(oldInstances);` in the finally block ensures that it is preserved.

Could you please share some example code that worked in previous versions but that do not work any more?

**Comment by szolo** [comment]
@Legioth **restoreInstances** method is using _oldInstances_ map which doesn't include **VaadinRequest**, only **VaadinSession** and **VaadinService** (see source code of **setCurrent** method above, from which we get this _oldInstances_ map).

**Comment by szolo** [comment]
This source code throws NPE if request does a `UI.close()`, it was fine before this patch.

    static void markCurrentRequest() {
        if (VaadinService.getCurrentRequest().getParameter(
                InternalDesingerApplicationMarker.DESINGER_IDE_MARKER) != null) {
            VaadinSession.getCurrent().setAttribute(
                    InternalDesingerApplicationMarker.DESINGER_IDE_MARKER,
                    Boolean.TRUE);
        }
        if (VaadinService.getCurrentRequest().getParameter(
                InternalDesingerApplicationMarker.LINUX_MARKER) != null) {
            VaadinSession.getCurrent().setAttribute(
                    InternalDesingerApplicationMarker.LINUX_MARKER,
                    Boolean.TRUE);
        }
    }

@Legioth you're right that **VaadinService** itself is preserved, but internally it's still using **ThreadLocal** in order to retrieve the **VaadinRequest** and there are no **VaadinRequest** in **ThreadLocal** since it wasn't restored and old instance was deleted by  **CurrentInstance.clearAll** invocation.

**Comment by Legioth** [comment]
Now I see. My simple test worked because `runPendingAccessTasks` returned immediately since the queue was empty.

This is actually a problem for `beforeClientResponse` in all situations, not only in combination with `UI.close()`.
