### ISSUE TITLE
Inconsistent naming between SelectionModel and SelectionEvent

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework8-issues#596]
`SelectionModel.getFirstSelectedItem()` vs `SelectionEvent.getFirstSelected()`.

Also check for other similar inconsistencies.

**Comment by pleku** [comment]
Use `getFirstSelectedItem()` because we want to distinct between `getSelected()` which returns a Set instead of just one item

**Comment by denis-anisimov** [comment]
Didn't find other such cases.
Let's fix them on demand.
