### ISSUE TITLE
Grid/AbstractListing and individual item updates

### ISSUE THREAD

**Issue by lightoze** [vaadin/framework8-issues#599]
Simplified (comparing to Vaadin 7) data provider system is great, but I have considerations regarding one use case - pushing updates of individual items displayed in a grid.

Assume that you have a list of POJOs where each item have unique ID. After the list is loaded you receive updated versions of POJOs. In that case, you need to:
1. identify whether received item ID is currently displayed (i.e. within current paged view);
2. replace/update an item without fetching the whole list again;
3. in some scenarios, make sure that row selection is not affected by the update.

After studying Vaadin 8 classes, I see that 2 and 3 seem to be possible if you copy data between POJOs instead of swapping objects and use `DataCommunicator.refresh(T data)`. It would be a bit inefficient now due to current implementation will iterate the whole list in `getActiveData()`, but can be improved.
Also there seems to be no easy way to lookup existing POJO to update. All relevant information is enclosed in `ActiveDataHandler` with no public access.

Please share your thoughts. I have one option on how to solve the problem:
1. optimize `DataCommunicator.refresh(T data)` implementation so that instead of calling `getActiveData().contains(data)` it would do something like `getKeyMapper().contains(data) && activeData.contains(getKeyMapper().key(data))`;
2. extend `DataCommunicator` API to allow tapping into active data set - public `getActiveData()` and active item listener support would be ideal. Listener would be able to maintain a map from domain-specific ID to a currently displayed POJO and item 1. from above list would be solved.

**Comment by Legioth** [comment]
I believe this is handled by https://github.com/vaadin/framework/pull/8271 that was recently merged.

Please reopen or file a new issue if there's still some part that is not supported by the new functionality.
