### ISSUE TITLE
Update ProgressBar to implement HasValue

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#60]
1. Rename current field implementation, prefix with "Legacy" + retain old field implementation class (unused at this point). Do this in one commit.
2. Change the field implementation to extend AbstractField and fix any problems which arise (probably quite many) in tests and elsewhere
   - All field specific tests must be updated to use the new field
   - Any tests which only uses the field to implement a test for some other component should be updated if it does not require a huge effort, otherwise left for now to use the Legacy component version

**Comment by denis-anisimov** [comment]
As agreed: move old impl to legacy package.

**Comment by Artur-** [comment]
It was decided that ProgressBar should not implement HasValue
