### ISSUE TITLE
Measure and compare app load time between V7 and V8

### ISSUE THREAD

**Issue by pleku** [vaadin/framework8-issues#607]
First step is to test and compare initial page loading time in Dashboard & app-example from archetypes with Lighthouse (or similar). To verify changes between different Lifehouse versions, a third app non-vaadin app should be used as a benchmark.

**Comment by pleku** [comment]
oops

**Comment by rogozinds** [comment]
I have the same problem, that initial loading time in v8 is almost 2 times bigger than for 7.7.7 at Firefox.
Framework 7 screen:
![v_777](https://cloud.githubusercontent.com/assets/1339320/23849478/6f9294da-07e4-11e7-85f5-5bfdcd289213.png)
Framework 8 screen.
![v_800](https://cloud.githubusercontent.com/assets/1339320/23849486/72bd3cbe-07e4-11e7-9fcc-f85970048fd0.png)
As test application I'm using testbench-demo:
https://github.com/vaadin/testbench-demo

**Comment by mstahv** [comment]
I tried the same app and got similar results (except that my both times were faster). Has this been investigated more?

**Comment by Artur-** [comment]
One problem in the "testbench-demo" app is that `Grid.onAttach` is called two times during initial render, and both invocations take around 25-30ms.
