### ISSUE TITLE
Binder.bindInstanceFields() overwrites existing bindings

### ISSUE THREAD

**Issue by twiggledi** [vaadin/framework8-issues#608]
Seems #47 is not solved or problem exists again. In Version **8.0.0.rc2** using Binder.bindInstanceFields() tries to bind existing fields again.
Similar as mentioned in #47 
```
binder.forField(yearOfBirth)
  .withConverter(
    new StringToIntegerConverter("Please enter a number"))
  .bind(Person::getYearOfBirth, Person::setYearOfBirth));

binder.bindInstanceFields(this); // Should not touch yearOfBirth, which is already configured
```
I try to bind a Double manually and the rest by using bindInstanceFields, then I get the Exception:
```
java.lang.IllegalStateException: Property type 'java.lang.Double' doesn't match the field type 'java.lang.String'. Binding should be configured manually using converter.
```

Seems that already bind fields are not filtered out.

**Comment by pleku** [comment]
Thanks for reporting this, but please use https://github.com/vaadin/framework repository instead; this repository was just used internally for 8.0 development before we had migrated the all the framework issues to github.

For the issue itself, there is a unit test for this and looking at the code, it should work as expected, so can you please provide bit more details how to reproduce this ?

**Comment by twiggledi** [comment]
Thank you for your response, I moved this issue to https://github.com/vaadin/framework/issues/8858 and enriched with information. I will close it here.
