### ISSUE TITLE
Basic ListDataSource

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#63]
```
ListDataSource<Person> dataSource =  new ListDataSource<>(persons);
ListDataSource<Status> dataSource = new ListDataSource<>(EnumSet.allOf(Status.class));
```

**Comment by hesara** [comment]
In the feature branch, DataSource.create(Collection / T...) creates such an InMemoryDataSource instance - there is no separate ListDataSource

**Comment by jdahlstrom** [comment]
d60941d083571393efd1107ad48585b434cab1ea // ListDataSource
ba228972ae734f3f596edb7a2382b0df19a1db9c // Renamed to InMemoryDataSource
