### ISSUE TITLE
Update NativeSelect to use a DataSource

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#64]
`setContainerDataSource` and related methods are replaced by `setDataSource`
`setItems` which creates a `ListDataSource`
`setItemCaptionProvider(Function<T,String> captionItemProvider)` which provides the caption for an item

```
public enum Status {
   PRESENT,ABSENT,UNKNOWN;

  public String getCaption() {
    return SharedUtil.capitalize(name().toLowerCase());
  }
}

NativeSelect<Status> s = new NativeSelect<>();
s.setItems(EnumSet.allOf(Status.class));
s.setItemCaptionProvider(Status::getCaption);

```

**Comment by hesara** [comment]
In the feature branch there is a new NativeSelect using a DataSource, but without setItems(), setItemCaptionProvider() and focus/blur listeners. Also a lot of old API from AbstractSelect and AbstractField has been removed from it including item icon support, the obsolete "new items allowed" support and null selection related options. Declarative format support is not yet implemented.

**Comment by jdahlstrom** [comment]
755c893008b11af8d4d46efebbd75cf840664057 and its descendants

**Comment by denis-anisimov** [comment]
As agreed: move old impl to legacy package.
