### ISSUE TITLE
Update ComboBox to use a DataSource

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#65]
`setContainerDataSource` and related methods are replaced by `setDataSource`
`setItems` which creates a `ListDataSource`
`setItemCaptionProvider(Function<T,String> captionItemProvider)` which provides the caption for an item

```
public enum Status {
   PRESENT,ABSENT,UNKNOWN;

  public String getCaption() {
    return SharedUtil.capitalize(name().toLowerCase());
  }
}

ComboBox<Status> s = new ComboBox<>();
s.setItems(EnumSet.allOf(Status.class));
s.setItemCaptionProvider(Status::getCaption);

```

**Comment by denis-anisimov** [comment]
As agreed: move old impl to legacy package.

**Comment by denis-anisimov** [comment]
Similar to #70: Combobox extends AbstarctSelect which is superclass for many many other classes.
