### ISSUE TITLE
Update Grid to use a DataSource

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#66]
`setContainerDataSource` and related methods are replaced by `setDataSource`
`setItems` which creates a `ListDataSource`
`addColumn` has a mandatory second parameter `Function<T,String> valueProvider`

```
Grid<Person> grid = new Grid<>();
grid.addColumn("Name", Person::getName);
grid.addColumn("Year of birth",
  person -> Integer.toString(person.getYearOfBirth()));
List<Person> persons = Arrays.asList(
  new Person("George Washington", 1732),
  new Person("John Adams", 1735),
  new Person("Thomas Jefferson", 1743),
  new Person("James Madison", 1751));

grid.setItems(persons);
```

**Comment by hesara** [comment]
There is a new Grid component in the feature branch with setDataSource() and addColumn(String, Function<T,V>) but no setItems(). The new Grid implementation is still lacking most of the functionality of the original Grid component (renderers, details, ...).

**Comment by denis-anisimov** [comment]
As agreed: move old impl to legacy package.

**Comment by denis-anisimov** [comment]
Depends on #67.

**Comment by tsuoanttila** [comment]
Waiting for review https://dev.vaadin.com/review/#/c/14181/
Initial implementation with many still missing features. Need to add new tickets for missing features.

**Comment by tsuoanttila** [comment]
Base is there. Multiple feature tickets split to their own issues.
