### ISSUE TITLE
Basic DataSource

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#67]
```
DataSource<Person> dataSource = new DataSource<>(
  // First callback fetches items based on a query
  query -> {
    // The index of the first item to load
    int offset = query.getOffset();

    // The number of items to load
    int limit = query.getLimit();

    List<Person> persons = getPersonService().fetchPersons(offset, limit);

    return persons.stream();
  },
  // Second callback fetches the number of items for a query
  query -> getPersonService().getPersonCount()
);
```

**Comment by hesara** [comment]
In the feature branch, currently there are InMemoryDataSource and BackEndDataSource which each take a request - a function mapping a Query to a Stream<T> - but not having a separate method for getting the count.

**Comment by jdahlstrom** [comment]
https://dev.vaadin.com/review/#/c/13864/

**Comment by jdahlstrom** [comment]
c9bd00f902274a00eba371a6ae5907d6a1812b35 // DataSource interface
ba228972ae734f3f596edb7a2382b0df19a1db9c // DataSource to Object->Stream
2a8b0cbe96c4e3fde541fdfa2fcd7cf210b698b5 // DataSource to Query->Stream
