### ISSUE TITLE
Update TwinColSelect to use a DataSource

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#69]
`setContainerDataSource` and related methods are replaced by `setDataSource`
`setItems` which creates a `ListDataSource`
`setItemCaptionProvider(Function<T,String> captionItemProvider)` which provides the caption for an item

```
TwinColSelect<Status> s = new TwinColSelect<>();
s.setItems(EnumSet.allOf(Status.class));
s.setItemCaptionProvider(Status::getCaption);

```

**Comment by denis-anisimov** [comment]
As agreed: move old impl to legacy package.
