### ISSUE TITLE
Create a RadioButtonGroup that replaces the single select case of OptionGroup

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#70]
`setContainerDataSource` and related methods are replaced by `setDataSource`
`setItems` which creates a `ListDataSource`
`setItemCaptionProvider(Function<T,String> captionItemProvider)` which provides the caption for an item

```
RadioButtonGroup<Status> s = new RadioButtonGroup<>();
s.setItems(EnumSet.allOf(Status.class));
s.setItemCaptionProvider(Status::getCaption);

```

**Comment by denis-anisimov** [comment]
As agreed: move old impl to legacy package.

**Comment by denis-anisimov** [comment]
This requires grooming.
OptionGroup is not a big class but a lot of its functionality inherited from AbstractSelect.
AbstractSelect is a superclass for too many classes.

So this issue is not really about OptionGroup.

**Comment by elmot** [comment]
https://dev.vaadin.com/review/#/c/14382/
