### ISSUE TITLE
ItemComparator for Grid

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#72]
```
grid.addColumn("Year of birth",
    person -> Integer.toString(person.getYearOfBirth()))
  // Sort numerically instead of alphabetically by the string
  .setItemComparator(
    Comparator.comparing(Person::getYearOfBirth));
```

**Comment by hesara** [comment]
In the feature branch, Column.setComparator sets a comparator that compares the items.

**Comment by hesara** [comment]
d0e55818de9493f14140716a86ead5b279c70181

**Comment by denis-anisimov** [comment]
Has no sense to do without other changes in Grid where comparator is used: update sort order (the setSortOrder RPC method called from client side) and/or new setDataSource method.
See details in vaadin8 branch.
Without those changes the only changes are : getter and setter for comparator.
And also Column should be made generic to use parameterized comparator.

**Comment by denis-anisimov** [comment]
There is already `setComparator` method in Column.
