### ISSUE TITLE
ValueComparator for Grid

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#73]
```
grid.addColumn("Name", Person::getName)
  // Override default natural sorting
  .setValueComparator(
    Comparator.comparing(String::toLowerCase));
```

**Comment by hesara** [comment]
Currently in feature branch (d0e55818de9493f14140716a86ead5b279c70181) with different name (Column.setComparator(...))

**Comment by hesara** [comment]
Actually the comparator in the feature branch is effectively an item comparator.

**Comment by pleku** [comment]
COULD HAVE, but not necessary for FW8.
