### ISSUE TITLE
In memory filtering for ComboBox

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#74]
```
comboBox.setFilter((filterText, item) ->
  item.getCaption().equalsIgnoreCase(filterText));
```

**Comment by hesara** [comment]
This example here and in the book doesn't really make much sense as it only ever lists items that are identical with each other and the search string apart from case - a contains() or startsWith() based example would be better

**Comment by Artur-** [comment]
agreed

**Comment by denis-anisimov** [comment]
Requires #65.

**Comment by hesara** [comment]
probably implementing in the same patch as #65, as the internal mechanism is needed for it anyway

**Comment by hesara** [comment]
Depends on #166
