### ISSUE TITLE
DataSource SortBuilder

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#79]
```
grid.addColumn("Full name",
    person -> person.getFirstName() + " " + person.getLastName())
  .setSortBuilder(
    direction -> Stream.of(
      new SortOrder("lastName", direction),
      new SortOrder("firstName", direction)
    ));
```

**Comment by hesara** [comment]
Implemented in the feature branch for Grid.Column, not directly on DataSource

**Comment by denis-anisimov** [comment]
The example shows it also for Column, not DataSource.
What's wrong ?  Description or comment with code snippet ?
How it should be ?

**Comment by jdahlstrom** [comment]
Is there some use case where the builder is something else than boilerplate

```
direction -> Stream.of(
      new SortOrder("foo", direction),
      new SortOrder("bar", direction)
      ...
    ))

```

**Comment by jdahlstrom** [comment]
Oh, there's already `setSortOrderProvider` and shortcut `setSortProperty`. So what is this ticket actually about?

**Comment by Legioth** [comment]
So this ticket is about at least two things:
1) Discuss whether the name of the method should be `setSortBuilder` as proposed by BoV or `setSortOrderProvider` as proposed by code that is currently in our master branch
2) Make sure there is at least a unit test that shows how the method is expected to work.

**Comment by pleku** [comment]
SHOULD HAVE, but not necessary for FW8.
