### ISSUE TITLE
Create root demo project

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#8]
https://github.com/vaadin/framework8-demo should contain a root pom file for a multi module project. Does not need to contain much at this point except Vaadin dependencies, TestBench dependencies and the possibility to add new modules

**Comment by Legioth** [comment]
The root pom also include a `jetty-maven-plugin` with at least this configuration:

```
<scanIntervalSeconds>-1</scanIntervalSeconds>
<stopPort>8081</stopPort>
<stopWait>5</stopWait>
<stopKey>foo</stopKey>
```
