### ISSUE TITLE
Remove Liferay theme tests

### ISSUE THREAD

**Issue by hesara** [vaadin/framework8-issues#89]
The tests are run with old browsers and are broken, preventing the build from passing.

**Comment by denis-anisimov** [comment]
Which tests exactly should be removed ?

I've removed LiferayThemeTest classes from the tests/themes and tests/components/uitests (2 classes with the same name).
There are more Liferay theme mentions:

tests/components/table/ColumnHeaderAlignments contains liferay theme as one of the themes to test against.
tests/integration/LiferayThemeDemo - looks like this is not a test. Should it be removed ?

tests/themes/FaviconTest - this doesn't test UI for liferay but rather just check the presence resource available via web. This should be kept as is I suppose.

**Comment by hesara** [comment]
Don't touch this - I'll assign it to myself, as this is very much related to the other one I'm working on

**Comment by denis-anisimov** [comment]
OK......

**Comment by hesara** [comment]
Addressed with #22 in https://dev.vaadin.com/review/#/c/13981
