### ISSUE TITLE
Create an AddressBook demo with in memory backend

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#9]
Same as the Vaadin 7 version, minimal code changes. 
- Declarative views
- Entity changes
  - Add boolean doNotCall ( -> checkbox)
  - Add long createdTimestamp stored as `java.time.Instant` ( -> read only text formatted as YYYY-MM-DD HH:mm:ss)
- Form changes
  - Add EmailValidator
  - Make firstName, lastName required
  - Make email or phone number required
- No changes to the backend service

**Comment by denis-anisimov** [comment]
Do you want to see some checkbox representation in the table for "doNotCall" or it should be just an editor control when a row is selected ?

Table doesn't allow editing in place so it cannot be a real checkbox since it's possible to change its state. But it can be an image which look like  checkbox....
"true/false" as values in the cell doesn't look nice anyway.

**Comment by Artur-** [comment]
All editing should still be in the form. The grid can e.g. show "DO NOT CALL" if it is set to true and leave the cell empty otherwise

**Comment by denis-anisimov** [comment]
OK

**Comment by denis-anisimov** [comment]
> Make email or phone number required

Do you want this (OR) to be implemented in the code (so it's not really regular "required" ) or should I just choose  one and make it required ?

**Comment by Artur-** [comment]
The same field is used for email/phone. The user must either enter an email address (a valid one) or a phone number (a valid one). So the field is required.

**Comment by denis-anisimov** [comment]
What do you mean : the same ?
Look at the picture here: https://github.com/vaadin/addressbook 
There are two fields for email and phone.

**Comment by Artur-** [comment]
Right, I'm thinking about another demo..  So here either email or phone must be filled in, neither field is required in the Vaadin 7 sense

**Comment by denis-anisimov** [comment]
OK.

**Comment by denis-anisimov** [comment]
https://github.com/vaadin/framework8-demo/pull/3

**Comment by denis-anisimov** [comment]
Depends on #101 and #102..
