### ISSUE TITLE
Consider renaming Binder.forField()...bind()

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#90]
Instead of 
`binder.forField(titleField).bind(Person::getTitle, Person::setTitle)`

I would find it clearer to use a "bind ... to" API, like
`binder.bind(titleField).to(Person::getTitle, Person::setTitle)`
This change would make the current `bind` helper (which is not very symmetric with `forField...bind` quite unnecessary as there is no much difference between

```
binder.bind(titleField, Person::getTitle, Person::setTitle)
binder.bind(titleField).to(Person::getTitle, Person::setTitle)
```

**Comment by hesara** [comment]
Is the old form used in BoV volume 1?

**Comment by Artur-** [comment]
Related to forField/bind is also the issue that "bind" currently means "bind field to a getter and setter" and also "bind all fields to a backing bean". Only changing to "bind...to" would make bind mean "bind to a field" but also at the same time "bind to a bean". 

In either case, the bind(bean) method should be named something else

**Comment by pleku** [comment]
@Legioth please clarify is this a part of the "new DoDo" and add or close.

**Comment by Legioth** [comment]
We won't do this.
