### ISSUE TITLE
Rename Binder load, save, saveIfValid and bind

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#91]
- `Binder.load(T bean)` is renamed to `readBean`
- `Binder.save(T bean)` is renamed to `writeBean`
- `Binder.saveIfValid(T bean)` is renamed to `writeBeanIfValid`
- `Binder.bind(T bean)` is renamed to `setBean`

Fix all the documentation (by hand) and demos (eclipse handles).

**Comment by pleku** [comment]
@Legioth please clarify is this a part of the "new DoDo" and add or close.

**Comment by pleku** [comment]
https://dev.vaadin.com/review/#/c/14639/
