### ISSUE TITLE
Pass locale to converter

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#94]
In Vaadin 7 the converters get the component locale, currently the converters only get the value. The active locale should be passed as a second argument

**Comment by jdahlstrom** [comment]
This makes composition more difficult (eg. no setConverter(Integer::valueOf, String::valueOf) without even more helper overloads, no more simply composing/flatMap to chain converters). Many (most?) converters don't need locale awareness, including our builtin ones. Those that need can get it from the closure (if built from lambdas) or via constructor (there aren't many use cases where the locale of a field changes at runtime - and even those can work by passing a Supplier<Locale> instead). By some trickery we can provide a helper for constructing locale-aware converters from (BiFunction, BiFunction).

**Comment by Artur-** [comment]
How would this affect creating a converter using Integer::valueOf, String::valueOf? That would just be a converter which does not use the locale for anything

**Comment by Artur-** [comment]
This is in https://github.com/vaadin/vaadin/commit/f2bb3c886c0b68c9a4e8212d6625614575148f80
