### ISSUE TITLE
Document selection binding in Book of Vaadin

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#96]

**Comment by denis-anisimov** [comment]
What's selection binding ?
Please point to the issues which this issue depends on whose implementation may be used as a reference to API.

**Comment by Artur-** [comment]
It should basically answer the questions
- How do you bind the value of a ComboBox<Country> to a Country field in a Person bean
- How do you bind the selection of a multiselect OptionGroup to a List<String>

Listings are not fields and do not implement `HasValue`. The selection model implements `HasValue` and binding should be done using `Binder`, similarly to how you bind a field right now

Related issues: #160 #161 #86

**Comment by pleku** [comment]
As of #396 Listing implement HasValue, which means that this is mostly about reacting to selection change ? OR just showcasing that for Listings the selection is what is being bind to ?

**Comment by Legioth** [comment]
As long as `SelectionModel` is a fundamental concept in the components, then that concept should be documented.

**Comment by pleku** [comment]
Done
