### ISSUE TITLE
Consider making Converter.toField also return a Result

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#97]
`fromField` returns a `Result<DataType>` while `toField` returns FieldType. This is documented as "Converting to the field type should always succeed, so there is no support for returning an error Result.". In reality, there is no guarantee that converting in that direction always succeeds to instead toField will throw a RuntimeException for problems while fromField will return an error result.

**Comment by jdahlstrom** [comment]
Returning a "validation result" is not useful when something fails that the user cannot do anything about except refresh. However, extending Result to return messages of different severities has been discussed. Any error from `toField` would still have to just propagated to the core error handling mechanism.

**Comment by Artur-** [comment]
You seem to advocate that converters are only for Binder instead of being a generic concept like in Vaadin 7, why is that? Not only is it strange to use and write the non symmetric converters but doing something like a reverse converter is even worse as the direction where "everything should always be ok" is now the "this might fail" direction

**Comment by Legioth** [comment]
How should the application behave if conversion fails in the toField direction?

**Comment by Artur-** [comment]
I don't think that is relevant? Right now you would get an exception, which is probably unhandled and things will be broken. If you get a Result, you CAN handle the error as opposed to now when you CANNOT handle the error

**Comment by Artur-** [comment]
Also keep in mind that the name of the method is the same as in Vaadin 7, not toField()

Right now it is

```
    public Result<MODEL> convertToModel(PRESENTATION value, Locale locale);
    public PRESENTATION convertToPresentation(MODEL value, Locale locale);
```

**Comment by Legioth** [comment]
What is the use case you want to support?

**Comment by Artur-** [comment]
Let's put it the other way, what use case do you want to support with the current version...?

Making reverse converters is strange if the API is not symmetric. Probably makes more sense for non-String fields like DateField<LocalDate> <-> Date or v7.DateField<Date> <-> LocalDate and others

**Comment by Legioth** [comment]
The reason to have them asymmetric is to make it clear that conversion in on direction is never expected to fail, since that would be a bug in the software instead of unsupported user input.

I still don't see why you'd ever need to reverse a Date -> LocalDate converter since the v7 DateField does not support the new converter API

**Comment by pleku** [comment]
COULD HAVE, but not necessary for FW8.
